### ISSUE TITLE
Failure to play encrypted HLS

### ISSUE THREAD

**Issue by iroha7941** [videojs/video.js#7051] opened 2021-01-20 01:24 UTC
## Description
An encrypted HLS file that plays properly on iPadOS instead causes video.js to crash on Linux and Windows.

Test case:  [example.zip](https://github.com/videojs/video.js/files/5839559/example.zip)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.  Unzip the example.zip file.
2.  Attempt to play the video using the included test.html.

### Expected
Expected playback to succeed.

### Actual
Playback fails on Linux and Windows.

### Error output
Error is "Uncaught TypeError: h is undefined" on Linux and "Uncaught TypeError: Cannot read property 'video' of undefined" on Windows.

#### videojs
Tested with Videojs version 7.10.2
#### browsers
Tested with Firefox on Linux, Chrome on Windows, Safari on iPadOS
#### OSes
Linux Fedora 32, Windows 10, iPadOS 14.3
### plugins
No plugins

**Comment by iroha7941** [comment] 2021-01-20 16:02
Here is an updated example which shows why I believe the issue lies in decryption:  
[example-2.zip](https://github.com/videojs/video.js/files/5843653/example-2.zip)

This updated example contains the same video in both encrypted and unencrypted form.  Both videos can be played on iPadOS, but only the unencrypted video plays on Linux/Windows.  The updated example also has a shell script that shows how the video files are generated/encrypted, if that is of any interest.

Thanks for any help you can provide.

**Comment by gkatsev** [comment] 2021-01-21 17:20
It looks like AES-128 encryption with fmp4 isn't working. Going to close this as a duplicate of https://github.com/videojs/video.js/issues/6893 to keep everything in one ticket.

**Closed by gkatsev** 2021-01-21 17:20 UTC
