### ISSUE TITLE
autoSetup problem

### ISSUE THREAD

**Issue by ri0ter** [videojs/video.js#2788] opened 2015-11-07 03:15 UTC
I have a problem with vjs, sometimes it doesn't setup all my video tags on the page.
I've found out that it happens if there's a something that blocks dom rendering. It's because of the `autoSetup ` function - it stops executing if it finds at least one video element on the page. So in my case if it'll find the first video and after that there's a script that blocks the dom rendering it won't find the rest of the videos.

Maybe a solution would be to change the `autoSetup ` to continue until the dom is loaded even if it'll find something?

**Comment by misteroneill** [comment] 2015-11-07 16:43
Interesting. Where in your document is the video.js `<script>` element?

I think your proposed solution sounds fairly reasonable; though, I'm not sure how common this scenario might be.

**Comment by ri0ter** [comment] 2015-11-07 17:00
I've tried to recreate this scenario. You might try this code:
```
<!DOCTYPE html>
<html>
	<head>
	<meta charset=utf-8 />
	<title>Video.js blocking script example</title>
	  
		<link href="http://vjs.zencdn.net/5.0/video-js.css" rel="stylesheet">
		<script src="http://vjs.zencdn.net/5.0/video.js"></script>
		<script>
			function sleep(miliseconds) {
				   var currentTime = new Date().getTime();
				   while (currentTime + miliseconds >= new Date().getTime()) {
				   }
			   }
			sleep(1000)
		</script>
	</head>
	<body>
		<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="360" data-setup='{}'>
			<source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
			<source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>
		</video>
		
		<script>
			sleep(1000)
		</script>
	  
		<br>
	  
		<video id="my_video_2" class="video-js vjs-default-skin" controls preload="auto" width="640" height="360" data-setup='{}'>
			<source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
			<source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>
		</video>
	</body>
</html>
```

I don't know why this example doesn't work without the first execution of sleep in  the head, but i assume that if you have few scripts in the head it might work the same way.

**Comment by gkatsev** [comment] 2016-03-29 17:48
Closing as a duplicate of https://github.com/videojs/video.js/issues/2386

**Closed by gkatsev** 2016-03-29 17:48 UTC
