### ISSUE TITLE
closed caption is not working in chrome with latest version videojs v5

### ISSUE THREAD

**Issue by jothikannan** [videojs/video.js#2817] opened 2015-11-16 14:00 UTC
It's weired to me that closed captions is not working in chrome , working fine in FF and other browsers

Even  i can't see the closed caption menu, which say Caption off when i find with Firebug

Attached is fiddle : http://jsfiddle.net/7s3pn6hr/1/

**Comment by gkatsev** [comment] 2015-11-16 21:36
This is a duplicate of #2689.

**Closed by gkatsev** 2015-11-16 21:36 UTC
