### ISSUE TITLE
You aborted the video playback

### ISSUE THREAD

**Issue by seabasss** [videojs/video.js#4940] opened 2018-02-07 20:54 UTC
I have a download button to download the movie file. It goes through a php script that asks the user to save the file to disk. It all works, but as soon as I click download the videojs player gets disabled and a message pop up that the video playback was aborted. Is there any way around this?

I tried "errorDisplay: false", but I don't want to disable all error messages, and that also seems to remove all the controls making it impossible to scrub or hit play or paus.

Ideas? Thanks!

**Comment by gkatsev** [comment] 2018-02-07 22:54
You could listen to the error event and then call `player.error(null)` to hide the error in this case. What does the button do in the player? A live example might be nice, maybe there's a better way of doing it that doesn't cause the player to break.

**Comment by seabasss** [comment] 2018-02-07 23:03
@gkatsev It is just a link outside of the player that is pointing towards a php file with this code in it, that fetches the same video file that is currently playing. I don't know if the player wants to stop the video because a different call is made or if it is because the call is trying to access the same file that is currently playing. I guess I could just find out by linking to a different file and see if it still happens. In either case, maybe that is enough for you to get an idea what it can be about? Thanks!

`<?php

$filepath = 'x';
$title = 'y';
$download = true;

header("Cache-control: private");

header("Content-Type: application/octet-stream");

if ($download) {
       header("Content-Disposition: attachment; filename=\"" . $title . "\"");
       header('Content-Transfer-Encoding: binary');
} else {
       header("Content-Disposition: inline; filename=\"" . $title . "\"");
}

// Disable caching
header('Cache-Control: no-cache, no-store, must-revalidate'); // HTTP 1.1.
header('Pragma: no-cache'); // HTTP 1.0.
header('Expires: 0'); // Proxies.

readfile($filepath);

exit;

?>`

**Comment by gkatsev** [comment] 2018-02-07 23:20
Using the same file could cause an issue based on how browsers handle loading of media. One thing to try is adding a query parameter to the download link so that the browser treats it as a separate request.

**Comment by seabasss** [comment] 2018-02-07 23:46
@gkatsev Thanks! I just tried it again, and it aborts even on a completely different file. The video keeps playing, but the message comes up and the controls disappears. I also tried a query parameter but it didn't work.

Other ideas?

**Comment by gkatsev** [comment] 2018-02-08 00:44
Could your backend be aborting the original request to the video when serving the download request?

**Comment by gkatsev** [comment] 2018-02-08 00:50
Unfortunately, I am unfamiliar with php so would not be able to help but maybe you can log each time you return data and then check to see if it continues happening after the download button is clicked?
Also, if you make the download link download from a different server, it should tell you whether the backend is at fault or not.

**Comment by seabasss** [comment] 2018-02-08 01:25
@gkatsev This is what the console says. `VIDEOJS: ERROR: (CODE:1 MEDIA_ERR_ABORTED) You aborted the media playback 
Object { code: 1, message: "You aborted the media playback" }`

**Comment by gkatsev** [comment] 2018-02-08 01:27
it sounds like the backend closed the connection. Also, I meant logging in your backend not in video.js.

**Comment by seabasss** [comment] 2018-02-08 01:37
@gkatsev Yeah it's weird, I don't know what to do. The video keeps on playing. It just says that I aborted it, dims it down and removes the controls. I don't know how to check the backend unfortunately.

**Comment by gkatsev** [comment] 2018-02-08 17:28
If you try playing a different video from a different server (for example `http://vjs.zencdn.net/v/oceans.mp4`) and then click the video download, does oceans continue playing? Also, if you try the opposite, you play your video but then set up the download link to download a video from a different server like oceans, does the video continue playing?

However, all signs point at the backend up being able to handle this properly. I'm not familiar with PHP and this isn't really the proper forum for debugging a hosting server. I'm going to close this because it's very unlikely it's a problem with Video.js. But if it does turn out to be, we can re-open. Also, we can definitely continue the discussion in here even if the issue is closed.

**Closed by gkatsev** 2018-02-08 17:28 UTC

**Comment by mmoebius** [comment] 2020-04-03 12:13
I can also recognize this. But this problem only exists in firefox. This error is also fired, if the user click to a link and open a new site in the current tab.

**Comment by usman64** [comment] 2020-11-26 07:11
I'm also facing the same issue in Firefox. When I click the download button the video keeps playing, but there an error "You aborted the media playback" in the video player and an error in the console "VIDEOJS: ERROR: (CODE:1 MEDIA_ERR_ABORTED) You aborted the media playback".

Has anyone found the solution to this problem?
