### ISSUE TITLE
Fullscreen player poster and no preload aspect ratio inconsistency

### ISSUE THREAD

**Issue by third774** [videojs/video.js#6846] opened 2020-09-16 22:36 UTC
## Description
When hitting play for the first time, the poster is hidden revealing the video element which does not display with the correct aspect ratio briefly before playback begins. This is much more noticeable on slower connections.

[Reduced test case](https://codepen.io/third774/pen/BaKOorN?editors=1100)

## Steps to reproduce
When the follow criteria are met:

1. Player's dimensions are not fixed pixel values (using viewport in example)
2. `preload` is set to `none`
3. `poster` attribute is set and matches video's aspect ratio

Hit play (in Chrome) and the issue should be visible.

### Expected
I expect the video element to display with the same aspect ratio as the poster.

### Actual
The video element stretches the poster to a different aspect ratio before correcting itself.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
latest
#### browsers
Chrome 85.0.4183.83
#### OSes
macOS 10.15.5
### plugins
N/A

**Comment by gkatsev** [comment] 2020-09-21 21:48
I can reproduce it if I set the connection to slow 3g before hitting play.
I can actually reproduce it without Video.js. Seems like this is a Chrome issue.

**Comment by third774** [comment] 2020-11-23 19:27
Should we keep this issue open to continue tracking?

**Comment by gkatsev** [comment] 2020-11-30 22:17
We can. Last I checked there wasn't a bug opened against chrome. Would be good to open a bug against it if one still doesn't exist.

**Comment by gkatsev** [comment] 2020-12-01 16:41
I opened a bug with Chrome for this: https://crbug.com/1154296

**Comment by gkatsev** [comment] 2020-12-01 16:50
Going to close this now as we have a crbug. I'll probably circle back here if the issue is ever fixed.

**Closed by gkatsev** 2020-12-01 16:50 UTC
Labels: browser bug

**Comment by third774** [comment] 2020-12-01 19:09
Awesome! Thanks for opening!

**Comment by mister-ben** [comment] 2021-02-26 13:47
That's fixed in Chrome 90, currently canary
