### ISSUE TITLE
Android mobile: Fullscreen button not working

### ISSUE THREAD

**Issue by netsetter** [videojs/video.js#2160] opened 2015-05-17 14:11 UTC
First, thank you for this great HTML5 Player framework, good job!

I've integrated it (version 4.12.6) into the website and everything is running fine (.mp4)
Checked all recent browsers and all component buttons are working, except with the default browser on the android device (version 4.4.2), the fullscreen button of the player is completly ignored.

Is this already a known issue? Any idea how to fix? 
When browsing videojs.com, clicking the intro video, same issue, when pressing the fullscreen icon, switching to fullscreen mode is completly ignored, no error message. 

Best regards

**Comment by Ampelmann23** [comment] 2015-06-28 12:37
Hi netsetter!

I have the same problem. - Do you have a solution for this so far?


Greetings,
-Mirco-

**Comment by WangHaoming** [comment] 2015-08-10 07:35
I have the exacted same problem! Do you have any solution so far?

**Comment by giggioman00** [comment] 2015-09-30 13:35
Same issue here

**Comment by gkatsev** [comment] 2015-11-17 22:39
In v5, we now default to native controls for native android browsers, so, I assume this isn't an issue anymore. See https://github.com/videojs/video.js/pull/2499
Closing, but can reopen if there's still an issue.

**Closed by gkatsev** 2015-11-17 22:39 UTC

**Comment by tonyawad88** [comment] 2015-11-21 20:11
@gkatsev This is still an issue on Android. Running Crosswalk version 15. On iOS it works fine, iOS / Safari Mobile. The problem is that when I click the full screen button on Android, the whole page flickers and the video remains to play in non-full screen mode. 

If I hold my thumb on the full-screen button for a couple seconds it successfully goes to full screen, hitting the full screen button once / tap once, doesn't work.

Any idea if there is a fix for this ? 

Thank you,

**Comment by braianj** [comment] 2016-03-18 03:37
found [this](https://github.com/videojs/video.js/issues/1995#issuecomment-88867136), just checking right now

**Comment by 5ulo** [comment] 2016-07-17 23:26
Problem still present - latest video.js, android 5.1, chrome

**Comment by mkeefe** [comment] 2016-07-25 19:29
Any proposed fix for this? Blocking a live app release. Tried requestFullScreen() both in a user-driven event and pragmatic. I either will see "method does not exist" or simply ignore the request outright.

As a quick test I tried the events for when you enter/leave fullscreen and those also are ignored. Tested on numerous Android devices new/old. Any ideas?

**Comment by gkatsev** [comment] 2016-07-25 20:27
As far as I can tell it's because a lot of native WebViews on Android don't have the native Fullscreen API and our [functionality to try and get the correct API](https://github.com/videojs/video.js/blob/master/src/js/fullscreen-api.js) isn't working on it.

It's possible that the WebView only lets the video element itself go into fullscreen like iOS does in a lot of cases (they still don't use the fullscreen API but their own thing). We potentially want to call [this method](https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js#L549-L581) on Android as well as on iOS. [This](https://github.com/videojs/video.js/blob/master/src/js/player.js#L1674) is where the check is made.

**Comment by dreasn** [comment] 2020-03-23 05:17
It might be late but for those who got here:
Add these attributes to the wrapper node (mine is iframe):

allowfullscreen="true" 
webkitallowfullscreen="true" 
mozallowfullscreen="true"
