### ISSUE TITLE
Progress bar woes on 5.0.0

### ISSUE THREAD

**Issue by tfr** [videojs/video.js#2652] opened 2015-09-30 08:33 UTC
Hi,

coming here with the previous issue I discovered that 5.0.0 is now out (was running on 4.12 before). So I upgraded in hopes that it just might fix my problems, but instead, unfortunately, it created a small new one:

Now the video player shows the "LIVE" badge and the progress bar starts off somewhere in the middle. Below attached is a sample of a 48 second video that I just started.

![screenshot 2015-09-30 11 29 42](https://cloud.githubusercontent.com/assets/100969/10188318/06d9f380-6767-11e5-993a-7852258fd46c.png)

Since the video is stored in a web app, it's dynamically served through a PHP script - might this be the culprit?

TIA,
Indrek

**Comment by mmcc** [comment] 2015-09-30 17:47
Well the styling issues across the control bar is an issue regardless. The ordering on the right side is strange and the time remaining / live component shouldn't be at the top of the control bar like that. Do you have a live example that we can take a peek at?

Re: delivery, the only times I've seen issues on this tracker involving video dynamically served via PHP, it's been the culprit. For varying reasons, so unfortunately I don't have a "oh it's probably this" kind of answer, but it's consistently been the root cause :(

**Comment by gkatsev** [comment] 2015-10-19 15:54
Only other thing I can think off is that the browser you're running this on isn't fully supported by our css (for whatever reason). What browser are you using?

**Comment by tfr** [comment] 2015-10-19 16:02
I'm running the latest and greatest Safari. But looks like this problem has somehow magically solved itself in the meantime.

**Comment by gkatsev** [comment] 2015-10-19 16:05
Huh, weird. Can we close the issue then and re-open if it re-manifests itself?

**Comment by tfr** [comment] 2015-10-19 16:07
Fine by me.

**Comment by gkatsev** [comment] 2015-10-19 16:10
Cool, closing for now then.

**Closed by gkatsev** 2015-10-19 16:10 UTC
