### ISSUE TITLE
Flash doesn't work

### ISSUE THREAD

**Issue by fluctuate** [videojs/video.js#4377] opened 2017-05-24 12:19 UTC
## Description
I can't use Videojs in Flash mode, i can see only a black background and play button, there is no an error message.

#### Some detail
- Video type: flv format
- Tag Proprty: data-setup='{ "techOrder":["flash"] }'

#### Reduced test case
See a reduced case:  http://bit.ly/2qfXAPC

#### Videojs Lib version
Version: 6.0.1.

#### Affected Browsers
All browsers that still can have Flash enabled/installed. (Android (Chrome, Firefox ) & iOS (Safari) can't run Videojs in flash mode because they have no more flash support)

**Comment by gkatsev** [comment] 2017-05-24 15:28
As we have [announced](http://blog.videojs.com/Video-js-removes-Flash-from-core-player/) and [documented](https://github.com/videojs/video.js/blob/master/CHANGELOG.md#breaking-changes), Flash is no longer available directly in Video.js by default in version 6.0. You should include [`videojs-flash`](https://github.com/videojs/videojs-flash) on your page.

Hope that helps.

**Comment by fluctuate** [comment] 2017-05-24 16:34
Yes, i already know this, see the test case.
All that i don't know is, why this code doesn't work ?


`
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />	
    <link href="https://vjs.zencdn.net/6.0.1/video-js.css" rel="stylesheet" >
    <script src="https://vjs.zencdn.net/6.0.1/video.js" ></script>
    <script src="https://flit.quadratica.eu/includes/customStuffs/video/players/videojs-flash/assets/js/videojs-flash.min.js" ></script>
</head>

<body>
<div style="width:100%; text-align:center; " >Video/flv</div>
<br/>
<video 
	id="my-video-1" 
	class="video-js" 
	controls="" 
	data-setup='{ "techOrder":["flash"] }'
	style="width:320px; height:200px; margin:auto; " 
>
	<source src="https://flit.quadratica.eu/images/video/media/Lupin_3.flv" type='video/flv'>   
</video>

</body>
`

**Comment by mister-ben** [comment] 2017-05-24 16:50
Can you update to videojs-flash 2.0.0? I think videojs/videojs-flash#10 will have fixed this for you.

**Comment by fluctuate** [comment] 2017-05-24 17:11
Ok thank yo, ubut i can't find v2.0 of lib videojs-flash

**Comment by mister-ben** [comment] 2017-05-25 08:43
https://github.com/videojs/videojs-flash/releases
There's also unpkg.com: https://unpkg.com/videojs-flash@2.0.0/dist/videojs-flash.min.js

**Comment by fluctuate** [comment] 2017-05-25 11:10
Thank you

**Comment by fluctuate** [comment] 2017-05-25 11:28
I've tried the version 2.0 and FLV still doesn't work (while mp4 works fine).
Here is the (updaed) reduced test: http://bit.ly/2qfXAPC

I can't understand why this 3d was closed, it's still not resolved.

**Comment by gkatsev** [comment] 2017-05-25 15:06
Sorry, I closed it because I thought the flash project wasn't being included. This is definitely an issue but looking at it some more, it seems like the issue is with the CDN release of Video.js and not because of a broken videojs-flash.
I'll work on fixing it.

**Comment by gkatsev** [comment] 2017-05-25 17:19
@fluctuate I think I fixed it. Can you confirm?

**Comment by fluctuate** [comment] 2017-05-25 20:55
@gkatsev 
Now it works! Thank you very much!

**Comment by gkatsev** [comment] 2017-05-25 20:57
Awesome. Thanks for reporting. Closing for real now :)

**Closed by gkatsev** 2017-05-25 20:57 UTC
