### ISSUE TITLE
body zoom error

### ISSUE THREAD

**Issue by ramonvictorn** [videojs/video.js#5389] opened 2018-08-20 14:46 UTC
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

When I zoom out the player identifies that the mouse is in a different place from the right

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.Zoom out the body of the page
2.Put the mouse on the timeline
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by alex-barstow** [comment] 2018-08-20 16:11
Can you please provide a reduced test case from [this template](http://jsbin.com/axedog/edit?html,output) and describe in more detail the problem you are seeing and how to reproduce it? For example, how exactly are you "zooming out" the page, what browser and operating system are you using, etc.

**Comment by Akxe** [comment] 2018-08-22 12:56
I would close it, it can be re-created, once it has all properties filled

**Comment by misteroneill** [comment] 2018-08-29 13:41
@Akxe We typically don't close issues just because they're missing something to reproduce them. We have automation that will close the issue for us if it becomes stale.

**Closed** 2018-10-30 12:06 UTC
Labels: wontfix
