### ISSUE TITLE
One play.js Two Streams PIP

### ISSUE THREAD

**Issue by rayj00** [videojs/video.js#6618] opened 2020-04-24 13:20 UTC
So bear with me as I try to articulate my issue.

I am generating a live stream using HLS and using video.js (v7.3.0) to play it from play.js.  I can view it just fine, PIP works just fine.

Now, if I start a second stream, it also plays fine and I can view either stream from separate browser tabs. PIP works fine also.

The problem is if I am using PIP on the first steam, it goes away when I use PIP on the second stream. 

Ah, but if I view stream1 with Chrome and stream2 with Firefox, the PIP works fine and I can PIP with both streams at the same time.

I guess the first question is I don't actually know if I am using video.js properly or not?  Am I correct that I can use one instance of video.js to play multiple live streams?

And second, shouldn't I be able to PIP on two different streams using the same browser on different tabs?

Thanks,

Ray

**Comment by gkatsev** [comment] 2020-04-24 17:07
This is a duplicate of https://github.com/videojs/video.js/issues/6612

**Closed by gkatsev** 2020-04-24 17:07 UTC
