### ISSUE TITLE
Autoplay (muted or unmuted) doesn't work in Chrome with latest video.js

### ISSUE THREAD

**Issue by WillMuijrers** [videojs/video.js#5233] opened 2018-06-06 11:24 UTC
## Description
Using the CDN of the latest video.js version the `autoplay` doesn't seem do to anything in Chrome. I'm well aware of the limitations of Chrome. Even applying `muted` does nothing. 
When using an old version of video.js (i used 6.4.0) the autplay and muted work as aspected.

## Steps to reproduce
```
// version 7.0.4 -> doesn't work 
// version 6.4.0 -> works fine
<video muted class="video-js" id="player"> 
     <source src=http://techslides.com/demos/sample-videos/small.mp4 type=video/mp4>
</video>

var player = videojs("player");

player.ready(function() {
      player.play();
  });
```
### Error output
When muted is **not** applied, one would expect a console error from Chrome. This also does not seem to happen.

**Comment by dszewczyk1** [comment] 2018-06-18 11:29
I also have a problem with autoplay, in a bit different code, as it should start playing just by adding "autoplay" attribute, not by running it manually.

` <script src="https://vjs.zencdn.net/7.0.4/video.js"></script> // worksw with 6.7.1 
<video class="video-js" data-setup='{ "controls": true, "preload": "auto", "loop": true, "autoplay": true, "muted": true}'> 
     <source src="http://techslides.com/demos/sample-videos/small.mp4" type=video/mp4>
</video>`

It seems to work in Chrome in 6.7.1 for example, but not with any newer version
http://jsbin.com/ribacaxezu/1/edit?html,output

**Comment by Sizzahandz** [comment] 2018-06-21 09:52
Someone have a fix for this?

**Comment by gkatsev** [comment] 2018-06-21 18:41
We just merged #5209 which gives a few more tools to get autoplay working. I am able to get autoplay working with latest Video.js but I can also confirm seeing autoplay not working properly in the example that @dszewczyk1 posted.

**Comment by richardlnnr** [comment] 2018-06-28 18:00
You can use `oncanplay="this.muted=true"` on your video tag

    <video  muted loop autoplay oncanplay="this.muted=true">
        <source src="your src" type="video/mp4">
        Your browser does not support HTML5 video.
    </video>

**Comment by mysuf** [comment] 2018-08-06 16:55
I can confirm that too. I can also say that it happend somewhere between v6.7.4(works) and v6.10.0(doesnt work) and probably will be somehow related to cloning video tag and its attributes..

**Comment by ksperling** [comment] 2018-08-10 05:17
I'm running into the same issue (Chrome 67.0.3396.99).

I've created a small JSFiddle reproducing the problem: https://jsfiddle.net/karstenlh/96hrzp5w/

`manualAutoplay_` seems to be called twice. The first time around tech isn't ready, so it does nothing. The second time it calls `play`, however `changingSrc_` == true so play just sets up the `playOnLoadstart_` callback, and doesn't even return a promise. However that callback never gets called as `loadstart` has already happened.

I'm not really familiar enough with videojs internals to diagnose this further.

**Comment by gkatsev** [comment] 2019-01-03 21:43
Anyone able to check latest chrome? I'm no longer able to reproduce this. Seems like this was a browser bug all along.

**Comment by gkatsev** [comment] 2019-01-03 21:52
We reverted #4804 because we noticed that it was no longer needed in newer version of chrome and so it was reverted in #5009. We could potentially bring that piece of code back in, though, I'd prefer to leave it out if we can. Also, if it's still an issue with chrome 71, we should probably open a bug with chrome.

**Comment by gkatsev** [comment] 2019-01-03 21:55
@afridley made a nice example for us to try out https://jsfiddle.net/afridley/dvLgr1cb/. For me, on macos and chrome 71, all players on that example autoplay properly.

**Comment by dszewczyk1** [comment] 2019-01-08 14:21
@gkatsev yes, it seems to work now in Chrome, so this looks like their issue after all...

**Comment by mysuf** [comment] 2019-01-08 18:40
yup, its working also in Windows Chrome 71

**Comment by gkatsev** [comment] 2019-01-08 18:44
Thanks for confirming!

**Closed** 2019-01-08 20:47 UTC
Labels: pinned

**Comment by gkatsev** [comment] 2019-01-08 20:48
Let us know if you find it broken again, I'll open an issue with chrome if it happens again.

**Comment by sorxrob** [comment] 2020-05-14 00:04
Autoplay sometimes work, mostly not.

Chrome Version 81.0.4044.138 (Official Build) (64-bit)
