### ISSUE TITLE
There's no big play button visible on Windows Phone 8.1

### ISSUE THREAD

**Issue by anttimo** [videojs/video.js#1669] opened 2014-11-18 13:03 UTC
When videojs.com is opened on Windows Phone 8.1 it can be seen that there's no big play button visible on the demo video player. When video playback is started by touching the video, controlbar controls work correctly so this issue is only about the the big play button.

ps. I only have Windows Phone 8.1 so don't know if same can be reproduced on a Windows Phone 8

**Comment by MacGivens** [comment] 2015-03-01 22:52
We've been testing video.js on our Windows Phone 8.1 devices and yes, we're seeing this issue too.

**Comment by smohadjer** [comment] 2015-05-15 10:15
I see the problem too...

**Comment by Voodoc** [comment] 2015-08-13 13:03
Is there a solution?

**Comment by heff** [comment] 2015-08-13 19:27
Anyone willing to dig in and help figure out what the issue is?

**Comment by mmcc** [comment] 2015-08-13 19:33
To be blunt, Windows Phone 8.1 has so little market share it's hard to justify spending too much time on this. Last data I saw had Windows Phone controlling less than 3% of the mobile market, with 8.1 accounting for ~50% of that.

**Comment by gkatsev** [comment] 2016-07-25 22:27
Any PR to improve the behavior on windows phone 8.1 would be welcome. However, we're unlikely to get around to fixing it ourselves. With the small market share and Microsoft seemingly distancing themselves from Windows Phone, I'm going to close this issue

**Closed by gkatsev** 2016-07-25 22:27 UTC
Labels: browser bug, bug, confirmed
