### ISSUE TITLE
Pausing and restarting

### ISSUE THREAD

**Issue by Tralapo** [videojs/video.js#1957] opened 2015-03-18 14:14 UTC
Dear VideoJS devs, you are all doing an awesome job. Credits for this beautiful project.

But I run into a problem that, in my opinion, should be fixed. It's related to streaming live-streams in HLS and RTMP. The problem is some kind of the same for both protocols, but also a little bit different. The main point for both problems is restarting a stream after hitting the pause button.

When using RTMP, the problem seems to be the biggest. When hitting pause, you simply can't restart the stream. You can hit the play button as much as you like, but the player won't start streaming again. That doesn't seem normal to me.

Luckely, I can work around that problem, thanks to a post on [StackOverflow](https://stackoverflow.com/questions/25446868/videojs-doesn%C2%B4t-play-after-pause-rtmp-live-stream/28632288#28632288). In video.dev.js, you need to find this line:

```javascript
vjs.Flash.prototype.play = function(){
    this.el_.vjs_play();
};
```

And replace it with this:

```javascript
vjs.Flash.prototype.play = function(){
    this.el_.vjs_load();
    this.el_.vjs_play();
};
```

It's quite a simple solution which does exactly what it should do: when hitting play after pause, the player reloads the stream and starts playing again (and live! it's not hanging in the past).

But, the solution above does not cover the problem with HLS on mobile devices. Here you can pause the player, but when you hit the play button again, it starts streaming again where it was when I hit pause. So if I've been away for 15 minutes en hit play again, I'm looking at things that happend 15 minutes ago.

In my opinion, that's not how it should be. I understand HLS working that way, but in my opinion I should get the newest images right away.

 With 4.11, I used this solution, also from StackOverflow, which did exactly what I wanted for HLS on mobile devices. It reloads and starts the stream again.

```javascript
<script type="text/javascript">
var myPlayer = videojs('videoID');
videojs("videoID").ready(function(){
var myPlayer = this;
myPlayer.on("pause", function () {
myPlayer.on("play", function () { myPlayer.load (); myPlayer.off("play"); });
});
});
</script>
```
But, that solution stopped working for 4.12.

Somebody know how I can make it work again for HLS in 4.12? Or maybe a more robust solution for both problems?

**Comment by dolartoday** [comment] 2015-03-18 21:33
I can confirm the issue, also, this makes the IMA Google Framework Ads unusable as the live stream will NOT restart after a pre-roll is run. I believe this is a show stopper. We are a pretty big news outlet evaluating players for LIVE streaming, and this is basically a reason to consider FlowPlayer or JWPlayer instead

**Comment by mmcc** [comment] 2015-03-19 00:45
Closing this because it's a duplicate of #1920 (and reopening the original).

**Closed by mmcc** 2015-03-19 00:45 UTC
Labels: duplicate
