### ISSUE TITLE
Video playback bug in Electron

### ISSUE THREAD

**Issue by Art2B** [videojs/video.js#2508] opened 2015-08-24 16:33 UTC
Hi, 

I'm building an app with [Electron](http://electron.atom.io/) and Videojs.
When I test my app in browser with a simple Apache web server, everything works fine, I have no problems.

But when I build my app within an asar file and run it with Electron, the video will play but I'll got the following error when I try to close the video or advance the video:

VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The video playback was aborted due to a corruption problem or because the video used features your browser did not support.

And then the video will show an error message with the same text, and close herself and let a black space with a cross. 

Here is some informations about the video: 
Dimensions: 1920*1080
Codec: H.264
Framerate: 25 frames per second
Bitrate 5009 

How can I fix this ?

PS: Sorry, but I can't join repo or images, there's a confidentiality policy on the project, I can't talk about it. I'm working on making a usable demo which reproduce the bug.

**Comment by heff** [comment] 2015-08-24 17:59
A usable demo could definitely help. My best guess would be that it's having trouble passing the video file to the system like a browser would, or that it doesn't support things that the web view expects like range requests.

You might try downloading the oceans.mp4 file from the videojs.com homepage, and put that in a plain video tag.
```
<video src="oceans.mp4" controls autoplay></video>
```

**Comment by gkatsev** [comment] 2015-11-17 19:44
I've recently used electron with videojs 5.0 and had no issues playing back mp4s locally or over the network.
We would need a reduced test case to be able to figure out what the issue is.
Closing for now but if we get more information and it is still a problem, we can reopen this issue.

**Closed by gkatsev** 2015-11-17 19:44 UTC
