### ISSUE TITLE
Text tracks added using MediaElement.addTextTrack are not proxied by Videojs on Firefox

### ISSUE THREAD

**Issue by svetlin-mladenov** [videojs/video.js#3038] opened 2016-01-26 11:19 UTC
Steps to reproduce: 

1. Setup a videojs instance on an html page
2. Dynamically add a text track to the wrapped native video element using [addTextTrack](https://www.w3.org/TR/html5/embedded-content-0.html#dom-media-addtexttrack)
3. Wait for the `addtrack` and related callbacks to be executed by the browser
4. Get the list of text tracks returned by `videojs(...).textTracks()`

Expected:
The newly added text track should be present in the list of text tracks returned by the corresponding videojs wrapping function namely `textTracks()`

Actual:
The list return by `videojs(...).textTracks()` does not contain the newly added text track

Here is a [test case](http://jsbin.com/kukudayifo/edit?html,output)

The issue is present with Firefox 43,44; Linux/Window; videojs 4/5.
It is not present with Chrome or IE 11 (other browsers or platforms not tested).

A workaround is to use `videojs(..).addTextTrack()` but I am trying to make my code player agnostic - work only with the native media element and use videojs to provide beautiful ui controls.

**Comment by hartman** [comment] 2016-01-26 14:06
I can confirm that it fails on FF, and I can also state that the test case is successful on Safari 9.

**Comment by gkatsev** [comment] 2016-01-26 16:43
Yep, sounds like a bug we should fix. This may be related to the fact that we're running firefox in emulated text-track mode for various reasons. We have a story to look into whether we can remove that ( #1862 ).
Also, while this specific usecase should definitely be fixed, we probably don't recommend trying to interact with the video element directly because it's possibly that it will get out of sync with how the videojs player thinks the video element is and could get into a bad state.

**Comment by gkatsev** [comment] 2016-07-25 23:57
I believe this is a bug in Firefox itself where it doesn't trigger an `addtrack` event. Nothing we can do but wait for it to be fixed (it's happening, hopefully, fixed in firefox 50).
Closing this in the meantime.

**Closed by gkatsev** 2016-07-25 23:57 UTC
Labels: bug, confirmed, unclaimed
