### ISSUE TITLE
video.js 5.0.0 does NOT work with videojs-contrib-dash 1.1.0 and dash.js 1.5.0

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#2670] opened 2015-10-03 13:25 UTC
video.js 5.0.0 does NOT work with videojs-contrib-dash 1.1.0 and dash.js 1.5.0.

Any update on when this might be fixed please.

Thanks

Richard

**Comment by chemoish** [comment] 2015-10-07 01:16
Maybe close in favor of the other one you have open?

**Comment by gkatsev** [comment] 2015-10-19 15:55
Closing as a dupe of https://github.com/videojs/videojs-contrib-dash/issues/23

**Closed by gkatsev** 2015-10-19 15:55 UTC
