### ISSUE TITLE
Videos larger than 2mb giving error in chrome

### ISSUE THREAD

**Issue by SampathPalla** [videojs/video.js#3441] opened 2016-07-19 18:46 UTC
## Description
Videos larger than 2mb are not being played in chrome (Version 51.0.2704.103 m). The same video is playing fine in FireFox and Internet Explorer. Getting this exception in the console: Uncaught (in promise) DOMException: The element has no supported sources.

### Expected
The video should play normally

### Actual
The video not playing and the player shows buffering icon.

### Error output
Uncaught (in promise) DOMException: The element has no supported sources.

## Additional Information
Including the following:
#### videojs
Latest
#### browsers
Chrome
#### OSes
Windows 7.1 Pro
### plugins
Just video.js

**Comment by gkatsev** [comment] 2016-07-19 19:04
Can you provide more information on the type of source you're using and what version of videojs you're using? Would be best if you could provide a [reduced test case](https://css-tricks.com/reduced-test-cases/) as that would be easiest for us to reproduce the issue.
However, as an example, videojs.com uses the `oceans` video which comes in at 11mb and plays just fine for me in chrome.

**Comment by SampathPalla** [comment] 2016-07-19 19:17
Thanks for the response! I am using videojs version 4.10.2. And the issue arises only for some files. Attached the media info of the type of files which are not being played for your reference. Will create the reduced test case if you still think it necessary. 
![media info](https://cloud.githubusercontent.com/assets/10891117/16963320/e4509028-4dc3-11e6-85e9-e227f8c893b6.png)

**Comment by gkatsev** [comment] 2016-07-19 19:24
Are the videos served the same way? I know we've had issues where the videos were served in a way that chrome didn't like (for example, servers that didn't allow byte-range requests).
Another thing to look into is the location of the metadata inside of the file itself. Some mp4s have the metadata like duration and video size at the end of the file so the browser needs to download the entire file before it can play back anything.
If those don't help, a reduced test case may reveal something else.

**Comment by mmcc** [comment] 2016-07-19 20:01
I have a sneaking suspicion that when you check the files that work they're going to be level Baseline or Main. High@4.1 is pretty advanced, so you're going to have spotty issues with device support on that one.

**Comment by SampathPalla** [comment] 2016-07-19 20:06
Yes. The videos that are playing are Baseline. That is what I thought too. That is the reason I provided the media info screenshot. Wanted to get a confirmation from you guys before I start converting the video files. Do you have a better work around for this instead of converting the files? Thanks in advance.

**Comment by mmcc** [comment] 2016-07-19 22:28
No, unfortunately I think transcoding the file is probably your best bet. If you have a bunch (or continuously updating) you might want to consider a cloud service like [Zencoder](http://zencoder.com), but for just a few the default settings for web in [Handbrake](http://handbrake.fr) should set you straight.

I'm closing this since it sounds like we're sorted out, but feel free to ping the comments if you have other questions.

**Closed by mmcc** 2016-07-19 22:28 UTC
Labels: needs: more info, needs: reduced test case

**Comment by SampathPalla** [comment] 2016-07-20 14:13
Thanks! I do have a lot of videos to convert. Although do you have any idea why are the videos smaller than 2mb of same format playing on chrome?
