### ISSUE TITLE
mute does not work for rtmp

### ISSUE THREAD

**Issue by anvaruk** [videojs/video.js#1965] opened 2015-03-21 12:49 UTC
e.g. mute doesn't work in the following example:

```
<video id="example_video_1" class="video-js vjs-default-skin"
  muted controls width="356" height="200"
  poster="http://mydomain.com/test.jpg"
  data-setup="{}">
<source src="rtmp://mydomain.com:1935/2-b99b-a2c6437dfa13_2" type="rtmp/mp4">
```
but If I use mp4 link it works

**Comment by gkatsev** [comment] 2015-03-21 16:04
A duplicate of #1780.

**Closed by gkatsev** 2015-03-21 16:04 UTC

**Comment by anvaruk** [comment] 2015-03-21 18:51
unfortunately the solution is out of my knowledge of this stuff
so I will have to stick with some other player which work but has the logo across the screen...
