### ISSUE TITLE
Grunt dev > jshint > Fatal error: watch null UNKNOWN

### ISSUE THREAD

**Issue by edwinbradford** [videojs/video.js#3395] opened 2016-06-26 17:02 UTC
## Description
Running 'grunt dev' in a cmd window on a Windows PC generates a fatal error message. I'm not sure if this is a known issue or if it is serious or trivial.

## Steps to reproduce
1. Navigate to the project directory in a cmd window.
2. Type "grunt dev" (without the quotes).

## Results
A message: "Waiting...Fatal error: watch null UNKNOWN" is returned.

### Expected
No error messages.

### Error output
```
Running "connect:dev" (connect) task
Started connect web server on http://0.0.0.0:9999

Running "concurrent:watchSandbox" (concurrent) task
Running "watch" task
Running "browserify:watch" (browserify) task
Waiting...Fatal error: watch null UNKNOWN


Execution Time (2016-06-26 16:44:02 UTC)
loading tasks  23s  █████████████████████████████████████████████████████████████████████████████████████████████████ 95%
Total 24.1s

    Warning:  Use --force to continue.

    Aborted due to warnings.


Execution Time (2016-06-26 16:42:24 UTC)
loading tasks            30.4s  ███████████████████████ 25%
jshint:src                  9s  ███████ 7%
browserify:build         16.2s  █████████████ 13%
uglify:build             24.4s  ███████████████████ 20%
concurrent:watchSandbox  37.6s  ████████████████████████████ 31%
Total 2m 2.2s


H:\videojsneue>
```

## Additional Information
I'm unsure whether 'grunt dev' finished building the files or not. 'grunt dist' has no problems and finishes without error messages.

#### videojs
5.9.2

#### browsers
Chrome

#### OSes
Windows 10 64 bit

### plugins
None

**Comment by edwinbradford** [comment] 2016-07-14 11:03
The Fatal error occurs at line 164:

```javascript
      jshint: {
        files: ['src/**/*', 'test/unit/**/*.js', 'Gruntfile.js'],
        tasks: 'jshint'
      }
```

Removing `'src/**/*', ` removes the error. This is happening on a vanilla install. Changing `'src/**/*', ` to for example `'src/js/*.js', ` also removes the error. It seems as though one or more Javascript files in the src directory are causing jshint to show a fatal error.

**Comment by gkatsev** [comment] 2016-07-25 18:55
That's really weird. Not sure what's happening there.
Does it work correctly if you do `grunt jshint` itself? Or does it only break when you run `grunt dev`?

**Comment by edwinbradford** [comment] 2016-07-26 11:43
I just tried it, `grunt jshint` works without any issues. `grunt dist` also works fine without errors. The only thing I can think of in case it's relevant is I'm not working behind a local server like XAMPP so localhost is meaningless. I'm loading files from the sandbox directory directly into a browser. Don't know it that's relevant at all.

**Comment by gkatsev** [comment] 2016-07-26 16:35
Huh, that's super weird that `grunt jshint` would work but not `grunt dev`.

**Comment by gkatsev** [comment] 2016-07-26 16:36
Wait a minute. Just re-read your original post, I guess I skimmed it too quickly. Seems like the issue is with the `browserify:watch` task.

**Comment by gkatsev** [comment] 2016-08-15 20:47
The build process is changing in #3445. I'll test that out on windows as well to make sure it works. Going to close this for now.

**Closed by gkatsev** 2016-08-15 20:47 UTC
