### ISSUE TITLE
Resolving URL before playback

### ISSUE THREAD

**Issue by heinbez** [videojs/video.js#2975] opened 2016-01-07 00:01 UTC
Hi fellas,

Thought I'd ask you guys for some help. I'm looking to resolve the real video path once the user clicks play. 

- User Clicks Play
- Play event Triggered
- Resolve Amazon Temporary Url 
- Modify Player's `src`
- Start playback

I was thinking along the lines of:

		player.on('play', function(e) {
			e.preventDefault();
			$url = resolveUrlFunction():
			player.src({
				type: 'rtmp/mp4',
				src: $url;
			});
			player.play();
		});

But obviously as you could imagine I'm setting myself up for an infinite loop here, but it still doesn't work in the first place.

Thanks!

**Comment by mister-ben** [comment] 2016-01-07 17:24
You can use `one()` instead of `on()` to catch only the first play event.

**Comment by heinbez** [comment] 2016-01-07 20:50
Thanks Ben! I'll try it out soon.

**Comment by mister-ben** [comment] 2016-01-08 16:22
If resolving the URL takes any time you might want to consider the effect of the delay on the user experience. Perhaps consider setting the URL on the player ready event.

Closing as it's not a bug/issue, but you can continue to reply to the thread.

**Closed by mister-ben** 2016-01-08 16:22 UTC
