### ISSUE TITLE
MP4 video is shrunk from native size in Opera

### ISSUE THREAD

**Issue by jone1joh** [videojs/video.js#4891] opened 2018-01-20 01:38 UTC
## Description

MP4 video is shrunk from native size in Opera; this is not the case with other browsers.  Very simple test case is attached.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Unzip the attached zip file to a "location" on a web site
2. Click on http://location/Video_Js_Test.html

### Expected
Please describe what you expected to see.

I expect the mp4 file to fill the player space as it does on other browsers.
### Actual
Please describe what actually happened.

Instead the mp4 file is shrunk by about 20 pixels and vertically centered in the player
### Error output
If there are any errors at all, please include them here.

None
## Additional Information
Please include any additional information necessary here. Including the following:

N/A
#### videojs
what version of videojs does this occur with?

All I think
#### browsers

Opera

Version: | 50.0.2762.58 (PGO) - Opera is up to date
-- | --
Stable
Windows 7 64-bit (WoW64)

#### OSes
Windows; only one at my disposal
### plugins
are any videojs plugins being used on the page? If so, please list them below.

No

[video-js.zip](https://github.com/videojs/video.js/files/1648398/video-js.zip)

**Comment by gkatsev** [comment] 2018-01-22 19:11
I've tried this on opera for mac and could not reproduce this. I've also tried this on browserstack (don't have access to a physical machine) and cannot reproduce there either.
What do you see as the value for `player.videoWidth()` and `player.videoHeight()` in your case?

also, as a workaround, I guess you should just either hardcode the size or use something like fluid mode with an aspect ratio of 420:576 or adding `vjs-fill` to make the player size to its container.

**Comment by jone1joh** [comment] 2018-01-22 21:30
[cid:image001.png@01D3938A.2F5CFEF0]

[cid:image002.png@01D3938A.2F5CFEF0]

[cid:image003.png@01D3938A.8378FA70]

Thanks for the reply Gary.  This is the latest Opera on Windows 7.  I’ve attached three screen shots to show what I see and from inspection it says the player container and the player are both 420x576 as is the mp4.  Yet in the player the mp4 isn’t filling the player (not seeing this on any other browser I’ve tested).

                var myVideo = document.getElementById('my_video_1');
                alert(myVideo.videoWidth);

Sometimes:
myVideo.videoWidth = 0
myVideo.videoHeight = 0

Othertimes after CNTR F5’s:
myVideo.videoWidth = 432
myVideo.videoHeight = 576

Always:
myVideo.width = 420
myVideo.height = 576

**Comment by gkatsev** [comment] 2018-01-22 21:41
Looks like your attachments got stripped via the email. The native resolution of the video is 420x576 and in all my trials the player resizes to the video size eventually.

**Comment by jone1joh** [comment] 2018-01-22 22:10
![video-js](https://user-images.githubusercontent.com/35616750/35246981-a464cd34-ffc0-11e7-9a0b-920769df9fd0.gif)

Above is what I mean by "shrunk".   Couldn't the width of 432 from myVideo.videoWidth cause this problem?

**Comment by gkatsev** [comment] 2018-01-22 22:21
Well, the width being slightly higher you should get pillarboxes and not letter boxes, you should get the letterbox is the player height is larger.
In the screenshot below I increased the width to 432 manually. Changing the height to 487 manually made my example look like yours.
![screen shot 2018-01-22 at 17 18 27](https://user-images.githubusercontent.com/535884/35247442-6ae9ae58-ff98-11e7-82c7-c3d690814173.png)

**Comment by jone1joh** [comment] 2018-01-24 02:45
To correct my issue with Opera I ended up adding the following to the test case I submitted earlier.  I think there is an issue with how the latest version of windows Opera handles css object-fit.

**added code:**
<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function() {
	document.getElementById('my_video_1').style.objectFit='unset';	
  });
</script>

**Comment by gkatsev** [comment] 2018-02-12 21:35
Yeah, I think we just have to chalk it up as a browser bug and hope it's fixed in the next release.

**Closed by gkatsev** 2018-02-12 21:35 UTC
