### ISSUE TITLE
DASH IF sample content not playing in VideoJS 7.0.3

### ISSUE THREAD

**Issue by edwinbradford** [videojs/video.js#5289] opened 2018-06-29 13:46 UTC
Sample DASH content from DASH IF is not playing in VideoJS version 7.0.3, it played fine in version 6.x with videojs-contrib-dash. I created a [JSFiddle](https://jsfiddle.net/edwinbradford/ywhu3gn9/) for you to verify this. If you take the video source link from that fiddle and try it in the official [DASH IF player](http://mediapm.edgesuite.net/dash/public/nightly/samples/dash-if-reference-player/index.html) it plays fine.

In VideoJS 7.0.3 the video doesn't load and the spinner goes round and round. The VideoJS docs say that version 7.0.3 has experimental dash support, I'm guessing it's not quite production ready yet. I'm running VideoJS in Chrome on Windows.

**Comment by forbesjo** [comment] 2018-06-29 14:33
Looks like videojs-http-streaming isn't generating the segment list correctly for your source, thank you for opening this issue!

**Comment by edwinbradford** [comment] 2018-06-29 14:51
Glad to be able to help on such a great project. The DASH IF Player I referred to in my issue has multiple working DASH files for testing in video players in case you didn't know but I'm sure you did.

**Comment by forbesjo** [comment] 2018-08-28 17:03
Added `confirmed` so stalebot doesn't close this. @gkatsev should stalebot ignore `bug` issues?

**Comment by majamee** [comment] 2019-02-17 00:55
@forbesjo Would you please be so nice to give any kind of update on this. I am not asking for any timelines, but I would be very interested what your rough plan (without timing) looks like in order to fully support DASH by VHS? There is virtually no information available about it, but the VideoJS blog's posts always read like DASH would be already fully supported since videojs v7 was introduced. So I really would appreciate any information on this.

**Comment by gkatsev** [comment] 2019-04-29 22:31
Hey, I have updates on this. The issue is that the stream used SIDX which we didn't support until recently, so, a SIDX video should now work, the downside is that the particular stream linked above still has some issues because it includes captions and we hadn't accounted for it, so, it's trying to do some things that break. However, when I updated the MPD to remove the captions support, that stream worked.

**Comment by gkatsev** [comment] 2019-04-30 21:40
Have a fix https://github.com/videojs/mpd-parser/pull/73 for the final problem

**Closed** 2019-05-01 17:29 UTC
Labels: bug, confirmed, playback
