### ISSUE TITLE
If a 403 is encountered during retry for playlist.m3u8 then VideoJS spams retry requests

### ISSUE THREAD

**Issue by TheRealMattLear** [videojs/video.js#6911] opened 2020-10-26 05:43 UTC
## Description

If a 403 is encountered during a retry of playlist.m3u8 request then videojs spams the server with requests: See this video, taking note of the requests in the bottom left corner: https://www.loom.com/share/5ae81fed9ae7478bbc0d06409d463a26

### Expected

VideoJS should honor the retry time of (5 seconds?) 

### Actual

Continuous requests to playlist.m3u8 without any timeout.

### Error output
```
video.min.js:12 VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the final playlist.
```

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Tested in latest @7 version

#### browsers
Google Chrome

#### OSes
Windows

### plugins

No

**Comment by gkatsev** [comment] 2020-10-29 05:55
Is this a duplicate of #6910?

**Closed** 2022-05-01 11:48 UTC
Labels: outdated
