### ISSUE TITLE
The volume bar could not hide after mutation was clicked.

### ISSUE THREAD

**Issue by DonkeyInBeijing** [videojs/video.js#3275] opened 2016-04-21 14:01 UTC
## Description
the volume bar could not hide after i click on the volume icon to mute the voice.
I must blur to somewhere else but the video container to make volume bar be hidden.

**Comment by gkatsev** [comment] 2016-04-21 15:40
Duplicate of https://github.com/videojs/video.js/issues/2918

**Closed by gkatsev** 2016-04-21 15:40 UTC
