### ISSUE TITLE
Live ui HLS stream crashes in chrome when running in the background

### ISSUE THREAD

**Issue by nathanjamal** [videojs/video.js#6085] opened 2019-07-03 09:30 UTC
## Description
Leaving the player running a live HLS stream (with liveUI enabled) in Chrome in a tab that is not the currently focused tab, causes the page to crash after about an hour. The javascript memory used in this time increases by over 400%. This doesn't seem to happen when the tab is focused.
This can be seen using the LiveUI sandbox test in the Video.js git repo.

## Steps to reproduce
1. clone the repository, and move into that directory
2. run npm install or npm ci to install all necessary packages
3. run npm start to start the local server
4. open http://localhost:9999/sandbox/liveui.html in Chrome
5. remove focus from that tab, either by minimising the window or opening another tab
6. after 1 hour open/focus the LiveUI tab

### Expected
Page is responsive and has continued playing

### Actual
Presented with Chrome's 'Page Unresponsive' modal. Unable to use the page.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.5.4
#### browsers
tested on:
Chrome 73.0.3683.103, 74.0.3729.131, 75.0.3770.100
#### OSes
Windows 10 on Surface Go and Lenovo IdeaPad U430 touch
### plugins
None
![2019-07-01 (1)](https://user-images.githubusercontent.com/199102/60580782-98b54480-9d7d-11e9-870b-9d49f646aa4a.png)

**Comment by gkatsev** [comment] 2019-07-08 19:21
Thanks! We are aware and it's likely related to #5937, we have time scheduled for addressing this, this quarter.

**Comment by matbcvo** [comment] 2020-01-02 01:04
Having same issue with video.js version 7.5.5 (latest)

**Comment by DispatchCommit** [comment] 2020-04-28 22:28
After looking into the issue, this is definitely a duplicate of https://github.com/videojs/video.js/issues/5937

PR https://github.com/videojs/video.js/pull/6621 will resolve this as well.

**Comment by DispatchCommit** [comment] 2020-07-10 04:05
@gkatsev the rAF fix for #5937 slated for the 7.9.0 should close this issue as well.

**Comment by gkatsev** [comment] 2020-07-10 16:39
Video.js 7.9.0 is out as a pre-release, closing as fixed.

**Closed by gkatsev** 2020-07-10 16:39 UTC
Labels: confirmed
