### ISSUE TITLE
Show error message if the video can't be played

### ISSUE THREAD

**Issue by moshwebs** [videojs/video.js#4455] opened 2017-06-28 16:34 UTC
Suppose that the video is down for some reason, how to show an error message?
For example if I add the following source in my videojs, I get no error message and loading wheel keep showing forever like the video is being loaded
`    <source src="http://www.google.com/video.mp4" type="video/mp4">`

**Comment by mister-ben** [comment] 2017-06-29 12:33
With that particular source, an error message *is* shown by default: "The media could not be loaded, either because the server or network failed or because the format is not supported."

For more customisable error messaging including timeouts see the [videojs-errors](https://github.com/brightcove/videojs-errors) plugin.

**Comment by gkatsev** [comment] 2017-07-05 06:18
An error should definitely be showing up in a large number of cases. If it isn't working would you be able to provide a reduced test case with a video that can't be played but isn't showing an error?

I'm going to close this issue and we can re-open if we can see a reduced test case we can reproduce the issue with. Thanks.

**Closed by gkatsev** 2017-07-05 06:18 UTC
