### ISSUE TITLE
can't use on mobile phone

### ISSUE THREAD

**Issue by mqliutie** [videojs/video.js#2877] opened 2015-12-03 03:32 UTC
both Android and iOS

http://graduation.avosapps.com/video-only.html

**Comment by gkatsev** [comment] 2015-12-03 03:54
Can you please provide more information on the issue?

> What did you do? (steps to reproduce)  
> What happened? (actual results)  
> What should have happened? (expected results)  
> What version of Video.js, and any plugins used?  
> What browsers and platforms does this occur/not occur on?  
> Is there a link to an example online?  
> Can a reduced test case be created? (e.g. [a jsbin](http://jsbin.com/axedog/9999/edit) or [JSFiddle (if Flash is involved)](http://jsfiddle.net/heff/zzXfb/))

**Comment by mqliutie** [comment] 2015-12-03 04:26
I want to call camera to record video
I use videojs-record plugin and it used video.js
[there](http://graduation.avosapps.com/video-only.html) you can look result, both Android and iOS device can't call camera
I don't what happened 
video.js version is 5.2.1

**Comment by gkatsev** [comment] 2015-12-03 04:36
Hm... Sounds like the issue is that either the device doesn't support the APIs used by the plugin the plugin isn't displaying errors properly. I think you should open an issue against the plugin (I think this is it? https://github.com/collab-project/videojs-record/issues) to inquire about it.
I don't think that there need to be any changes made in videojs core. When you create an issue, feel free to link it here and if you have other questions feel free to ask. Meanwhile, I'll close this issue. Thanks.

**Closed by gkatsev** 2015-12-03 04:36 UTC
