### ISSUE TITLE
Video.js subtitle view defect

### ISSUE THREAD

**Issue by sercanl** [videojs/video.js#5224] opened 2018-06-01 12:01 UTC
I am using videojs with angular 5. When I pause the video with some caption and scroll to a further point in the video, the captions keep on showing the previous text. The defect gives no error messages, and it happens on Chrome, Firefox, IE11 and Edge. It doesn't happen on Safari. 

Please see example screenshot (GIF) here: https://giphy.com/gifs/3q1s1MyzMYsxpGB2lR 

I tried different versions of videojs (6.2, 6.3, 6.9 and 7.0). It was the same with all.

I create the track items in angular as stated below:

```
<ng-container *ngIf="captions">
        <track *ngFor="let track of captions" kind="captions" src="{{track.src}}" srclang="{{track.sprak_kode}}" label="{{track.label}}" />
</ng-container>
```
Sercan

**Comment by gkatsev** [comment] 2018-06-06 19:06
This is probably due to us [relying on `timeupdate` events from the tech](https://github.com/videojs/video.js/blob/master/src/js/tracks/text-track.js#L191) for displaying captions. Browsers don't necessarily trigger a `timeupdate` event after a seek, even though, they technically can and should based on the specification. Also, once playback restarts, the captions should go back to being updated.

A workaround for now is to call `player.textTrackDisplay.updateDisplay()` on seek. But we should probably look into having them update during seeks as well.

**Comment by sercanl** [comment] 2018-06-08 08:53
Hi gkatsev,

Thanks for your reply. Will this fix be included in next release?

**Comment by gkatsev** [comment] 2018-09-25 16:17
I am no longer able to reproduce this issue. Tested in a bunch of modern browsers and IE11 on win7. Going to close it for now. 
If this is still an issue, please provide a test case.

**Closed by gkatsev** 2018-09-25 16:17 UTC
Labels: confirmed, difficulty: easy, help wanted

**Comment by thienedits** [comment] 2019-02-01 22:38
@sercanl How are you getting the track element to be added to the video? I have this exact code and when i inspect the DOM, the track element is not present. It only seems to work if i have the player config of 
```
html5: {
    nativeTextTracks: true
  }
```
