### ISSUE TITLE
Plugin scope shared between multiple videos

### ISSUE THREAD

**Issue by Soviut** [videojs/video.js#2997] opened 2016-01-12 09:45 UTC
I've written several plugins for a client that were working fine with a single player on a page. However, I've noticed scoping issues once we needed more than one player on a page a once.

The HTML for the players looks like this:

```html
  <h2>Player</h2>

  <video id="video"
         class="video-js vjs-skin-custom vjs-big-play-centered"
         height="300"
         width="600"
         poster="test/poster.jpg"
         controls
  >
  </video>

  <h2>Secondary</h2>

  <video id="video-secondary"
         class="video-js vjs-skin-custom vjs-big-play-centered"
         height="300"
         width="600"
         poster="test/poster.jpg"
         controls
  >
  </video>
```
The javascript to initialize it (visor is the wrapper around videojs that marshals all the plugins):

```javascript
  <script>
    var player = visor('video');
    var player2 = visor('video-secondary');
  </script>
```

The plugin template starts with:

```javascript
  var myPlugin = function(options) {
    var settings = videojs.mergeOptions(defaults, options);
    var player   = this;
```

Throughout the plugin I make liberal reference to `player`, assuming it would maintain a reference to the player it was initialized on. However, it seems only the last player is working correctly, meaning it's stomping on the first player's reference somehow.

**Comment by gkatsev** [comment] 2016-01-12 16:58
The way plugins are implemented right now is super simplistic. They're just functions on the prototype of the player so the `this` value when called on a player is the player you called it on.
If you're writing a complicated plugin, you'll want to make sure that each time the plugin is called it doesn't override the same variable that stores the player property, so, it isn't shared between instanced of the plugin.
I would wonder if `visor` is doing something weird maybe? Does it work if you don't use it? I've used pretty complicated plugins videojs plugins and they do not have the issue (see contrib-ads for example).
Is `visor` public anywhere?

**Comment by Soviut** [comment] 2016-01-12 20:42
`visor` is a thin wrapper around videojs to initialize the player and all the plugins I've written for it. It looks like this:

```javascript
(function(window, videojs) {
  window.visor = function(target, options) {
    var defaults = {
      controls: true,
      plugins: {
         // configure all plugins
      }
    };

    // called when player is initialized
    var readyHandler = function() {
      console.log('player ready');
      // perform any changes that need need the ready state
    };

    var mergedOptions = extend(defaults, options);
    var player = videojs(target, mergedOptions, readyHandler);
    return player;
  };
})(window, window.videojs);
```

**Comment by gkatsev** [comment] 2016-01-12 20:48
Would you be able to put up a super reduced test case showcasing the problem? It doesn't seem like `visor` would be the issue.

**Comment by Soviut** [comment] 2016-01-16 22:10
I've been experimenting by completely removing my `visor` wrapper and loading the plugins manually during the ready callback, however, I'm still getting the same behaviour.

**Comment by mmcc** [comment] 2016-01-16 22:31
Can you put together a JSBin so I can take a look?

**Comment by Soviut** [comment] 2016-01-16 22:33
Unfortunately my client doesn't want this appearing publicly so I'll have to email it to you.

**Comment by mmcc** [comment] 2016-01-16 22:46
I understand your predicament, but I really don't like private support like that, namely because it ultimately only helps you. If someone else has the same issue and stumbles across this, they're just going to see a dead end where someone got in touch via email.

Surely you can put together a generalized example?

**Comment by Soviut** [comment] 2016-01-16 22:49
I understand, though I am using this space to document any attempts I've made with the assumption that I'll encounter this in the future, forgot I solved it and find my own answers.

I'll see if the example I sent to @gkatsev can be anonymized enough to be useful.

**Comment by mmcc** [comment] 2016-01-16 22:58
I put together an [example](http://jsbin.com/tufuhu/edit?html,js,console,output) showing that plugin scope isn't shared between players if you write it that way. Does that help?

**Comment by Soviut** [comment] 2016-01-16 23:03
The issue I'm experiencing is events cross talking between players as well as custom player commands always acting on the last player on the page.

For example, I've built an annotations plugin (using the yeoman plugin generator) which listens for the `timeupdate` event on the player. When I have two players, the first player's `timeupdate` events are causing annotations to appear in the 2nd player. Its like a reference is being replaced somewhere.

**Comment by mmcc** [comment] 2016-01-16 23:07
To reiterate, I totally understand where you're coming from! I've been in the contractor world myself, so I totally get the situation of not being able to share work, just remember that this isn't a support channel. To be totally clear, you're asking for one-on-one, unpaid help from us, so you can complete a project *you're* being paid for. Again, I get your situation, but that's simply unfair to us and the rest of the Video.js community, especially those of us that aren't working for a company that's paying us to support the project.

> When I have two players, the first player's timeupdate events are causing annotations to appear in the 2nd player.

Honestly this pretty explicitly indicates an implementation bug to me.

**Comment by Soviut** [comment] 2016-01-16 23:12
Yeah, I'm certainly not trying to get free support, just trying to get to the bottom of this to figure out if its implementation or something systemic. In either case I'd document it here as much as possible and probably write a PR if I could fix it.

Here's a sanitized example using the third party videojs-resolution-picker plugin:
http://videojs-plugin-scope-issue.s3-website-us-east-1.amazonaws.com/

To reproduce the issue:
- Start and then pause both videos, noting that both are SD resolution showing 480p placeholder footage
- Open the browser dev console
- Observe that `player1` and `player2` are separate players with different IDs and target elements
- type: `player1.currentResolution('HD');`
- Observe that player2 switches resolutions instead of player1

**Comment by mmcc** [comment] 2016-01-16 23:55
I understand you're not, honestly you're just the unfortunate one to hit me when I've been thinking about problems with OSS lately. :) I have full faith your intentions are good! Definitely not meaning to imply you're intentionally trying to be malicious or anything.

I updated the [example I gave](http://jsbin.com/tufuhu/edit?html,js,console,output) to fire on the `timeupdate` event. As you can see, it's firing for each player context individually. You can also call `player1.whoami()` or `player2.whoami()` and see that each one does reference the correct player ID for that instance.

So, unfortunately, this _seems_ like a bug in your resolution switcher plugin. I don't have time to dig into the source right now, but at a glance it looks like there are some variables defined at the module level (such as `currentResolution`) that might be leaking between instances and causing the trouble you're seeing. Have you opened an issue on that project to ask?

**Comment by Soviut** [comment] 2016-01-17 00:27
I'll contact the author of the resolution switcher plugin about this as well.

My plugins, on the other hand, follow the outline created by the yeoman plugin generator. The only thing any of them have at the module level is the defaults for the options, which get `videojs.mergeOptions(defaults, options)` into passed options. Everything else resides inside the plugin's main function.

I'm not sure if it matters but I've also got a `ready` check in case the plugin is initialized out of order.

```javascript
  annotations = function(options) {
    var settings = videojs.mergeOptions(defaults, options);
    var player = this;

    player.on('ready', function() {
      // initialize the whole plugin here
    }
  }
```

**Comment by mmcc** [comment] 2016-01-17 00:31
Do you have your annotation plugin online anywhere?

**Comment by Soviut** [comment] 2016-01-18 00:14
@mmcc The actual repo for this is private but here's a Gist of the annotations source https://gist.github.com/Soviut/92d135dd82262ec61a8a

**Comment by mmcc** [comment] 2016-01-18 02:35
I assume it's something that was missed when extracting it, but I get an error when I try to use the plugin. Mind getting it working on [JSBin](http://jsbin.com/axedog/latest/edit)? Or rather, not working in the sense of reproducing the issue.

Anyway, I'm going to close this issue because everything that I've seen is pointing to problems with implementation (although there are almost certainly things we could improve in terms of documentation). There's nothing "special" about the way we handle plugins, we [literally just add](https://github.com/videojs/video.js/blob/master/src/js/plugins.js) the plugin to the player's prototype. I'd still like to get to the bottom of your specific issue with the annotation plugin, and if it points to a VJS bug we can reopen at that point.

**Closed by mmcc** 2016-01-18 02:35 UTC
Labels: needs: discussion, needs: more info

**Comment by Soviut** [comment] 2016-01-18 03:00
I've updated my example page to include the annotations plugin: http://videojs-plugin-scope-issue.s3-website-us-east-1.amazonaws.com/

I've applied the annotations plugin to both players using plugin configs:

```javascript
var player2 = videojs('video-secondary', {
  plugins: {
    annotations: {
      annotations: [
        {start: 3, end: 6, top: '30%', left: '30%', width: '10%', height: '10%', text: 'first', url: 'http://www.somethingawful.com'},
        {start: 5, end: 10, top: '50%', left: '50%', width: '30%', height: '30%', text: 'second', url: 'http://www.twitter.com', imageUrl: 'http://lorempixel.com/400/200/sports/2/'}
      ]
    }

    // ...
  }
}, function() {
  // ready
});
```

To reproduce:
- Start player 1
- Observe no annotations showing on player 1, despite both players having the plugin initialized on them
- Observe annotations appearing on player 2, despite player 2 not being started

**Comment by mmcc** [comment] 2016-01-18 03:32
Ok so for the purpose of a reduced test case, let's get this down to the tiniest amount of code that still shows the problem. I assume `updateSrc` comes from the resolutions plugin, so that should all go. I started the work for you at this [JSBin](http://jsbin.com/sakuma/edit?html,js,console,output), and for the most part it should be functionally the same as your example but I'm still not getting any annotations. Let's start by getting that working.

**Comment by Soviut** [comment] 2016-01-18 04:40
Thanks for the JSBin example. Yes, `updateSrc()` was from the previous example I did to show off the issue with the resolution plugin.

I can see that the same behaviour is occurring with the annotations in the JSBin as in my local example. The annotations only show up on the 2nd player. So at least there's some consistency between our two test cases.

**Comment by gkatsev** [comment] 2016-01-18 05:58
Looks like the issue is that there's a shared variable in your plugin. You have a line `annotations = []` in your plugin code which ends up being shared between instances because your plugin function's name is also `annotations`. The fix is to prepend `var` to that line. Here's a working example: http://jsbin.com/sinijadiqi/edit?js,output

**Comment by Soviut** [comment] 2016-01-18 06:25
You're right! I must have confused the earlier declaration for the plugin function name with a declaration for the data variable. I wouldn't be surprised if this is the case in my other plugins as well because the data variable is often similarly named to the plugin function (eg: "ads", "relatedVideos", etc.).

I'm going to look more closely as the resolution switcher since there's a good chance that's the problem there as well. If it's the case I'll pass that along to the plugin author.
