### ISSUE TITLE
Video sizing of width and height to "auto" creates very odd sizing behavior. Black bars.

### ISSUE THREAD

**Issue by surgevelocityllc** [videojs/video.js#2841] opened 2015-11-23 15:38 UTC
![screenshot_2015-11-23-10-34-18](https://cloud.githubusercontent.com/assets/11379976/11340959/64b226e4-91ce-11e5-92f6-6b487743c2d6.png)
With videojs 4 we had a few CSS class tweaks, but for the most part the video element scaled dynamically and maintained proper aspect ratios when using width and height "auto". However with 5.0 all videos are showing up like the attached file. Even Videojs homepage.

**Comment by Soviut** [comment] 2015-11-26 00:50
You'll need to supply more details. Is this only happening on Android? What element are you specifying weight and height on, the original video tag that videoJS wraps, or the container that does the wrapping?

**Comment by nightsurge** [comment] 2015-11-27 12:37
@Soviut It can be reproduced on the actual videojs homepage on Desktop using Chrome as well. As soon as the video element gets to about 630px wide or smaller, the black bars start to appear and grow larger.

On my own particular website, using videojs 4.12 I've always just set width and height to be "auto" and the video perfectly sized itself for the container it was put in, without any weird black bars. I'm really struggling to figure out how to get the new version 5 player to do the same.

<img width="851" alt="screen shot 2015-11-27 at 7 30 39 am" src="https://cloud.githubusercontent.com/assets/3065882/11441331/326da786-94d9-11e5-9f63-deac2d513d78.png">

**Comment by Soviut** [comment] 2015-11-27 19:22
You shouldn't be setting styles on the `<video>` tag. You should be setting them on the div above it with the `.video-js` class on it. Set it's `height: auto;` and it works fine.

![image](https://cloud.githubusercontent.com/assets/226882/11447334/4c30f1bc-9512-11e5-8083-5a6c047f697d.png)

**Comment by surgevelocityllc** [comment] 2015-11-27 19:36
Is this an undocumented change in version 5? The documentation always said
to apply your classes and styling to the video tag in the past.

http://docs.videojs.com/docs/guides/setup.html

I'll update my code and try this again. It seems like maybe the issue is
inaccurate or unclear documentation.

**Comment by Soviut** [comment] 2015-11-27 19:43
You can apply classes to the video tag before but not styles directly. So your styles should look like:
```css
.video-js {
    height: auto;
}
```
And not:
```css
video {
    height: auto;
}
```
This is because videojs will strip the classes you apply to the video tag and move them to the wrapping `div`. It then gives the `<video>` tag a class of `vjs-tech`. The same would happen to the flash fallback, a youtube embed, etc.

So make sure you always only style the classes within the videoJS hierarchy since things like the tech may not always be a `<video>` tag.

**Comment by nightsurge** [comment] 2015-11-29 06:54
Thank you, I guess this is just new behavior as mentioned in the blog post. Thanks for helping sort that out! However now on iOS (via the Chrome Dev Tools simulator) the videojs never seems to take affect. It stays at standard HTML5 interface. Android appears to be fine. Thoughts on this?

<img width="422" alt="screen shot 2015-11-29 at 1 52 57 am" src="https://cloud.githubusercontent.com/assets/3065882/11455755/0b045e7e-963c-11e5-9bbf-2e936a9766e5.png">
<img width="361" alt="screen shot 2015-11-29 at 1 53 29 am" src="https://cloud.githubusercontent.com/assets/3065882/11455756/0b04ad84-963c-11e5-9d3d-d85e63b1d8b9.png">

**Comment by Soviut** [comment] 2015-11-29 08:10
The chrome representation is misleading. On iOS proper it looks like this:

![image](https://cloud.githubusercontent.com/assets/226882/11456023/a0f7e75c-9646-11e5-881d-5101837c75de.png)

I'm not certain if videoJS is supposed to hide the controls on iOS or not. **This should really be in a new bug ticket since long conversations don't always get read.**

**Comment by nightsurge** [comment] 2015-11-30 16:55
Thank you, you may close this one!

**Closed** 2018-01-03 19:57 UTC
