### ISSUE TITLE
Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.

### ISSUE THREAD

**Issue by manjeetb** [videojs/video.js#3358] opened 2016-06-07 11:49 UTC
## Description
I am using HTML5 \<video> element to play videos using videojs library for controls. I am getting this  Intermittent issue while playing videos of any format on any browser. 

## Steps to reproduce
Click on play button, browser throws this error. 

### Error output
Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
    at TypeError (native)
    at Object.seekTo (http://localhost:9000/bower_components/wavesurfer.js/dist/wavesurfer.min.js:4:16115)
    at Object.seekTo (http://localhost:9000/bower_components/wavesurfer.js/dist/wavesurfer.min.js:4:3138)
    at updateNeedle (http://localhost:9000/scripts/controllers/dwf/logger.js:348:25)
    at http://localhost:9000/scripts/controllers/dwf/logger.js:301:7
    at Scope.$emit (http://localhost:9000/bower_components/angular/angular.js:12915:33)
    at Player.<anonymous> (http://localhost:9000/scripts/services/player.js:34:31)
    at HTMLDivElement.ret (http://localhost:9000/bower_components/video.js/dist/video.js:20997:15)
    at HTMLDivElement.data.dispatcher (http://localhost:9000/bower_components/video.js/dist/video.js:20645:29)
    at Object.trigger (http://localhost:9000/bower_components/video.js/dist/video.js:20749:25)

### versions
Ruby: 2.1.2
Rails: 4.2.0
#### videojs
Video.js 5.10.3 
#### browsers
Any. I am pasting google chrome's console log
![chrome-log](https://cloud.githubusercontent.com/assets/17235927/15854922/29c10a68-2cca-11e6-9826-6ef5c8e0f4fc.png)

#### OSes
Ubuntu-14.04, Windows 8.
### plugins
videojs.wavesurfer.js

**Comment by gkatsev** [comment] 2016-06-07 14:30
Can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)? It would make it a lot easier for us to reproduce the issue you are experiencing and thus fixing it.

**Comment by manjeetb** [comment] 2016-06-08 13:05
Hi, thanks for your response. I could not provide any code as organization policy issue. Tell me if I can provide anything else. Thanks.

**Comment by gkatsev** [comment] 2016-06-08 15:23
That error doesn't look like it's coming from videojs. I just tried setting the currentTime to Infinity and it fails with the same error but it doesn't actually throw a TypeError but rather just logs it to the console.
![](https://cldup.com/SmVp02ol9E.png)
I would hazard a guess that this is a problem with either wavesurferjs or the wavesurferjs videojs plugin.
However, without a reduced test case it's almost impossible for us to help you out more. I would recommend at least trying to unravel it yourself privately. Does it work with just plain old wavesurferjs without videojs?

**Comment by thijstriemstra** [comment] 2016-06-16 13:21
Looks like the same issue as https://github.com/katspaugh/wavesurfer.js/issues/745

**Comment by gkatsev** [comment] 2016-06-22 21:23
I think this is a issue that should be fixed in wavesurfer.js.

**Closed by gkatsev** 2016-06-22 21:23 UTC
Labels: needs: reduced test case

**Comment by codejq** [comment] 2020-03-31 20:10
For any one have the same issue this is happen when the code try to set any property like currentTime
volume ... multiple time and concurrent

**Comment by TigerTh** [comment] 2021-02-26 04:24
this.player.on('loadedmetadata', function() {
        //console.log('loadedmetadata-视频源数据加载完成')
        //设置上次播放时间lastLearnTime(秒)
        var duration = this.duration(); //视频时常
        var currentTime=0
        if(_this.videoSource.curProgress){
          currentTime = duration * _this.videoSource.curProgress / 100; //当前时间
        }
        this.currentTime(currentTime);
      })


I just encountered the same problem，It because the value of currentTime is NaN（as _this.videoSource.curProgress is undefine）,so maybe you should add some condition or restrictions
