### ISSUE TITLE
videojs is not a function

### ISSUE THREAD

**Issue by webDevRN** [videojs/video.js#2818] opened 2015-11-16 21:45 UTC
In order to fix video issues on the Android default browser I attempted to update video.js from 4.11.2 to 5.2.0. This error showed up on desktop and mobile debugging.

```
Uncaught TypeError: videojs is not a function
autoSetup @ setup.js:68
```

Thank you

**Comment by gkatsev** [comment] 2015-11-16 22:02
Duplicate of #2386. I'll reopen that one to track/investigate.

**Closed by gkatsev** 2015-11-16 22:02 UTC
