### ISSUE TITLE
Problem with time and timeline since update to 7.0.3

### ISSUE THREAD

**Issue by dilburt** [videojs/video.js#5214] opened 2018-05-28 01:55 UTC
I recently updated my system to use videojs version 7.0.3, videojs.ads version 6.3.0 and videojs.ima version 1.3.0. Everything appears to be working except for the time and timeline. The time reads -1:-1 and the timeline is always at the end (full). This has worked fine through versions 5 and 6 of videojs although I skipped the latest release of version 6 and went to 7 so I can't say if this would have happened in the latest version of 6.

I am getting 2 warnings that appear to be unrelated although I would appreciate any tips you may have regarding these as well:

1. VIDEOJS: WARN: Unexpected adsready event (Preroll)
2. VIDEOJS: WARN: Unexpected startLinearAdMode invocation (Preroll)

The Undexpected startLinerAdMode comes after adStart but I'm not calling startLinearAdMode anywhere in my code.

I don't see any errors in the log to indicate the timer problems even though I'm running verbosity: 5 and the ima3_debug version of the library so I have no idea what is going on. I definitely have the current versions of the CSS files according to what was installed by npm but I have a feeling this must be related to a CSS problem or some other content issue that is causing the time and timeline updates to fail. Seems like this would log though and I'm not seeing that.

Thanks,

D

**Comment by magikstm** [comment] 2018-05-28 02:16
With which browser(s) are you experiencing this issue? (OS, browser and browser version)

There are no notes for the latest releases of your plugins about them being compatible with video.js 7:
https://github.com/videojs/videojs-contrib-ads
https://github.com/googleads/videojs-ima

I would suggest trying video.js 6.10.1 first.

**Comment by dilburt** [comment] 2018-05-28 06:07
Thanks magikstm. I had started looking down the release versions for any mention of this and although I didn't find anything regarding time or timeline I decided to take your advice and look for the most recent set of versions with explicit cross-testing comments. As far as I can see this appears to be videojs 6.7.3, videojs-ads version 6.2.1 and videojs.ima version 1.2.0.

However, with these versions I still have the same issue with time showing -1:-1 and the timeline showing end of video. Anyone seen this?

**Comment by ldayananda** [comment] 2018-05-30 22:37
Sorry for the late response @magikstm, one thing to note is that there are a few compatibility issues with contrib-ads and videojs-ima which you can follow [here](https://github.com/googleads/videojs-ima/issues/539). The warnings you are getting indicate that an ad break is being started at a time when an ad should not play(which is likely why you are seeing invalid times in the control bar). I suggest you open an issue against videojs-ima with a JSbin or something similar so it's easier to track down the incompatibility.

**Comment by ldayananda** [comment] 2018-05-30 22:38
As this isn't caused by videojs, I'll close this issue but feel free to open a new issue if you do find that videojs v7 is introducing a problem.

**Closed by ldayananda** 2018-05-30 22:38 UTC

**Comment by dilburt** [comment] 2018-05-30 23:11
Hi ldayananda,

This was my issue, @magikstm was helping me. Thanks for the info and link, I'm checking that now. I opened an issue with videojs.ima on Monday and they are looking into it.

Thanks,

D

**Comment by ldayananda** [comment] 2018-05-31 15:01
Ah yes, sorry for the mix up. I hope you're able to find the issue!

**Comment by dilburt** [comment] 2018-06-01 02:03
Yes, @shawnbuso pointed out that the new version of videojs.ima makes the call to ima.requestAds() internally now so removing this call from my code solved the problem.
