### ISSUE TITLE
have a question about progress bar

### ISSUE THREAD

**Issue by qimingWei** [videojs/video.js#3947] opened 2017-01-15 09:36 UTC
i use video.js 5.11.8
i find a bug, when i click progress bar to Fast forward to somewhere and i click progress bar back to other somewhere. After i click back off the progress bar will be return to the first i Fast forward point.
how can i Change it to normal ?

https://cloud.githubusercontent.com/assets/25046571/21961434/83e01588-db44-11e6-98ed-06068af17c13.gif

**Comment by gkatsev** [comment] 2017-01-15 16:29
Dupe of https://github.com/videojs/video.js/issues/3839. Fixes in 5.16.0 (and partially in 5.15.1).

**Closed by gkatsev** 2017-01-15 16:29 UTC
