### ISSUE TITLE
Video tag that uses the src attribute instead of <source> tags won't play on click

### ISSUE THREAD

**Issue by DoomTay** [videojs/video.js#5257] opened 2018-06-16 04:48 UTC
## Description
Video tag that uses the src attribute instead of <source> tags won't play on click. I click on the play button and nothing happens

http://jsfiddle.net/henkvgr8/1/

### Expected
Both videos should play

### Actual
The top one works, the bottom one won't.

### Error output
N/A.

#### videojs
7.0.5, though further testing has shown that this issue goes as far back as 6.0.0
#### browsers
Firefox 60.0.2
#### OSes
Windows 10
### plugins
None

**Comment by BrandonOCasey** [comment] 2018-06-18 15:59
I am able to reproduce this on chrome. It does seem like the tech is loading the source and that everything is copied over. Calling play manually on the second video element starts playing the video. The problem is that the player does not  know that we have a source and won't call play when clicking the big play button because it thinks that we have no source.

**Comment by gkatsev** [comment] 2018-06-18 16:13
I'm going to close this as a duplicate of #4851. That issue's topic is different but the root cause is the same. There's also a bunch of discussion there related to it.
#4469 which was recently merged in improves this behavior by figuring out the type for various video formats but there's some more work to be done for this.

**Closed by gkatsev** 2018-06-18 16:13 UTC
Labels: bug
