### ISSUE TITLE
Progress control UI is not updating correctly on seek of paused video

### ISSUE THREAD

**Issue by onerzafer** [videojs/video.js#6370] opened 2019-12-23 15:35 UTC
## Description
Progress control is not updating as expected when the video is paused and the user would like to seek a point in time by clicking the progress bar.
[reduced test case](https://codesandbox.io/s/gracious-spence-xv0si?fontsize=14&hidenavigation=1&theme=dark)

## Steps to reproduce
1. Open the reduced test case
2. play the video
3. pause the video
4. wait until video fully loaded
5. click to the progress bar to seek the video for a different time
6. observe the progress bar and progress bar handle is not moving to the clicked point.
7. play the video and observe the UI update correctly and video actually play from where the user clicks

### Expected
Regardless of the video is paused or not the user should be able to see an update from the UI.

### Actual
On a paused video clicking the progress bar correctly updates the vide but not the progress bar.

### Error output
There is no js error only UI is behaving oddly.

#### videojs
video.js 7.7.1
#### browsers
Tested on Chrome
#### OSes
Tested on Mac Catalina 10.15.1
### plugins
no plugins used

**Comment by gkatsev** [comment] 2019-12-23 16:48
Thanks, it's something that we got an issue for previously but accidentally got closed #6232. They also opened a PR but the fix is a bit trickier than expected #6234.

**Comment by gkatsev** [comment] 2019-12-23 17:56
Going to close this as a duplicate of those two. Thanks for writing up a detailed report.

**Closed by gkatsev** 2019-12-23 17:56 UTC
