### ISSUE TITLE
IE11 debugger mode to IE8 Error: Member not found at Line 8650

### ISSUE THREAD

**Issue by mehulchauhan** [videojs/video.js#2123] opened 2015-05-05 16:05 UTC
Hi, 

I tested video.js in native IE8 and it works perfectly fine but in IE11 when I change mode to IE8 using debugger I get following errors:
At Line 8650:  list[prop] = vjs.TextTrackList.prototype[prop]; Member not found.

Can you please help me to resolve errors for IE8 debugger mode.
![error-videojs](https://cloud.githubusercontent.com/assets/2623132/7476965/958e689e-f36e-11e4-951a-89d4af03e81b.jpg)

**Comment by EZWrighter** [comment] 2015-05-05 16:29
I can confirm this as I saw the same behavior, but I assumed an IE11 bug as it did work as expected in IE8.

**Comment by gkatsev** [comment] 2015-05-05 18:00
Is there a reason why you're using the IE8-mode in IE11? Generally, those types of modes add a lot of extra bugs that work fine if you use the actual browser itself and is low on our priority list.

**Comment by mehulchauhan** [comment] 2015-05-05 18:04
Actually I do agree with your point, but as per my client requirements I need to support this, is there anyway I can use IE8 mode without errors as this stop other my js too to get executed

**Comment by javidjamae** [comment] 2015-07-23 18:08
I can confirm that I see this same issue with IE10 running in IE8 browser mode. Unfortunately, I'm finding it difficult to find a Windows box with IE8 in order to verify on an actual IE8 browser.

**Comment by javidjamae** [comment] 2015-07-23 21:14
FYI - I just installed and tested IE8 on Windows 7 using the modern.ie virtualbox image and I do not see this issue on IE8 there.

**Comment by mmcc** [comment] 2015-07-23 23:02
@javidjamae excellent, thanks for checking. I'm going to close this since this seems to be a "IE compatibility-mode" issue.

**Closed by mmcc** 2015-07-23 23:02 UTC
Labels: browser bug, bug, needs: confirmation

**Comment by javidjamae** [comment] 2015-07-24 22:57
@mmcc - no worries, however I would recommend leaving this issue open and trying to fix it. The compatibility mode is not just there for developer testing purposes. If a site defines the following meta tag, then an IE10 or IE11 browser will automatically switch in to the IE8 compatibility mode (just as if you went in to developer mode and did it manually):

```
<meta http-equiv="X-UA-Compatible" content="IE=8"> 
```

This is a problem for 3rd-party products that use videojs and are embedded on sites where they don't necessarily have control over the compatibility meta tag. Note that even if you're in an iframe, you can't override the parent page's compatibility mode, and it will impact the code video player in the iframe. We're currently seeing this with some large media sites that use our embedded video player products.

**Comment by mmcc** [comment] 2015-07-25 00:18
@javidjamae I totally see what you mean, but going down the IE compatibility mode rabbit hole is so far down our priority list right now that I think this issue would just languish forever. To be terribly honest, I lean towards not doing any additional work to support this use case on principal alone. 

I realize we're talking about something entirely out of our hands, but forcing IE8 compatibility mode on  visitors is so backwards that it borders on malicious. Heck, I'm personally in the camp that thinks we should drop IE8 support altogether in order to stop being enablers, but I'm definitely out numbered on that one. :)

I do think that we should just make a firm decision about what our policy is on this, though and stick with it. @videojs/core-committers? :+1: or :-1:

**Comment by pam** [comment] 2015-07-25 00:29
Yeah, when we dropped support for IE6/7 that included compatibility mode.
There's too much we would have to do then continue to test and maintain, to
put that on our regular contributors while trying to keep up with
everything else.  There was an issue around 6/7 support that had some
fixes, and we suggested making that a side project for people who needed it
and were willing to help.  You might check that out. I'd find it but I'm on
my phone. :)

-- 
Sent from mobile

**Comment by mmcc** [comment] 2015-07-25 00:33
O.o did @pam become sentient?!

**Comment by gkatsev** [comment] 2015-07-25 00:35
If someone were to fix it and submit a PR, we could accept it. However, maintaining it ourselves isn't realistic. Should we just support IE11 in IE8 mode? What about IE11 in IE9 or IE10 modes? What about IE9 or IE10 in any preceding browser modes?
Maintaining IE8 itself is hard enough as it is. While I would also like to drop IE8, there's enough users for us to keep it around, at least until January 2016 when Microsoft completely gets rid of IE8 support.

**Comment by javidjamae** [comment] 2015-07-25 04:25
@mmcc @gkatsev @pam - I totally understand, and that was what I expected your response to be, but I thought I'd ask anyways. :smiley: 

We're working with our partners to get them to stop using compatibility mode. Best case, they'll drop it and go to edge, worst case I'll be spending time writing a pull request.
