### ISSUE TITLE
Feature based IE8 detection

### ISSUE THREAD

**Issue by doublex** [videojs/video.js#1961] opened 2015-03-19 19:50 UTC
Maybe it would be worthwhile to update the IE8 detection:

````
vjs.IS_IE8 = (/MSIE\s8\.0/).test(vjs.USER_AGENT);
->
// http://tanalin.com/en/articles/ie-version-js/
vjs.IS_IE8 = (document.all && !document.addEventListener);
````

**Comment by mmcc** [comment] 2015-03-19 19:54
According to that site, wouldn't the check be this?

```javascript
document.all && document.querySelector && !document.addEventListener
```
This seems like a good idea to me, though.

**Comment by gkatsev** [comment] 2015-03-19 20:02
What? That's crazy, `document.all` exists in firefox and chrome but `!document.all` evaluates to true. ![](http://media.boingboing.net/wp-content/uploads/2012/12/Mind-Blown_thumb1.gif)

Also, while useragent switching isn't great, it's mostly ok for testing for old browsers.

**Comment by mmcc** [comment] 2015-03-19 20:20
That mind-blown gif is blowing my mind.

Yeah I was going to ask if we've seen actual issues caused by checking the user agent. I don't know why someone would want to fake an IE8 user agent, but I guess I've seen stranger things.

**Comment by doublex** [comment] 2015-03-19 20:30
"(document.all && !document.addEventListener)" is perfect to detect IE8 and below.
"document.all" was a Microsoft-specific and does not exist in other browsers. Even if it would exist, they all would support "document.addEventListener" -> the condition would be false.

**Comment by gkatsev** [comment] 2015-03-19 20:46
We don't want to detect IE8 and below. Only IE8.

**Comment by doublex** [comment] 2015-03-24 09:11
If you want IE8 only detect, then @mmcc would be the solution.
The problem: I want to create a "IE7 plugin" - and for that plugin I need "IE8 and below" detection.

**Comment by heff** [comment] 2015-03-24 17:19
If we're specifically not supporting IE6/7, then IE8 and <=IE8 are kind of the same.

**Comment by doublex** [comment] 2015-03-24 18:29
@heff 
For you yes - but you would give me the chance to write a "IE7 plugin" (some dummy-functions() and IE7 would work again).
Thanks!

**Comment by gkatsev** [comment] 2015-03-24 18:34
A variable called `IS_IE8` should only ever report true for `IE8`.
A plugin can do possibly do their own user agent detection or we could add `IS_IE8_AND_BELOW` var as well.

**Comment by heff** [comment] 2015-03-24 22:48
Yeah, I agree with that. If there's no specific reason why core needs the
less than IE8 check, then that should be in the plugin.

**Comment by mmcc** [comment] 2015-04-01 00:44
I'm going to close this because it seems like the conversation is leaning towards this belonging within the plugin itself. If I'm wrong, yell at me and / or reopen.

**Comment by gkatsev** [comment] 2015-04-01 00:48
Adding a strict `IS_IE8` might be useful, especially as we're moving away from IE8 baseline and into es5 baseline.

**Comment by mmcc** [comment] 2015-04-01 00:53
Ok, reopening until we decide, then.

**Comment by gkatsev** [comment] 2015-11-17 23:34
I'm going to close this. IE8 is now a fairly small browser, especially compared to what it used to be, especially since microsoft is discontinuing all support for older IEs on january 12, 2016.

**Closed by gkatsev** 2015-11-17 23:34 UTC
Labels: enhancement
