### ISSUE TITLE
"default" attribute for text tracks not work in IE

### ISSUE THREAD

**Issue by d4d4k** [videojs/video.js#2259] opened 2015-06-12 22:55 UTC
In 4.12.7 default text track feature is not available for IE. Subtitles (or captions) always off when the player is loaded. I tested it in IE 11.

**Comment by mmcc** [comment] 2015-06-15 01:36
Closing this as a duplicate of #1914. Mind pinging that thread with any additional info?

**Closed by mmcc** 2015-06-15 01:36 UTC
Labels: duplicate
