### ISSUE TITLE
`this.el_.vjs_getProperty('buffered'))` error when using flash tech in 5.0.0-rc.2

### ISSUE THREAD

**Issue by meleyal** [videojs/video.js#2261] opened 2015-06-15 14:14 UTC
This occurs in IE8, or any browser using `techOrder: ['flash', 'html5']`

**Comment by mmcc** [comment] 2015-06-16 00:33
Closing this as a duplicate of #2247, but feel free to add any input on that thread.

**Closed by mmcc** 2015-06-16 00:33 UTC
