### ISSUE TITLE
Video Full Screen keeps video original size

### ISSUE THREAD

**Issue by burnhamrobertp** [videojs/video.js#3655] opened 2016-09-29 14:50 UTC
Most videos seem to be fine but others, such as this one:

http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4

Do not engage in full screen and simply stays in its original size with the rest of the screen having a black background. Video controls are properly positioned, but the actual video doesn't increase in size.

**Comment by gkatsev** [comment] 2016-09-29 15:26
Seems to work fine for me. Can you put up a reduced test case showcasing the issue?

**Comment by bradjones1** [comment] 2016-11-22 18:38
I am running into this using a Big Buck Bunny trailer test video, though I'm playing it with the contrib HLS extension. I will try to put up a test example soon.

![screenshot from 2016-11-22 11-37-18](https://cloud.githubusercontent.com/assets/981966/20536874/1be6fa62-b0a8-11e6-89de-2d1b4fa6dba1.png)

**Comment by misteroneill** [comment] 2016-11-28 18:33
Those audio tracks errors are odd/suspicious. What version of video.js is that?

Also, is this browser or OS-specific?

**Comment by bradjones1** [comment] 2016-12-21 02:01
> Those audio tracks errors are odd/suspicious. What version of video.js is that?

Version 5.8.8, off the CDN. I'm also using v. 3.16.13 of the [HLS library](https://github.com/videojs/videojs-contrib-hls), if that might make a difference.

> Also, is this browser or OS-specific? Same results on both Firefox and Chromium on Linux, haven't tried another OS.

**Comment by misteroneill** [comment] 2016-12-22 14:45
@bradjones1 I put together a [reduced test case](http://output.jsbin.com/xogimu) and fullscreen seems fine in all browsers, but I'm on Mac OS X. It could be Linux-related.

The `audioTracks` error looks like a consequence of incompatible video.js and videojs-contrib-hls versions. videojs-contrib-hls v3.16.x expects video.js 5.10.1 or higher.

My example uses v5.10.8 and v3.16.14 and I don't see that error.

**Comment by bradjones1** [comment] 2016-12-22 17:09
@misteroneill Thanks... I missed the dependency issue since it's not in the README, just the `package.js`. I will try this combination and follow up. Appreciate the test.

Is the 4.x branch of HLS still unstable at this point?

**Comment by bradjones1** [comment] 2016-12-22 19:56
After testing with this a bit more, I think the culprit here was width/height CSS being applied to the video element itself, which when removed allowed the video to expand to fit the full screen.

For anyone else finding this via a Drupal integration, see [this issue](https://www.drupal.org/node/2838769).

**Comment by svandecappelle** [comment] 2017-01-06 16:45
This CSS could help you. 
It caused by the width / height into DOM attributes are the most important attributes. Forcing them into CSS to important has solved mine.

```
.video-js .vjs-tech {
  width: 100% !important;
  height: 100% !important;
}
```

**Comment by gkatsev** [comment] 2018-01-03 18:55
I think this has been fixed and answered, so, closing.

**Closed by gkatsev** 2018-01-03 18:55 UTC
