### ISSUE TITLE
[5.0] Triggering events after disposing player

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/video.js#2634] opened 2015-09-24 11:51 UTC
In our testsuite we dispose the player after every test automatically.

However, sometimes some events still trigger after disposing. For example the videojs-contrib-ads plugin triggers an adtimeout by default after the set timeout.

If this happens after the player is disposed, the `hasElemData` function throws an error, because `elem` is null.

Is it an idea to check for this in the `trigger` function and if `elem` is null, do nothing?

**Comment by heff** [comment] 2015-09-24 14:57
That definitely seems like a safety we could add into component.trigger. [Dispose does remove all event listeners](https://github.com/videojs/video.js/blob/f5b80c8ea99848bc3eaf8ea0dbc422cdbba112a2/src/js/component.js#L124) so it would be good if we could narrow in on exactly why the event is getting triggered after dispose.

**Comment by heff** [comment] 2015-09-24 14:57
If you think you could help make a PR for this, please do.

**Comment by gkatsev** [comment] 2015-09-24 15:01
We've previously not done that because often it's better the fix the root cause.

**Comment by nickygerritsen** [comment] 2015-09-24 15:01
Isn't it the case that, although event listeners are gone, `Event.trigger` still needs the element?

I.e. if I have a plugin that does:

```js
setTimeout(function() {
    player.trigger('test');
}, 5000);
```

Then this will currently give an error.

**Comment by gkatsev** [comment] 2015-09-24 17:06
I think so. Not saying we shouldn't necessarily fix it. But previously we hadn't because it generally revealed an actual problem that should've been fixed in the first place.

**Comment by heff** [comment] 2015-09-24 18:18
Other options would be to give plugins a specific way to check if the player is disposed, or allow plugins to have a dispose() method that the player calls when it's disposed. The latter would be a bit complicated.

Actually, if something needs a `setTimeout` or `setInterval` it should use `player.setTimeout` or `player.setInterval`. Those get cleared when the player is disposed.

Finally we could throw a warning instead of an error if an event is triggered after the player is disposed.

**Comment by gkatsev** [comment] 2015-09-24 18:34
a warning instead might be good.

Also, adding a dispose to plugins is one of the things I want to add to plugins in the future. Making plugins more robust out of the box so each plugin doesn't need to implement everything from scratch itself.

**Comment by nickygerritsen** [comment] 2015-09-25 06:48
I think dispose in each plugin makes sense, but I also like @heff 's idea with `player.setTimeout`, again because then each plugin does not have to reimplement it.

**Comment by gkatsev** [comment] 2018-01-03 20:01
I think we've more or less cleared all these issues.

**Closed by gkatsev** 2018-01-03 20:01 UTC
Labels: confirmed, enhancement
