### ISSUE TITLE
"muted" option not working for Flash

### ISSUE THREAD

**Issue by wfayeBerman** [videojs/video.js#1801] opened 2015-01-14 15:15 UTC
When setting the "muted" option to "true" the volume is audible in Flash.  I've searched past issues and see that this has been a problem over the years and am wondering if this might be addressed in a new release.

**Comment by gkatsev** [comment] 2015-01-14 16:23
Dupe of #1780. We're aware of the issue now, but have a lot of large projects finishing up that we need to push through. Please continue discussion over in that issue. 
Thanks!

**Closed by gkatsev** 2015-01-14 16:23 UTC
