### ISSUE TITLE
VideoJS 7 fails to return the native play promise

### ISSUE THREAD

**Issue by KevinBrogan** [videojs/video.js#5218] opened 2018-05-29 00:22 UTC
## Description
VideoJS 7 fails to return the native play promise.

## Steps to reproduce
```html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Video Player</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.0.3/video-js.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.0.3/video.min.js"></script>
<style>
.video-js
{
	width: 320px;
	height: 180px;
}
</style>
</head>
<body>
<video controls id="vid" class="video-js">
	<source src="//mirrors.standaloneinstaller.com/video-sample/dolbycanyon.mp4">
</video>
<script>
	videojs(vid,{},function(){console.log(this.play())});
</script>
</body>
</html>
```
### Expected
console will log the play() promise on both success and failure, on platforms that natively return it

### Actual
console logs undefined

#### videojs
7
#### browsers
all, tested on chrome
#### OSes
all
### plugins
none

**Comment by mister-ben** [comment] 2018-06-01 11:09
The problem is calling `play()` between `ready` and `loadstart`. In this case, that `play()` returns nothing and play is attempted again on `loadstart`.

https://github.com/videojs/video.js/blob/v7.0.3/src/js/player.js#L1906

**Comment by gkatsev** [comment] 2018-06-20 20:05
Actually, going to close this specific issue in favor of videojs/video.js#3927

**Closed** 2018-06-20 20:05 UTC
