### ISSUE TITLE
TypeError: d is null

### ISSUE THREAD

**Issue by karneaud** [videojs/video.js#1783] opened 2015-01-06 11:32 UTC
Got this error running on FireFox 34 for Windows 7 

    TypeError: d is null
    http://cdnjs.cloudflare.com/ajax/libs/video.js/4.11.3/video.js
    Line 111

Trying to debug it but no luck

**Comment by heff** [comment] 2015-01-07 00:52
Thanks for reporting it. Any more info on what's required to reproduce the error? I'm not seeing it in FF34 on this demo page.
http://jsbin.com/axedog/

**Comment by heff** [comment] 2015-01-07 20:49
Can you see the same error or not in that jsbin example? And if not, can you point to any differences in what you're doing with the player?

**Comment by Runtheball** [comment] 2015-01-28 17:09
I'm seeing similar error in FF 35.0.1 on a mac. Works fine in Chrome.
"VIDEOJS:" TypeError: d is null
Stack trace:
t.p.$b/a.prototype.Ja@http://vjs.zencdn.net/4.11/video.js:111:336
T@http://vjs.zencdn.net/4.11/video.js:65:453
s.src/<@http://vjs.zencdn.net/4.11/video.js:74:313
s.Na@http://vjs.zencdn.net/4.11/video.js:36:189
Q/<@http://vjs.zencdn.net/4.11/video.js:63:307
s.Na@http://vjs.zencdn.net/4.11/video.js:36:189
t.f.checkReady@http://vjs.zencdn.net/4.11/video.js:129:420
t.f.onReady@http://vjs.zencdn.net/4.11/video.js:129:342
@http://dev.mopdog.com/:0:22

**Comment by wpinsite** [comment] 2015-02-01 02:42
I am seeing the exact same issues in Firefox as well. No issues in Chrome

**Comment by p-j** [comment] 2015-02-02 08:54
Same problem here, Chrome works well, but Firefox don't.

On the unminified version, the error is 

```
"VIDEOJS:" TypeError: sh is null                             video.dev.js:1409:4
Stack trace:
vjs.MediaTechController.withSourceHandlers/Tech.prototype.setSource@http://localhost:3000/bower_components/video.js/dist/video-js/video.dev.js:6715:5
vjs.Player.prototype.techCall@http://localhost:3000/bower_components/video.js/dist/video-js/video.dev.js:4209:7
vjs.Player.prototype.src/<@http://localhost:3000/bower_components/video.js/dist/video-js/video.dev.js:4775:11
vjs.Component.prototype.triggerReady@http://localhost:3000/bower_components/video.js/dist/video-js/video.dev.js:2483:7
vjs.Player.prototype.loadTech/techReady@http://localhost:3000/bower_components/video.js/dist/video-js/video.dev.js:3933:5
vjs.Component.prototype.triggerReady@http://localhost:3000/bower_components/video.js/dist/video-js/video.dev.js:2483:7
vjs.Flash.checkReady@http://localhost:3000/bower_components/video.js/dist/video-js/video.dev.js:7525:5
vjs.Flash.onReady@http://localhost:3000/bower_components/video.js/dist/video-js/video.dev.js:7510:5
@http://localhost:3000/#:0:22
```

And at line 6700 and followings

```js
  /**
   * Create a function for setting the source using a source object
   * and source handlers.
   * Should never be called unless a source handler was found.
   * @param {Object} source  A source object with src and type keys
   * @return {vjs.MediaTechController} self
   */
  Tech.prototype.setSource = function(source){
    var sh = Tech.selectSourceHandler(source); // Here sh is null

    // Dispose any existing source handler
    this.disposeSourceHandler();
    this.off('dispose', this.disposeSourceHandler);

    this.currentSource_ = source;
    this.sourceHandler_ = sh.handleSource(source, this);
    this.on('dispose', this.disposeSourceHandler);

    return this;
  };
```

**Comment by p-j** [comment] 2015-02-02 10:43
Ok, so after further investigation, I fill I need to better explain the context : 
I'm runngin Firefox Developer Edition on Ubuntu 14.04.1. 
I have flash installed and can display Flash animation on [Flash player help](http://helpx.adobe.com/flash-player.html), I also tried with pipelight to get a more up-to-date version of flash player on Firefox, but no luck.

The `sh` above origininate from `selectSourceHandler` that I copy paste below

When I head to video.dev.js@6663

```
  /**
   * Return the first source handler that supports the source
   * TODO: Answer question: should 'probably' be prioritized over 'maybe'
   * @param  {Object} source The source object
   * @returns {Object}       The first source handler that supports the source
   * @returns {null}         Null if no source handler is found
   */
  Tech.selectSourceHandler = function(source){
    var handlers = Tech.sourceHandlers || [],
        can;

    for (var i = 0; i < handlers.length; i++) {
      can = handlers[i].canHandleSource(source);

      if (can) {
        return handlers[i];
      }
    }

    return null;
  };
```

handlers contains only Flash handlers and no HTML5 handlers. Both native and RTMP source handler return `""` to the `canHandleSource(source)` call.

**Comment by p-j** [comment] 2015-02-02 11:06
Just tested on windows, with latest Firefox. Its working and using the HTML5 native handler.

**Comment by p-j** [comment] 2015-02-02 12:00
I found a way to get it working : 
In BigVideo.js, instead of 

```js
  var BV = new $.BigVideo();
  BV.init();
  BV.show('./video/immeubles1.mp4', {
    ambient: true
  });
```
I used 

```js
  var BV = new $.BigVideo();
  BV.init();
  BV.show([{
    type: 'video/mp4',
    src: './video/immeubles1.mp4'
  }], {
    ambient: true
  });
```
Now I get the correct answer from `canHandleSource(source)` and it plays.
It plays using the pipelight player though and not the native HTML5 one, but I guess that's ok.

Hope this helps someone else.

**Comment by gkatsev** [comment] 2015-02-02 17:17
That does help. Sounds like the issue comes about when a type isn't provided (though, you probably should always provide a type).

**Comment by hiteshmodha** [comment] 2015-02-19 12:51
I have same issue in FF 35.0.1

**Comment by mmcc** [comment] 2015-02-27 23:32
I can't reproduce in 4.12 on OS X running [this demo](http://jsbin.com/doquve/4/edit?html,js,output)

- Firefox 35
- Firefox 36
- Firefox 38 (Developer Edition)

That's setting the source via js both with and without a type. Setting it in the src tag has no affect. If someone can put together a reduced test case that shows this we can reopen, but I'm closing for now.

**Comment by heff** [comment] 2015-02-27 23:33
I believe #1905 will fix this issue but I can't be sure. If someone could set up a reduced live example of the error happening I'd know better.

**Closed by mmcc** 2015-02-27 23:32 UTC
Labels: bug
