### ISSUE TITLE
Dash.js  : Live bug ?

### ISSUE THREAD

**Issue by tepaze** [videojs/video.js#3603] opened 2016-09-07 14:33 UTC
Hi,

I think there is a bug with DASH.js on live stream :
player.duration() returns "Infinity" until the first call of timeupdate() event
After that, player.duration() == 2e53 - player.currentTime()
So the message "LIVE" disappears, and timeline with Inconsistent remainingTimeDisplay() appears

I need to force player.duration(Infinity) each timeupdate() event to keep "LIVE" indicator...

videojs v5.10.8
dashjs v2.2.0

I hope this post can be useful, it's my first contribution :-)

**Comment by misteroneill** [comment] 2016-09-08 16:40
This sounds like it might be an issue on the Dash side, but it does sound familiar to things I've heard talked about internally at Brightcove. @forbesjo are you aware of anything like this?

**Comment by ssanth** [comment] 2016-10-03 21:40
Any update on this? 
We are using video.js - 5.10.4 and seeing this issue on DASH Live streams.

**Comment by fozzle** [comment] 2017-01-03 18:50
Seeing this as well, dash @ v2.4.0 and videojs @ v5.12.6. The manifest is being generated by Wowza.

I've opted for hiding that component for now.

**Comment by fozzle** [comment] 2017-01-03 19:56
I've identified the cause of the issue in dash.js contrib and am working to fix it.

**Comment by forbesjo** [comment] 2017-01-05 15:41
Merged @fozzle's fix and is part of contrib-dash 2.6.1

**Comment by gkatsev** [comment] 2017-01-05 16:17
Thanks @forbesjo and @fozzle.

**Closed by gkatsev** 2017-01-05 16:17 UTC

**Comment by tepaze** [comment] 2017-01-05 21:33
Thanks @fozzle and @forbesjo
