### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by nicubarbaros** [videojs/video.js#4807] opened 2017-12-12 10:06 UTC
I get 
```undefined is not an object (evaluating 'e.player.controlBar.progressControl.seekBar.mouseTimeDisplay.hide'``` 
on IOS 11 Mobile (User Agent : ```Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 Mobile/15B202 Safari/604.1```)

Video Js version
```video.js": "^6.2.4```

**Update**
Looks like on mobile   MouseTimeDisplay is undefined in   ```this.player.controlBar.progressControl.seekBar.mouseTimeDisplay.hide()```

**Comment by gkatsev** [comment] 2017-12-12 17:30
I'm unable to reproduce this. Are you using any particular options? Would you be able to provide a reduced test case?

**Comment by misteroneill** [comment] 2017-12-13 19:32
What specific version of Video.js would help as well. You can get it via `videojs.VERSION` in the console.

**Comment by gkatsev** [comment] 2018-01-02 21:28
Closing due to lack of updates.

**Closed by gkatsev** 2018-01-02 21:28 UTC
