### ISSUE TITLE
Autoplay not working on chrome, videojs 6.4.0 / chrome 62.0.3202.75 (Works on Firefox / Edge)

### ISSUE THREAD

**Issue by erick3000** [videojs/video.js#4720] opened 2017-11-04 19:28 UTC
## Description
Using the latest 6.4.0 js and css the autoplay doesn't work only on chrome, tested on firefox / edge and it work. Also videojs 5 autoplay does work, so it seems to be a problem related to version 6.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Load latest JS / CSS 6.4.0
2. Print the player
(example)             <video id='video' class="video-js vjs-fluid" data-setup='{ "controls": true, "autoplay": true, "preload": "auto" }' width="600" height="337" poster="<?=$config->thumbUrl?>/<?=$video->filename?>.jpg?i=<?php echo time(); ?>">
3. try all 3 browsers
-Chrome
-Edge
-Firefox

## Results
Chrome - No Autoplay
Edge - Autoplays
Firefox - Autoplays
### Expected
Chrome - Autoplays
Edge - Autoplays
Firefox - Autoplays

### Actual
autoplay doesn't work

### Error output
none

## Additional Information
Video js version 5 does autoplay correctly
#### videojs
6.4.0 / 6.2.8 tested
#### browsers
chrome
#### OSes
windows
### plugins
none

**Comment by gkatsev** [comment] 2017-11-30 19:59
I'm unable to reproduce this. How are you setting autoplay? Would you be able to make a reduced test case where you can reproduce this? Do you happen to have data saver enabled (not even sure if it's available on desktop)?

**Comment by muralimnmcse** [comment] 2017-12-05 12:34
Me too facing issue after the chrome's updated. 
Cross-origin plugin content from http://vjs.zencdn.net/swf/5.3.0/video-js.swf must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.

**Comment by gkatsev** [comment] 2017-12-05 16:11
Flash is a whole other matter

**Comment by gkatsev** [comment] 2017-12-11 16:39
@andriybohdan it works for me when I change to the "full" view on codepen: https://codepen.io/bav/full/opvMmx/, I wonder if the sandboxing in the normal view in codepen is causing issues.

**Comment by andriybohdan** [comment] 2017-12-11 17:40
@gkatsev Thanks for checking. Hmm.. it works for me in Full view too, but not when i run it outside of codepen. 

Here's the same demo from codepen but without sandboxing:

http://soft-systems.net/t/video-js/index.html

Video is played without issues in Safari, Firefox and iOS Safari, but it fails to auto start in Chrome.

**Comment by gkatsev** [comment] 2017-12-11 18:38
Weird, I can repro your page locally @andriybohdan. I'll take a look, thanks.

**Comment by gkatsev** [comment] 2017-12-11 19:07
That's super weird. Works fine without video.js but fails with Video.js. My local dev setup is autoplaying just fine too.

**Comment by gkatsev** [comment] 2017-12-11 19:10
@andriybohdan do you happen to have an https version of that test page? I wonder if that's an issue?

**Comment by gkatsev** [comment] 2017-12-11 19:12
Tested with an https thing myself and seems to also not work there. It does work without Video.js.

**Comment by gkatsev** [comment] 2017-12-11 19:15
I can get the codepen to fail by middle clicking and to open in a new tab and then switching over.

**Comment by andriybohdan** [comment] 2017-12-11 19:29
yeah, it's strange. If i switch off video.js it works just fine with plain html5 video.

I think it can be related to "src=" attribute. When i check this codepen in safari video.js adds src=...:

```
<video id="player_html5_api" class="vjs-tech" tabindex="-1" autoplay="" muted="muted" **src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"**>
  <source src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" type="video/mp4">
</video>
```

but it's missing when checking in Chome:

```
<video id="player_html5_api" class="vjs-tech" tabindex="-1" autoplay="" muted="muted">
  <source src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" type="video/mp4">
</video>

```

**Comment by gkatsev** [comment] 2017-12-11 19:39
I don't think that matters.
I also found that we have a bug in our `play()` handling that's causing some issues, so, it can't be used as a workaround for this either. I really wonder why my dev environment works fine but not this test page.

**Comment by gkatsev** [comment] 2017-12-11 19:41
OH, I got it to work. If I put Video.js into the `head`, it works fine but not if I have it in the body like it is right now. Bizarre.

**Comment by gkatsev** [comment] 2017-12-11 19:43
Actually, if it's before the video element it seems to work fine.

**Comment by gkatsev** [comment] 2017-12-11 19:48
For example: https://solutions.brightcove.com/gkatsevman/fail.html

I'll see if I can narrow down why it's happening. I wonder if it's a chrome bug related to their autoplay work.

**Comment by andriybohdan** [comment] 2017-12-11 19:51
Right you're. Thanks a lot! 

And now there's "src=" attribute in Chrome as well, so probably it's related in some way.

**Comment by gkatsev** [comment] 2017-12-11 20:19
Seems like it's something to do with moving the video element in the DOM along with the addition of the autoplay attributes. Trying to make a reduced test case and this is what it's leading me to.

**Comment by gkatsev** [comment] 2017-12-11 20:25
I think the problem here is that we have the video element autoplay too early, then when we move the video element into the player div, chrome will pause the video and we don't replay it.

**Comment by gkatsev** [comment] 2017-12-11 21:21
I have a potential fix for this: https://github.com/videojs/video.js/pull/4804

**Comment by andriybohdan** [comment] 2017-12-12 12:42
@gkatsev i've got a chance to try this fix and seems like now it plays video even when autoplay is off in Chrome.

**Comment by gkatsev** [comment] 2017-12-12 15:58
Thanks for testing @andriybohdan, I think I just messed up the conditions :)

**Comment by gkatsev** [comment] 2017-12-12 17:01
@andriybohdan I pushed up an update, would you be able to re-test?

**Closed** 2017-12-14 16:24 UTC

**Comment by gkatsev** [comment] 2018-03-12 22:44
So, the fix for this introduced a regression https://github.com/videojs/video.js/issues/5005. In Chrome 65, it seems to no longer be necessary, I'm going to verify whether it's necessary for Chrome 62, 63, and 64. If it's not necessary in chrome 64, what are your thoughts about getting rid of this workaround? @andriybohdan @tjaneczko @videojs/core-committers.

**Comment by gkatsev** [comment] 2018-03-12 22:50
well, I can't even reproduce our failing test cases from above in browserstack. Maybe it's no longer an issue and we can just remove the workaround.

**Comment by tjaneczko** [comment] 2018-03-13 15:36
If it's no longer an issue with Chrome and the browserstack tests are passing on various versions I think it's probably ok to remove this workaround

**Comment by misteroneill** [comment] 2018-03-13 16:35
Agree with @tjaneczko - if it's no longer reproducible in a few recent versions of Chrome, we should revert the workaround.

**Comment by rijosh** [comment] 2018-05-24 05:40
This is because of now chrome is preventing auto play in html5 video, so by default they will not allow auto play. so we can change this settings using chrome flag settings. this is not possible for normal case so i have find another solution. this is working perfect...
(add preload="auto")

<video autoplay preload="auto" loop="loop" muted="muted" id="videoBanner" class="videoBanner">
    <source src="banner-video.webm" type="video/webm">
    <source src="banner-video.mp4" type="video/mp4">
    <source src="banner-video.ogg" type="video/ogg">
</video>


 //Video auto play bug fixing
           var herovide = document.getElementById('videoBanner');
           herovide.autoplay=true;
           herovide.load();  
//Video auto play bug fixing

**Comment by campones** [comment] 2018-11-10 16:18
facing a weird issue with videojs 7.0.5 where autoplay works fine while navigating through the site but not working when pressing the refresh button (f5).  that's with chrome 70, no issues on firefox.

**Comment by gkatsev** [comment] 2018-11-10 18:56
That sounds like expected behavior if you have a low IME score on Chrome. Once you interact with a domain, autoplay restrictions are released until the page is refreshed/navigated away from.
We have a best practices post on our blog: https://blog.videojs.com/autoplay-best-practices-with-video-js/

**Comment by campones** [comment] 2018-11-13 16:43
maybe but on my other domain, the exact same site will autoplay so..

**Comment by stratboy** [comment] 2018-11-15 10:20
I have tried every possible solutions explained here, but video.js doesn't autoplay with chrome. It does in every other browser but not chrome. Also note that, as pointed out by others here, it will perfectly work without video.js. So it's not a chrome issue, nor a configuration issue. It must be a bug.

**Comment by gkatsev** [comment] 2018-11-15 16:00
I looked into it a bit as part of https://github.com/videojs/video.js/issues/5581 and it does seem like there's something weird going on. We'll investigate more.

**Comment by stratboy** [comment] 2018-11-15 16:37
Ok I SOLVED this issue this way (kind of a hack) > extracted from some source of mine, so please forget variables:

``` html
  <video  loop class="video-js main-video-bg" id="video-bg">
    <source src="<?= $video_bg_mp4; ?>" type="video/mp4">
  </video>
```

Than later

``` js
var player = videojs('video-bg');
player.ready(function(){
  _.delay(function(){ player.autoplay('muted'); }, 1000); // lodash here, but it could be simply setTimeout
});
```

So 3 things are implied here:

- Didn't use video's autoplay/muted attributes or data-setup 
- Used 'muted' and not 'mute' (before > MY FAULT!!!)
- Delayed the player autoplay call <<< this is crucial. Used 1000ms, but maybe even less is enough.

Now it works, but the need for delay is quite a strange thing. Maybe, if really needed for chrome, you could hide it into your autoplay implementation.

**Comment by gkatsev** [comment] 2018-11-15 16:44
Thanks @stratboy that's helpful. It did seem like some timing issue when I looked at it quickly yesterday, so, thanks for confirming it. We definitely should be covering it internally in Video.js. Users shouldn't need to do that.

**Comment by stratboy** [comment] 2018-11-15 17:02
@gkatsev chrome's need for some time to wake up before doing well, is something I already saw before 2 or 3 more times on other contexts than video (don't remember, but I clearly remember reviewing some code of mine that had timers with some 'chrome wtf/hell' comments beside). It's kind of buggy without any reason sometimes. To be true, I never liked chrome, I never felt it as something really solid, don't know why, but my 20 years of web development force me to this instinct for some unknown reason :nerd_face:

**Comment by gkatsev** [comment] 2018-11-15 17:08
Hah, yeah, there's definitely sometimes weird things happening.

**Comment by dhullsumit** [comment] 2018-11-22 07:45
I solved. this is not a generic solution, but its working fine for me.
you just need to reload page.

<video preload="auto"autoplay muted loop >
      <source src="vid.mp4" type="video/mp4">
</video>

<script>		
	var video = $("video").get(0);
	video.load();
	video.play();
	if (video.paused){
		location.reload(true);
	}
</script>

**Comment by dhullsumit** [comment] 2018-11-22 07:51
I solved. this is not a generic solution, but its working fine for me.
you just need to reload page.

`<video preload="auto"autoplay muted loop >`
`<source src="vid.mp4" type="video/mp4">`
`</video>`

`<script>	`	
	`var video = $("video").get(0);`
	`video.load();`
	`video.play();`
	`if (video.paused){`
		`location.reload(true);`
	`}`
`</script>`

**Comment by stratboy** [comment] 2018-11-22 07:55
@dhullsumit  please see mine above.

**Comment by dhullsumit** [comment] 2018-11-22 08:03
@stratboy, this is for if you are not using any pluging.

**Comment by stratboy** [comment] 2018-11-22 08:10
@dhullsumit as I wrote, you can just use a plain-ancient-pure-vanilla-shining-javascript `setTimeout()` function instead of _.delay.

**Comment by webakimbo** [comment] 2018-12-04 06:43
More data in case it's useful:
- Delaying play/autoplay in my js does not work for me, including @stratboy's implementation above.
- BUT I can play the video just fine if I run the exact same command manually in the js console.

Worth noting that I'm running an old version (v5.17.0) on a 2yo Rails codebase; Sprockets is choking on the newer version I downloaded (v7.3.0).

**Comment by asksandeep** [comment] 2020-04-13 09:47
Thanks :) It's working
