### ISSUE TITLE
5.0-rc.2 - no video playback in Android 4.1 stock browser

### ISSUE THREAD

**Issue by meleyal** [videojs/video.js#2277] opened 2015-06-19 09:35 UTC
Happens on Android 4.1.2 using stock browser ("Internet" app).

1. Open test page
2. Click play button

Expected: Video starts playing
Actual: No video playback / black screen
Test case: http://jsbin.com/halokodoxo/1/edit?output

![screenshot_2015-06-19-10-45-14](https://cloud.githubusercontent.com/assets/15045/8250762/0f439f58-1677-11e5-9765-6b5d0aa1a4e7.png)

Maybe related: #2044, #1986, #975

**Comment by moay** [comment] 2015-08-20 10:54
Confirm. Also happens in rc58, but not only in stock browser - for me it's also chrome on android. The video will just not load, the poster image stays there.

**Comment by moay** [comment] 2015-08-20 11:19
I checked the logs I get on chrome, here is what I get:

    VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}_logType 
    
    @ log.js:79116.log.error 
    @ log.js:31error 
    @ player.js:2026handleTechError 
    @ player.js:1019ret 
    @ fn.js:35ret     
    @ fn.js:35112.data.dispatcher 
    @ events.js:72

Works on iOS devices.

**Comment by heff** [comment] 2015-08-20 16:48
@forbesjo have you done any testing on Android with 5.0 yet?

**Comment by moay** [comment] 2015-08-20 17:56
This test was done on VJS 5. :-) Was just saying, that the displayed error cannot be true because the media and the network both are the same for a working setup with VJS4. Sorry, I hope it's easier to understand now?

**Comment by gkatsev** [comment] 2015-08-20 18:02
What device is it? Samsung?
What I could imagine is that you'd need to include the es5-shim for it to work but don't have specific proof.

**Comment by forbesjo** [comment] 2015-08-20 18:04
I can confirm that the issue still appears with the latest rc using 4.1.2 stock browser. 5.0 Android looks ok.

**Comment by moay** [comment] 2015-08-20 18:07
Yes, its a Samsung. But its running Android 5.0 (Cyanogenmod) and Chrome.

**Comment by moay** [comment] 2015-08-20 18:11
es5-shim doesn't change anything. ;-)

**Comment by gkatsev** [comment] 2015-08-20 18:29
Seeing this in logcat:
```sh
I/chromium(14190): [INFO:CONSOLE(10422)] "Uncaught TypeError: videojs is not a function", source: http://10.1.12.72:8080/build/temp/video.js (10422)
```

**Comment by gkatsev** [comment] 2015-08-20 18:30
Actually, never mind.
I *can* get it to work, but you basically need to press play several times.

**Comment by gkatsev** [comment] 2015-08-20 18:55
Ugh, it's really hard to debug on this device. It doesn't want to log anything that is viewable in logcat.

**Comment by moay** [comment] 2015-08-21 06:33
When I was testing, I used chrome and USB debugging, which actually worked quite well for the log. But I didn't get the error you got, so videojs seems to be initializing correctly. Just doesn't want to play the file... It doesn't matter if I use an mp4 or a webm file, also the number of players I run doesn't change anything.

**Comment by gkatsev** [comment] 2015-08-21 06:40
Yeah, ignore that error. It isn't relevant. Actually, yeah, I totally forgot to see whether I can inspect using the remote debugging since it's a chromium-based native browser.
Have you tried pressing the play button multiple times? That's how I've gotten it to play on my device. :P

**Comment by moay** [comment] 2015-08-21 08:21
Yes, I tried. When I hit the big play button, it disappears and the controls appear. So I can click on pause - play - pause - play - and so on. That doesn't change anything. If I try to hit the timeline to play the video at some point, the current playback time switches to -1:0-1 and thats it.

**Comment by gkatsev** [comment] 2015-08-21 15:09
Looks like if you put in `about:debug`, you get a little debug menu in Settings which enable you to show the console on the device itself.

**Comment by gkatsev** [comment] 2015-08-21 15:12
Looks like on this device, the thing to grep for is `Console`. On all other devices previously, I grepped for `CONSOLE` and it worked.

**Comment by gkatsev** [comment] 2015-08-21 16:18
I have a tentative fix for it locally.

**Comment by moay** [comment] 2015-08-21 16:59
@gkatsev Can I test it?

**Comment by gkatsev** [comment] 2015-08-21 17:10
I'll have a PR open/updated soon.

**Comment by gkatsev** [comment] 2015-08-21 17:53
@moay https://github.com/videojs/video.js/pull/2499 should hopefully fix the issue.

**Comment by gkatsev** [comment] 2015-08-21 17:56
Adding that option by default for "native android browsers".

**Comment by moay** [comment] 2015-08-21 17:58
I'll test it with the next rc release. ;-)

**Comment by moay** [comment] 2015-08-22 09:03
Okay, tested this. Still did not work - so I removed the password protection of the directory in which the video lays and voilà, it works. So it seems, that was the error I made. (The video file was protected with a basic http authentication)

Now, there are two new "bugs" since I updated from rc59 to rc60. 
- The controls won't appear on my phone using chrome android, so I can't control the playback at all.
- I can't pause the video in chrome on my mac by clicking somewhere on the screen any more. This used to work with rc59. Can only pause using the pause button with rc60.

I reverted to rc59 for testing and playback on chrome mobile works when the password protection is removed. Sorry for the confusion, didn't expect this to be a problem!

**Comment by moay** [comment] 2015-08-24 07:15
Sorry guys, my macbook seems to have some glitches... I'm at work now, and the described errors don't appear any more. Even on mobile, chrome now plays the video and gives me the controls. It's still a bit buggy, but that is probably caused by my phone.

I still have one strange behaviour with webm files, but thats not confirmed (maybe the file) and it's not related to this issue. Will open an issue for this, if needed.

**Comment by gkatsev** [comment] 2015-08-24 18:54
@moay so, are you seeing this issue anymore or can this be closed?

**Comment by moay** [comment] 2015-08-25 07:19
@gkatsev I can't see the error that was initially described in this issue any more, thats correct. Opened issue #2504 for the error that started to appear when this issue was fixed.

So for me, this one is closed. ;-)

**Comment by gkatsev** [comment] 2015-08-25 14:51
OK. I'll close this issue but if it's still occurring for people, we can always reopen.

**Closed by gkatsev** 2015-08-25 14:51 UTC
