### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null at VideojsDelegate

### ISSUE THREAD

**Issue by RaviJayagopal** [videojs/video.js#7367] opened 2021-08-06 22:37 UTC
Getting the following error only when a VideoJS video is viewed on a mobile device as well as mobile-sized screen:

VM4999:214 Uncaught TypeError: Cannot read property 'classList' of null
    at VideojsDelegate (<anonymous>:214:46)
    at add_element (<anonymous>:395:17)
    at MutationObserver.<anonymous> (<anonymous>:419:17)

You can see it in action at https://redesign.freelancewritersden.com/jeremy-new-video-test/ .

If there's multiple videos on a page, only the last video plays. All of the ones above the last one give the above errors.

Happening in iOS (iPhone 12) and also on desktop (Windows, Chrome browser) when viewing through Dev console and testing it in different mobile sizes.

Videojs version: 7.14.3 (latest)

**Comment by gkatsev** [comment] 2021-08-09 20:23
I think it's something on your end that's causing the issue. I cannot reproduce the classList issue, but I can see that on your site if I use Chrome's Response Mode and set it to iPhone X only the last player loads.
One thing I noticed is that Video.js is included on the page 3 times. Ideally, you should only include it once. In addition, you have the players set up automatically via `data-setup` but you also try and initialize them via calling `videojs()`.
I've extracted the 3 video players and with a single inclusion of Video.js they seem to work fine when it's loaded in the iPhone X response mode https://codepen.io/gkatsev/pen/poPqNQX

**Comment by RaviJayagopal** [comment] 2021-08-09 22:44
Hi @gkatsev, thank you for your reply.

See https://contentresponder.com/multiple-long-videos-165/ 

The page has multiple videos, and works fine on desktop.

But exact same page does not work on mobile, and also does not work on desktop if using responsive view.

See https://i.imgur.com/mhIBVA1.png

**Comment by FredZeng** [comment] 2021-08-10 04:23
@RaviJayagopal As gkatsev explained, the direct reason is including multiple Video.js, which makes the autosetup algorithm runs multitime.

And the reason why same code works differently, may see [html5.js#L369-L383](https://github.com/videojs/video.js/blob/main/src/js/tech/html5.js#L369-L383).

Since `Html5.prototype.movingMediaElementInDOM = !browser.IS_IOS;` depends on browser, when meeting iOS, it will try to clone a new `video` node.

According to [MDN cloneNode](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode), `cloneNode` does not copy attributes assigned to element properties.

> Cloning a node copies all of its attributes and their values, including intrinsic (inline) listeners. **It does not copy event listeners added using addEventListener() or those assigned to element properties (e.g., node.onclick = someFunction)**.

Hence, after `createEl`, the new `video` tag lost it's `player` attribute, which is required by `autoSetup()` algorithm to skip duplicate setup.[See setup.js#L38-L47](https://github.com/videojs/video.js/blob/main/src/js/setup.js#L38-L47)

@gkatsev Do you think it is necessary to cover such situation?

**Comment by RaviJayagopal** [comment] 2021-08-10 06:25
Happy to report that the issue is resolved. It was due to the multiple inclusion of the videojs js file. I missed that because it has worked fine in the past - probably a few years ago. Not sure what changed in videojs or in browsers for it to stop working now.

Thank you for your help @gkatsev and @FredZeng

**Closed** 2021-08-10 13:16 UTC
