### ISSUE TITLE
No Compatible Source was found for this Media : ( in Search Console only )

### ISSUE THREAD

**Issue by moeinomidii** [videojs/video.js#5242] opened 2018-06-10 10:15 UTC
everything is ok for my users to watch some stuff from my website. but when i Fetch & Render My Website i'll get this error . i also did this : https://github.com/videojs/video.js/issues/4401 .
Screenshot of Google Search Console : http://s9.picofile.com/file/8328825634/google.JPG
an Example form ma website : https://bazitori.com/gametrailer/38/

**Comment by gkatsev** [comment] 2018-06-18 18:36
Closing this as a duplicate of #5193.

**Closed** 2018-06-18 22:43 UTC
