### ISSUE TITLE
VideoJS stops on some HLS segments with unclear error messages

### ISSUE THREAD

**Issue by yshatz** [videojs/video.js#7020] opened 2020-12-29 17:33 UTC
## Description
Some streams that our player generates suddenly stop in VideoJS player in Chrome, with messages "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

We've isolated the segment(s) that cause it, see [here](https://videojs-hls-chunks-debug.s3-eu-west-1.amazonaws.com/6669/playlist.m3u8) or you can download archive from [here](https://drive.google.com/file/d/185AejKKyVNL1pYbzs0S5Hs3ktw4M_pJt/view?usp=sharing)

The same playlist plays fine in VideoJS/Firefox and in VLC.

Message in media console is 
Failed to send video packet for decoding: {timestamp=30000000 duration=0 size=63 is_key_frame=0 encrypted=0}

It stops playing on the border of segments 65 and 66. Parsing them with ffprobe I do not see any packets of such a small size and in general nothing wrong. 

## Steps to reproduce
1. open https://videojs-http-streaming.netlify.app tool in chrome
2. Point it to https://videojs-hls-chunks-debug.s3-eu-west-1.amazonaws.com/6669/playlist.m3u8
3. Start playing

### Expected
Expected to play all segments of the list (60 seconds). If in fact one of the segments is defective, we'd expect player to jump over it and play the next one. And hopefully give us some more diagnostics (at least filename, offset). 

If there's an option to ignore errors, we'll advice the customer to use it (we ourselves do not use VideoJS, we generate the stream)

### Actual
After 30s it stops

### Error output
Messages in Media console:
Prepared video sample is not conformant
Failed to send video packet for decoding: {timestamp=30000000 duration=0 size=63 is_key_frame=0 encrypted=0}

#### videojs
Not sure what client has, we tested with https://videojs-http-streaming.netlify.app/, which is presumably the latest.
#### browsers
Chrome
#### OSes
Windows and Linux

**Comment by DispatchCommit** [comment] 2021-03-31 16:17
I can't reproduce such an error

**Comment by gkatsev** [comment] 2021-04-02 16:55
I think this may have been fixed via https://github.com/videojs/mux.js/pull/378, which is in latest VHS now.

**Closed by gkatsev** 2021-04-02 16:55 UTC
