### ISSUE TITLE
Muted button disappear in iphone(ios 10.3)

### ISSUE THREAD

**Issue by kayakyelf** [videojs/video.js#4373] opened 2017-05-23 03:43 UTC
## Description
I added videojs in my project and testing it  on my iphone.  

## Steps to reproduce
1. I set the player muted so that it can autoplay. 
2.But cannot find the mute button and volume button to control the audio.

### Expected
have the mute button to control muted or not

### Actual
No mute button and cannot control the volume

#### videojs
video-js-5.20.1
#### browsers
safari
#### OSes
ios 10.3

Could anyone help to solve this?

**Comment by arashilan** [comment] 2017-07-12 03:52
Me too. Set autoplay on iOS
When set "autoplay muted" in `<video>` ,then the video can autoplay.
When set "autoplay" `<video>` ,then video can't autoplay.

**Comment by misteroneill** [comment] 2017-07-12 17:13
@arashilan That is a limitation of Safari, not something Video.js can control.

**Comment by misteroneill** [comment] 2017-07-12 17:13
This looks like a duplicate of #4478

**Comment by couchcrew-thomas** [comment] 2018-02-06 10:15
The current iOS Safari supports JS control of the muted behaviour. So this is indeed a bug.

**Comment by gkatsev** [comment] 2018-05-04 22:09
Duplicate of #4478

**Closed by gkatsev** 2018-05-04 22:09 UTC

**Comment by moti5565** [comment] 2018-06-21 19:42
#4478

**Comment by gkatsev** [comment] 2018-06-21 19:49
This should be fixed in master now, a release of 7 is coming soon and it'll be back ported to 6.x at some point as well.
