### ISSUE TITLE
Seeking backwards while using nativeControlsForTouch breaks playback

### ISSUE THREAD

**Issue by third774** [videojs/video.js#6444] opened 2020-02-12 20:23 UTC
## Description
When using the `nativeControlsForTouch` for option with a DASH manifest, seeking backwards breaks playback.

## Steps to reproduce
1. Open https://codepen.io/third774/pen/xxboOvr
2. Open Chrome dev tools and turn on device toolbar (for touch controls)
3. Reload the page (re-initializes player to use native touch controls)
4. Seek at least 3/4 into the video.
5. Seek back toward the start of the video (playback will break and not resume here)

### Expected
The player should seek backwards and load the appropriate segments to resume playback at the seeked time

### Actual
Loading of segments for newly seeked time never happens, and as a result playback never resumes.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Latest (7.6.6)
#### browsers
Chrome (at least)
#### OSes
MacOS, Android
### plugins
None

**Comment by gkatsev** [comment] 2020-03-17 20:53
So, I think this may be due to us switching to middleware in VHS: https://github.com/videojs/http-streaming/pull/161.
That PR seems to cause some issue in VHS 1.x (https://github.com/videojs/http-streaming/issues/378), and we may be reverting it there, though, we don't currently have a plan to revert that PR in master as that issue isn't present in master.

**Comment by third774** [comment] 2020-03-18 02:03
Cool — thanks for the update! I'll see if building with `master` makes this problem go away and report back.

**Comment by third774** [comment] 2020-03-18 02:26
Hrm — so, I built `video.js` from source at the tip of `master` after building `@videojs/http-streaming` from source and linking it in `video.js`, the problem still seems to exist.

Did I understand correctly that the problem should not exist in `master` if switching to middleware in VHS is the root cause?

**Comment by gkatsev** [comment] 2020-03-18 21:56
Master still uses middleware, so, it won't be fixed. You can try the PR videojs/http-streaming#777 and see if that works.
For master, we may look into doing a hybrid approach or maybe just see if native controls are being used and then not rely on the middleware, still thinking things through.

**Comment by third774** [comment] 2020-03-18 22:59
Awesome! That PR does indeed fix it. Thanks for everything you do! 🎉

**Comment by gkatsev** [comment] 2020-03-19 01:17
You're welcome, then, yes, indeed, the issue is that. We'll have to come up with a solution in master. We're likely going to merge and release that PR in the 1.x release line soon.

**Comment by third774** [comment] 2020-05-18 20:49
✨

**Closed** 2020-07-25 07:36 UTC
Labels: outdated

**Comment by gkatsev** [comment] 2020-08-06 05:17
Also, we reverted the middleware change in the main branch, so, this should be fine with VHS 2.x as well.
