### ISSUE TITLE
VideoJS not working in Chrome, but its working in Firefox

### ISSUE THREAD

**Issue by anantapon** [videojs/video.js#5842] opened 2019-03-06 09:47 UTC
The player display error message below:

"The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

My code:

```
<link href="https://vjs.zencdn.net/7.4.1/video-js.css" rel="stylesheet">
--
  | <script src='https://vjs.zencdn.net/7.4.1/video.js'></script>
  | <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
  | <script src="https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js"></script>


<!-- VideoPlayer -->
--
  | <video id='video-player' class='video-js' controls preload='auto' width='640' height='320' data-setup='{}'>
  | <source src='../file_upload/module/manage_digital_file/digital_file/7f54fa63.mp4' type='video/mp4'>
  | <p class='vjs-no-js'>
  | To view this video please enable JavaScript, and consider upgrading to a web browser that
  | <a href='https://videojs.com/html5-video-support/' target='_blank'>supports HTML5 video</a>
  | </p>
  | </video>
```

Thank you.

**Comment by gkatsev** [comment] 2019-03-06 15:09
Does your backend support byte range requests? That is often the cause of mp4s not playing on chrome but playing in firefox.

**Comment by captainjlp** [comment] 2019-03-20 21:32
same problem: 
doesn't work with Chrome (73.0.3683.86 (Official Build) (64-bit)) 
but woks without any Problem with 
- Firefox (65.0.2 64-bit)
- Internet Explorer (11.379.17763.0 - Update version 11.0.115)
- Chrome on Samsung 9 or Huawei Tablet

**Comment by captainjlp** [comment] 2019-03-20 21:33
test: with the following URL:
https://www.tvcom.be/video/culture/musique/l-invite-corentin-piquard-participant-a-l-open-stage_23687_300.html

**Comment by captainjlp** [comment] 2019-03-20 21:40
--> Error:
Ad error: AdError 400: There was an error playing the video ad. Caused by: Error: Error: There was an error playing the video ad. --> in: videojs.ima.js:1385

**Comment by goatandsheep** [comment] 2019-04-24 03:07
@gkatsev does byte range request support make it better or worse?

**Comment by gkatsev** [comment] 2019-04-29 21:44
@goatandsheep byte range requests are required by some browsers.

**Comment by gkatsev** [comment] 2019-04-29 21:46
@captainjlp I'm unable to see any playback issues with your test page.

I'm closing this issue but if we get more info or another test page, we can re-open, if necessary.

**Closed by gkatsev** 2019-04-29 21:46 UTC

**Comment by Irirus** [comment] 2020-04-28 02:16
I have this issues also, still cant not fix this

**Comment by TijnSnijders** [comment] 2020-05-14 20:31
I am experiencing actually something different. 

I have a test rtmp server running (with HLS) to which I am streaming to. I can pick up the stream in VLC. I have a simple bit of code taken from the video-js website to display the stream running on my (seperate) webserver. 

Loading the page in Edge, the stream comes through no problem, but Chrome (and Brave) and Firefox won't load the m3u8 file. It tells me the media counld not be loaded because either the server or network failed or because the format is not supported.

But it runs fine in Edge... I am baffled.

**Comment by cygnuson** [comment] 2021-03-31 03:12
I am also having this problem. Edge works fine, no problem but chrome and firefox dont work.

**Comment by cygnuson** [comment] 2021-03-31 04:51
I solved this by the following: 
`<video id="my-video" class='video-js vjs-default-skin' controls preload="auto"
            data-setup='{"fluid": true, "autoplay":true,"html5": {"vhs": {"overrideNative": true},"nativeAudioTracks": false,"nativeVideoTracks": false}}'>`
This causes everything to use the non-native player, which edge requires. I knew it was fishy that EDGE was working and chrome wasnt.  It turns out in this case EDGE worked because its not as featurefull as chrome. 

This issue is not "closed" since the native player support for chrome is not working.  Just to be clear, this is an issue with the native player support on chrome.

**Comment by gkatsev** [comment] 2021-04-02 16:59
I have seen the soundhandler thing appear but haven't been able to track it down consistently. I think Chrome has been experimenting with native audio tracks for a while and is finally working on them. We potentially already have a workaround for Edge for this, which is why it's working fine, I'm not sure.
We probably want to override audio and video tracks by default whenever we override native by default. We haven't gotten around to it yet because I've mostly seen `soundhandler` not appear.

**Comment by eban5** [comment] 2021-06-03 19:27
hey, @gkatsev - we were able to reproduce "SoundHandler" appearing and causing this bug:

1. In Chrome, go to `chrome://flags` and enable "Experimental Web Platform features"

2. Relaunch Chrome when prompted

3. Go to a video such as https://www.pbs.org/video/ship-that-changed-the-world-vdrvtc/

4. Hover over the audio track button in the controlbar and you'll see `SoundHandler` appear as the default selected option.

5. Start playback of the video and at about the 0:05 mark, you will notice the video stop and hang there.

6. Switching the audio track to any other track, like English or English AD, will allow the video to resume playback

We only see this happen when Experimental Web Platform features is enabled and so far have only seen it in Chrome.

**Comment by gkatsev** [comment] 2021-06-24 19:33
@eban5 OMG, that makes total sense. Apparently I had it enabled for a long time because I was testing some stuff that required it. I guess that's where they're experimenting with it.
