### ISSUE TITLE
Weird character in CSS file breaks grunt-contrib-less task run

### ISSUE THREAD

**Issue by thasmo** [videojs/video.js#3145] opened 2016-02-29 09:38 UTC
## Description
Running `grunt-contrib-less` throws an error. The problem is a corrupted/weird character in `dist/video-js.css` on line 581.

### Expected
Grunt task runs properly.

### Actual
Grunt task throws an error.

### Error output
```
>> SyntaxError: media definitions require block statements after any features in fileadmin/dist/bower.css on line 4806, column 8:
>> 4805
>> 4806 @media ?screen {
>> 4807   .vjs-user-inactive.vjs-playing .vjs-control-bar :before {
```

#### videojs
Occurs with 5.7.x and 5.8.x and also with 5.4.x. Probably also with all versions in between.

**Comment by mmcc** [comment] 2016-02-29 17:00
That'd be pretty crazy bizarre if it's really `grunt-contrib-less` throwing the error, since we switched to Scss for v5. That's a good reminder that we should probably go through and clean out any old dev packages that aren't in use anymore.

I don't see this issue locally. What version of Node / NPM are you using?

**Comment by thasmo** [comment] 2016-02-29 17:26
We're using `grunt-contrib-less` to compile less files to css files. In our `grunt-contrib-less` task configuration we also process a `CSS` file named `bower.css` which has been created by `grunt-bower-concat`. When the less-compiler processes the `bower.css` file, it throws the mentioned error, because it obviously has problems with the corruptet character in the file, which comes from the `video-js.css` file.

SO, it could ba argued that this is a less-compiler bug, although it would be nice if it's possible to remove the bad character from the distributed video.js CSS file.

```
> grunt less
Running "less:main" (less) task
>> SyntaxError: media definitions require block statements after any features in fileadmin/dist/bower.css on line 4806, column 8:
>> 4805
>> 4806 @media ?screen {
>> 4807   .vjs-user-inactive.vjs-playing .vjs-control-bar :before {
Warning: Error compiling fileadmin/dist/bower.css Use --force to continue.
Aborted due to warnings.
Task 'less:main' took 1010ms
All tasks took 1010ms
```

**Comment by gkatsev** [comment] 2016-02-29 17:36
I think this is a dupe of the #3013. Less is probably complaining about the utf8 character in our CSS output.

**Comment by gkatsev** [comment] 2016-03-28 19:20
I think I'm going to close this as a dupe of #3013.

**Closed by gkatsev** 2016-03-28 19:20 UTC

**Comment by wing-zheng** [comment] 2018-02-19 06:52
how to solve this problem
