### ISSUE TITLE
Full screen bug in ios devices

### ISSUE THREAD

**Issue by tekbahadur1996** [videojs/video.js#5098] opened 2018-04-16 09:02 UTC
When you enter in the full screen mode in IOS devices and leave the full screen mode then you can see two different controls overlapping each other.

**Comment by mister-ben** [comment] 2018-04-29 13:33
On which Video.js and iOS versions? As far as I'm aware this isn't an issue with current versions.

**Comment by gkatsev** [comment] 2018-06-18 22:19
Sounds like this is a duplicate of #3762.

**Closed** 2018-06-18 22:19 UTC
