### ISSUE TITLE
Player icons do not appear in ie8

### ISSUE THREAD

**Issue by noekidotcom** [videojs/video.js#2982] opened 2016-01-08 08:54 UTC
Though functionality is fine thanks to the de ie8 shim, the player icon font does not display in ie8. Utf-8 metatag is in place and I've tried both versions 5.4.4 and 5.4.6 of the VideoJS distribution files. Any ideas?

**Comment by mmcc** [comment] 2016-01-08 15:59
Are you hosting yourself or using the CDN? Mind trying the CDN version just as a test?

This also reminds me that the official IE EOL is in 4 days (Jan 12). :tada: :100: :fireworks:

**Comment by noekidotcom** [comment] 2016-01-11 09:07
Thank you for your prompt respond. The problem occurs no mater how the library is loaded (either self hosted or via CDN). I also tested pre-release 5.5.1 to no avail. Control containers are present and functional in ie8, only with no visible icon fonts. Time tootips over progress bar show with no issues. I kwow ie8-9-10 support will effectively drop soon, but this web I'm building comes with ie8 support. If it helps, version 4 (up to 4.11 release) is ok regarding player icosn in ie8, I guess that's a whole different thing though.

**Comment by tneaves** [comment] 2016-01-12 15:18
@mmcc I am having trouble even getting the IE8 player to work, at all. Even with the CDN hosted script.

**Comment by mmcc** [comment] 2016-01-13 06:45
That's strange, because it seems to be working fine for me in a VM:

![VirtualBox](https://www.dropbox.com/s/w8q65q4b98la5q8/Screenshot%202016-01-12%2022.43.40.png?raw=true)

Here's the [example I'm running](http://jsbin.com/jumapedaku) in that screenshot.

I'm going to close this, but feel free to continue the conversation in the comments.

**Closed by mmcc** 2016-01-13 06:45 UTC

**Comment by legendjslc** [comment] 2016-01-13 06:51
you should add mime type of web font to IIS to allow browser to download it.

http://stackoverflow.com/questions/26177849/mime-types-for-woff-ttf-svg-and-eot-404ing-despite-being-setup-in-iis

**Comment by ownmaster** [comment] 2017-01-31 17:16
Hi,

I have exact same problem as shown on the screenshot in the [above post](https://github.com/videojs/video.js/issues/2982#issuecomment-170944468). I can even play the video, but during playback I can't see control icons (play/pause, sound), though I can see the popup labels above them when hovering ('Pause', 'Mute').

I check it in IE11, Windows 10 64-bit, in IE8 mode: `<meta http-equiv="X-UA-Compatible" content="IE=8"/>`. Video.js version: 5.15.1.

This has to do something with fonts because, for example, if in video-js.css I change
```
.vjs-icon-play:before, .video-js .vjs-big-play-button:before, .video-js .vjs-play-control:before {
    content: "\f101"; }
```
to
```
.vjs-icon-play:before, .video-js .vjs-big-play-button:before, .video-js .vjs-play-control:before {
    content: "XXX"; }
```
I can see `XXX` on a big play button.

I tried solution above about adding font mime types to IIS web.config but that didn't change anything, actually this should not be server problem, since player renders correctly if I switch to IE9, IE10 or IE11 mode in the same browser. It also renders correctly in Opera and Firefox.

The problem is that I have to use IE8 mode, otherwise other page functionality fails, so there is no option.

Can this be 'fixed'?
If not, can you give suggestions how can I rework default CSS file to show the buttons (using images, for example)?
Or maybe I should downgrade video.js to some old version?

Here is how it looks (preview and playback):
![ie8mode-preview](https://cloud.githubusercontent.com/assets/10141077/22475815/df315248-e7e8-11e6-93b1-443ef50ad6d3.png)
![ie8mode-playback](https://cloud.githubusercontent.com/assets/10141077/22475855/09eebcf0-e7e9-11e6-93b4-df80dfd7bc30.png)
