### ISSUE TITLE
Text tracks: problems with VJS 4.12.1 - Specifically, Chapters

### ISSUE THREAD

**Issue by Globulopolis** [videojs/video.js#1908] opened 2015-02-28 10:29 UTC
Hi!
Found a strange behavior with the text tracks.

1. Subtitles not working anymore in InternetExplorer(at least for 11 version).
I can see the menu with subtitles but when I select subtitle nothing displayed on video.

2. Chapters not working anymore. I tested video in IE11, FF35, Chrome 34. Even menu isn't displayed.
This is chapters file http://demo.киноархив.com/downloads/trailers/m/2/monte-carlo-2.chapters.vtt Maybe something wrong with this file?

**Comment by ksheurs** [comment] 2015-02-28 18:32
Possibly related, I am noticing in Chrome on OSX (Version 40.0.2214.115) tracks fail loading for me unless I put `crossorigin="anonymous"` on the `<video>` tag. I properly have CORS setup, but without that `crossorigin` attribute I get the following error: 

"Text track from origin 'https://xyz.cloudfront.net' has been blocked from loading: Not at same origin as the document, and parent of track element does not have a 'crossorigin' attribute. Origin 'http://player.host.com' is therefore not allowed access."

Is this expected in Chrome? Is there a list of agents where I should put this attribute on the `<video>` tag or is this something VideoJS should be handling?

Thanks again!

**Comment by gkatsev** [comment] 2015-03-09 21:51
As @ksheurs said. Also, make sure your mimetype is set correctly for the VTT files. IE11 is particularly strict on this. This is being tracked in #1904 and #1888.
As for chapters, they should work last I checked. Can you a test case with chapters not working please?
Thanks.

**Comment by gkatsev** [comment] 2015-03-09 21:59
Changing the title of this to about Chapters since the other issue is tracked elsewhere.

**Comment by Globulopolis** [comment] 2015-03-10 08:04
@gkatsev my .htaccess file:
    AddType audio/mp4 .m4a .f4a .f4b
    AddType audio/ogg .oga .ogg
    AddType video/mp4 .mp4 .m4v .f4v .f4p
    AddType video/ogg .ogv
    AddType video/webm .webm
    AddType video/x-flv .flv
    AddType text/vtt .vtt

Last line will fix subtitles display for Firefox and Chrome. But still not working in IE11. And chapters not working in "all" browsers.
I'm revert back to VJS 4.11.4 and subtitles, chapters... works as expected.
http://demo.киноархив.com/index.php?option=com_kinoarhiv&view=movie&page=trailers&id=2&Itemid=102&lang=ru (second video)

**Comment by gkatsev** [comment] 2015-03-10 17:19
Interesting. Can confirm that there's an issue. I wonder if it has to do with minification.

**Comment by Globulopolis** [comment] 2015-03-10 17:32
@gkatsev now tested with dev version of VJS and can confirm that subtitles now work in IE, and Firefox and Chrome.
Chapters still not work in IE and Chrome.

PS! Tested with VJS 4.12.3 dev.

**Comment by gkatsev** [comment] 2015-03-10 17:35
Thanks for checking!

**Comment by OwenEdwards** [comment] 2015-03-13 20:23
Just catching up with this, but I've seen the same problem with Chapters which is fixed by using the dev version of 4.12.3, so it must me a minification problem. I was thinking it was related to #1864, too, since there's an impact on other tracks (they get a repeated 'update' event based on the timer that #1864 refers to), so it's somewhere in there, but I haven't 'tracked' it down yet ;-)

**Comment by EZWrighter** [comment] 2015-04-24 00:08
This might be helpful here...looks like CORS and tracks are broken in IE11: https://connect.microsoft.com/IE/feedback/details/817222/ie-11-unable-to-load-captions-cross-domain-with-track

I can confirm...valid CORS/mime-type setup working into every other environment except IE11.  Same local caption file displays correctly.

The bug has been on the books for over a year with no action...can we turn on emulated captions for IE11 by default until this is resolved?

**Comment by EZWrighter** [comment] 2015-04-24 16:27
Until this is fixed, here is my workaround:  Detect IE11 via Tim Downs short script here: http://stackoverflow.com/questions/10964966/detect-ie-version-prior-to-v9-in-javascript

If IE11 then setup the config to emulate tracks in html5 tech:
`var config = { html5 : {
  nativeCaptions : false, 
  nativeTextTracks : false 
} }`

This only is necessary for cross domain tracks.  Seems to work so far.  Any better ideas?

**Comment by EZWrighter** [comment] 2015-04-24 16:53
Woops, I actually changed up my Detect IE11 code to use the answer here: http://stackoverflow.com/questions/19999388/jquery-check-if-user-is-using-ie/21712356#21712356

Didn't realize the Tim Down answer was only for versions less than IE9.

**Comment by gkatsev** [comment] 2015-04-24 17:08
You only need to set either `nativeCaptions` or `nativeTextTracks`, they're synonyms.

**Comment by Globulopolis** [comment] 2015-04-25 06:21
Hm... I tested chapters and subtitles again with the 4.12.5 and all seems to be ok. So issue can be close.

**Comment by EZWrighter** [comment] 2015-04-27 16:13
I will open a separate IE11 CORS ticket and reference this one.

**Comment by mmcc** [comment] 2015-06-15 01:35
Woops, missed @Globulopolis last comment on this one. Closing this.

**Closed by mmcc** 2015-06-15 01:35 UTC
Labels: bug, confirmed, needs: addressing, needs: reduced test case, unclaimed
