### ISSUE TITLE
videojs5 doesn't retry a request on failed HLS segment

### ISSUE THREAD

**Issue by arikkrol1** [videojs/video.js#2951] opened 2015-12-28 09:53 UTC
If a requests to an HLS .ts segment fails the player doesn't try to fetch it again.
To tests this I interfered with the XHR of the first segment and caused it to fail. The player didn't recover.
Previous versions of videojs did recover.

**Comment by hartman** [comment] 2015-12-28 11:52
This seems like an error that should be reported with videojs/videojs-contrib-hls plugin...

**Comment by gkatsev** [comment] 2015-12-28 17:10
Closing as a dupe of https://github.com/videojs/videojs-contrib-ads/issues/139

**Closed by gkatsev** 2015-12-28 17:10 UTC
