### ISSUE TITLE
videojs is not a function

### ISSUE THREAD

**Issue by Globulopolis** [videojs/video.js#2822] opened 2015-11-17 19:28 UTC
Hi!
I cannot understand that's happening with the videojs player. JS throw an error
> TypeError: videojs is not a function
var player = videojs(mediaEl);
on line 11209 http://vjs.zencdn.net/5.0/video.js

But sometimes it's working, sometimes no.
FF 42, VJS 5.2.1

**Comment by gkatsev** [comment] 2015-11-17 19:37
I believe this is a duplicate of #2386.

**Closed by gkatsev** 2015-11-17 19:37 UTC
