### ISSUE TITLE
Why not updating the play-progress-bar when seeking with mouse ?

### ISSUE THREAD

**Issue by zcoding** [videojs/video.js#4464] opened 2017-07-04 09:49 UTC
## Description
The play-progress-bar not updating when i seek current time with my mouse, it looks wierd.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. init an instance
2. load and play a video
3. seek with a mouse

### Expected
I expected to see the vjs-play-progress update to the mouse's position

### Actual
no, it did not update until mouse up

### Error output
no error

**Comment by Spartanace1024** [comment] 2017-12-04 15:43
I had the same exact same issue. Turns out the problem had something to do with not showing "remainingTimeDisplay" in controls.

Example below

```
 // This will update the progress bar on mouse drag
  var player = videojs("my_video_1", {
      controls:true,
      fluid: true,
      autoplay: false,
      controlBar: {
        children: [
          "currentTimeDisplay",
          "timeDivider",
          "durationDisplay",
          "progressControl",
          "fullscreenToggle",
          "remainingTimeDisplay" //ensure we show the remaining time display here
        ]
      }
    })
```

```
  //This will not update the progress bar on mouse drag
  var player = videojs("my_video_1", {
      controls:true,
      fluid: true,
      autoplay: false,
      // Notice no remaining time display in children list
      controlBar: {
        children: [
          "currentTimeDisplay",
          "timeDivider",
          "durationDisplay",
          "progressControl",
          "fullscreenToggle"        
         ]
      }
    })
```

**Workaround**
Ensure the remaining time display is shown via options and use css below.

```
  /* Hide remaining time display here due to bug */
  .vjs-remaining-time {
    display: none;
  }
```

**Comment by gkatsev** [comment] 2017-12-04 20:02
As mentioned in a few other issues around this, it's because of how the seeking infrastructure is built in video.js where the play progress is set up to follow exactly what's happening in the player. https://github.com/videojs/video.js/issues/4460#issuecomment-313002033 for example. Closing as a dupe of that one.

**Closed by gkatsev** 2017-12-04 20:02 UTC
