### ISSUE TITLE
Win7 IE not playing video

### ISSUE THREAD

**Issue by rendermouse** [videojs/video.js#2301] opened 2015-07-02 16:26 UTC
I've seen two different GitHub issues reporting videojs not working on Win7 IE11. Both tickets were closed.

Yet I get the same video error, on IE11, 10 and 9:

"VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported. [object Object]"

![image](https://cloud.githubusercontent.com/assets/1102555/8482060/0aff3c8e-20b5-11e5-8bfa-4897bd5d03ea.png)

I have a Windows7 machine. My browserstack instance of Win7 also fails IE11 the exact same way on videojs.com.  
![image](https://cloud.githubusercontent.com/assets/1102555/8482180/e465b976-20b5-11e5-920a-8d7f15be4482.png)

I also have Flash Player 18,0,0,194 installed.

Strangely, a coworker has Win7, and his IE works fine on videojs.com. I cannot find the reason why.

Past tickets about this were closed, but this issue seems to still be relevant.

**Comment by mmcc** [comment] 2015-07-02 16:42
Mind referencing these other tickets that seem relevant? There are a few I saw related to Windows 7 issues that were vague and the OP never followed up, so if you have others that seem relevant it'd be nice to associate them.

Do you have Windows Media installed? That's the common thread across all the legitimate windows playback issues (particularly folks in the EU because of the anti-trust version Windows 7N or whatever). The gist is that the browser reports that it can play back HTML5 video, then can't because it doesn't actually have the codecs installed. FWIW, I'm in the same boat as your coworker, all copies of Windows 7 that I have access to are working fine, so this is a fun one to debug.

Browserstack is notoriously bad at testing video-related issues, so I wouldn't really take failures there into account. We lump that with testing in IE8 compatibility mode.

**Comment by rendermouse** [comment] 2015-07-02 16:56
https://github.com/videojs/video.js/issues/1097
https://github.com/videojs/video.js/issues/1973
https://github.com/videojs/video.js/issues/1021
https://github.com/videojs/video.js/issues/1469

Browserstack plays videojs just fine from the Win8 VM. Just not in Win7.

I do have Windows Media Player installed, although I never use it. 
![image](https://cloud.githubusercontent.com/assets/1102555/8482674/215b0f4a-20b9-11e5-9939-b3f4964e1b2c.png)

**Comment by rendermouse** [comment] 2015-07-02 17:00
Apparently my coworker has a newer version of IE, version 11.0.9600.17420CO. Mine is 17280CO. I do not have admin rights to upgrade this on my machine.

**Comment by mmcc** [comment] 2015-07-02 17:04
Yeah, this is a really tough one to actually debug. #1469 and #1973, for instance, are Browserstack-specific but worked fine in an actual VM. #1021 and #1097, however, seem to be pretty relevant to your issue. Does [this example](http://output.jsbin.com/buxora) work for you?

**Comment by rendermouse** [comment] 2015-07-02 17:12
Regretfully, that example fails in the same way.

![image](https://cloud.githubusercontent.com/assets/1102555/8483066/efd356fa-20bb-11e5-819f-e4f12e4cd3d3.png)

**Comment by mmcc** [comment] 2015-07-02 17:25
Drats, I was curious if the [`preload` comment](https://github.com/videojs/video.js/issues/1021#issuecomment-45904724) might make a difference for you.

To be honest, this seems like it's slipping into can't / won't fix territory, especially given how difficult this seems to be to reproduce. IE11 is theoretically supposed to be evergreen and it seems that newer versions aren't having this issue, so I don't know if we can spend the time it would take to debug and fix this.

**Comment by rendermouse** [comment] 2015-07-02 18:12
I did a full reboot (normally I just hibernate my system), and videos are now **working**.  Sigh.

We get updates pushed to our systems via corporate policy, so I don't know what might be different after this latest reboot. IE and Media Player versions are exactly the same as before.

Anyway, thank you for your incredibly quick response, and I apologize if this turned into nothing but an unproductive distraction.

![image](https://cloud.githubusercontent.com/assets/1102555/8484188/40d01be4-20c4-11e5-8a9e-afe8b03517a1.png)

**Comment by mmcc** [comment] 2015-07-02 18:26
(╯°□°）╯︵ ┻━┻ 

Oh, computers. Glad I could uh...help? :)

**Closed by mmcc** 2015-07-02 18:26 UTC
Labels: browser bug, needs: more info

**Comment by graywithanA** [comment] 2015-10-23 20:52
For what it's worth, I too am having this issue on Win7 IE11 (11.0.9600.17843).
