### ISSUE TITLE
Seeking to negative values

### ISSUE THREAD

**Issue by MekliCZ** [videojs/video.js#4501] opened 2017-07-18 16:17 UTC
## Description
There is possibility to seek to negative time using player.currentTime(), which causes weird behaviour of the player.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Seek to negative value using currentTime() function

### Expected
It shouldn't be possible to seek to negative time (my opinion is that it would be best to just seek to 0 if negative number was used as a parameter of currentTime())

### Actual
In combination with hls.js, player behaviour is weird - it seeks to end of the video

## Additional Information
Please include any additional information necessary here. Including the following:
### plugins
videojs-hls.js (integration of hls.js to video.js)

**Comment by gkatsev** [comment] 2017-08-16 19:55
Video.js itself seems to handle seeking to a negative number just fine. It could be an issue with hls.js or the its integration with video.js.

**Comment by MekliCZ** [comment] 2017-08-16 19:58
But even if seeking to negative values works with pure HTML5 video element, there is a lot of libraries using MSE which can be broken by seeking to negative values. Not only hls.js.

**Comment by gkatsev** [comment] 2017-08-16 20:03
True, we can potentially make it better but it won't solve the root cause that the MSE libs aren't handling it correctly :).
Best case, this should be fixed in both places.

**Comment by MekliCZ** [comment] 2017-08-16 20:04
+1 for fixing it both in video.js and MSE libs :)

**Comment by gkatsev** [comment] 2017-12-04 20:06
Making this a "help wanted" "first timers only" issue.
The fix is pretty easy, it just needs to clamp the negative value to 0 in `player.currentTime()`. Basically, inside of [this if statement](https://github.com/videojs/video.js/blob/master/src/js/player.js#L1791), if `seconds` are less than 0, we should set them to zero.
Please comment here if you'd like to work on it so multiple people don't work on it at once.

**Closed** 2017-12-11 21:25 UTC
Labels: first-timers-only, help wanted
