### ISSUE TITLE
"default" attribute for text tracks not work

### ISSUE THREAD

**Issue by d4d4k** [videojs/video.js#1884] opened 2015-02-20 17:27 UTC
In 4.12.0 (and 4.12.1), default text track feature is not available. Subtitles (or captions) always off when the player is loaded.

**Comment by heff** [comment] 2015-02-23 21:58
@gkatsev can you confirm this?

**Comment by gkatsev** [comment] 2015-02-23 22:06
Very possible because we disable tracks on loadstart. Probably want to check that `default` attribute isn't ste.

**Comment by heff** [comment] 2015-02-23 22:15
@gkatsev can i assign this one to you then?

**Comment by gkatsev** [comment] 2015-02-23 22:20
What would we want the expected behavior to be?
Should `default` tracks be given to the browser to display and all other tracks be disabled?

But yes, I can assign myself.

**Comment by heff** [comment] 2015-02-23 22:41
If by 'given to the browser' you mean just don't disable them on loadstart, that sounds good to me.

**Comment by gkatsev** [comment] 2015-02-23 22:49
Yep, that's it

**Closed** 2015-02-27 00:55 UTC
Labels: bug

**Comment by brahiansoto** [comment] 2015-12-01 11:52
Subtitles default does not work
