### ISSUE TITLE
100% width and height not working

### ISSUE THREAD

**Issue by nik0s100** [videojs/video.js#2455] opened 2015-08-10 16:55 UTC
I was using version 4.11 subtitles and full 100% width and height was working fine but I like more can please someone help me to make subtitles and 100% width and height the player...also add a new caption setting so users can upload their own subtitles...I am using the latest version..

**Comment by mmcc** [comment] 2015-08-10 17:17
Allowing users to upload their own settings sounds like a great plugin idea, but we won't be adding that to core. If you decide to build it, let us know!

Re: the 100% height and width for subtitles, I think I would need to see an example of what you're trying to achieve. In my head, it sounds like you want to cover your entire video with your subtitles, which I can't imagine is the case.

Closing this since this is a question, not a bug, but feel free to continue the conversation in the comments.

**Closed by mmcc** 2015-08-10 17:17 UTC

**Comment by nik0s100** [comment] 2015-08-11 10:20
I just want to make the video with 100% height and width not the subtitles thats what I mean
<video id='video' class='video-js vjs-default-skin' controls preload='auto' width='100%' height='100%' poster='poster' data-setup='{}'>
but its not working with the newest latest version...

**Comment by mmcc** [comment] 2015-08-11 21:33
Ah ok, misunderstood the question. The best way to do this in 4.x is to specify height and width as auto in the player, then set `padding-top` to the desired ratio.

In 5.0 (master), we've improved the story around [fluid width](1952) pretty drastically.
