### ISSUE TITLE
Video Overlay and Controls are not getting removed when changing quality:

### ISSUE THREAD

**Issue by bhargavavarma** [videojs/video.js#7313] opened 2021-07-08 05:40 UTC
## Description
When changing quality using `videojs-http-source-selector`, the overlay and control bar components are not getting removed.
As per our observation, `listenForUserActivity_` is not getting called sometimes, but the video is playing in the background.
You can check this out in [this](https://codesandbox.io/s/pztxb?file=/index.js) codesandbox link

You can check this in the video attached [here](https://drive.google.com/file/d/1WLFmM7FcSsV8sDp1eBQ8Bh7500JiQcZq/view?usp=sharing) too

## Steps to reproduce
1. Change the video quality and keep the mouse pointer on the video itself.
2. Try to repeat step-1, 2-3 times to reproduce the issue.

### Expected
The controls should be removed after some time automatically.

### Actual
The controls are not getting removed and are staying infinitely until reload.

#### browsers
Chrome 90
#### OSes
Linux and MAC
### plugins
videojs-contrib-quality-levels 2.1.0
videojs-http-source-selector 1.1.6

**Comment by mister-ben** [comment] 2021-07-08 11:21
Hm, I could reproduce that on the captions menu on your sample too.

**Comment by gkatsev** [comment] 2021-07-08 15:05
I can reproduce it when I click on the menu button, but not when I just hover to select a choice. Probably something funky related to lock showing.

**Comment by gkatsev** [comment] 2021-07-08 15:23
Also, I did notice that the codesandbox is depending on `videojs` rather than our package name `video.js`. Though, getting a newer version doesn't seem to help.
Interestingly, I cannot reproduce via https://videojs-preview.netlify.app/sandbox/index.html, on https://videojs-http-streaming.netlify.app/, I cannot reproduce via the captions menu, but I can via the http-source-selector menu. My guess is that it's something related to that plugin, because until I cause it to happen with the source selector, everything seems to be working fine.

**Comment by Ridham177** [comment] 2021-08-01 18:21
@gkatsev When you reproduce the issue using http-source-selector menu, do you use [vod.dev](https://vod.dev/)? I am able to recreate the issue in the given sandbox but not on the aforementioned site which is a demo for http-source-selector.

**Comment by Ridham177** [comment] 2021-08-01 20:53
This may be primitive information to mention but `player.userActive()` always returns true after recreating the bug. Should we be explicitly setting state to false? This is my first time working with video.js library and my second OSS issue so any directions are much appreciated.

**Comment by gkatsev** [comment] 2021-08-02 16:38
I was testing with https://videojs-http-streaming.netlify.app/.
I can't reproduce on vod.dev. Don't really know what the difference is.

I just took another look and I noticed that the element that contains the menu and the menu button maintains its `vjs-hover` class. This only happens with this plugin. I'm not really sure why. When it fails, the class sticks around, but it doesn't seem to happen every single time.
This is what happens when it should've been hidden and be inactive
![image](https://user-images.githubusercontent.com/535884/127894970-3ac539db-de91-4176-a955-0af4d1a3181b.png)

**Comment by Ridham177** [comment] 2021-08-02 19:23
You are right. The class sticks around. If I hover over the quality selector button (after observing that the vjs-hover class stays) and I move my mouse away from the quality selector button, the vjs-hover class is removed. However, the overlay still stays, so I don't think the issue can be fixed by fixing the behavior of the vjs-hover class. Here is a [video](https://www.youtube.com/watch?v=pkCX81541LE) of that. I'll keep investigating the events that occur.

**Comment by Ridham177** [comment] 2021-08-02 20:18
`
_proto.listenForUserActivity_ = function listenForUserActivity_() {
      
      var mouseInProgress;
      var lastMoveX;
      var lastMoveY;
      var handleActivity = bind(this, this.reportUserActivity);

      var handleMouseMove = function handleMouseMove(e) {
        // #1068 - Prevent mousemove spamming
        // Chrome Bug: https://code.google.com/p/chromium/issues/detail?id=366970
        if (e.screenX !== lastMoveX || e.screenY !== lastMoveY) {
          lastMoveX = e.screenX;
          lastMoveY = e.screenY;
          handleActivity();
        }
      };

      var handleMouseDown = function handleMouseDown() {
        handleActivity(); // For as long as the they are touching the device or have their mouse down,
        // we consider them active even if they're not moving their finger or mouse.
        // So we want to continue to update that they are active

        this.clearInterval(mouseInProgress); // Setting userActivity=true now and setting the interval to the same time
        // as the activityCheck interval (250) should ensure we never miss the
        // next activityCheck

        mouseInProgress = this.setInterval(handleActivity, 250);
      };

      var handleMouseUpAndMouseLeave = function handleMouseUpAndMouseLeave(event) {
        handleActivity(); // Stop the interval that maintains activity if the mouse/touch is down

        this.clearInterval(mouseInProgress);
      }; // Any mouse movement will be considered user activity


      this.on('mousedown', handleMouseDown);
      this.on('mousemove', handleMouseMove);
      this.on('mouseup', handleMouseUpAndMouseLeave);
      this.on('mouseleave', handleMouseUpAndMouseLeave);
      var controlBar = this.getChild('controlBar'); // Fixes bug on Android & iOS where when tapping progressBar (when control bar is displayed)
      // controlBar would no longer be hidden by default timeout.

      if (controlBar && !IS_IOS && !IS_ANDROID) {
        controlBar.on('mouseenter', function (event) {
          this.player().cache_.inactivityTimeout = this.player().options_.inactivityTimeout;
          this.player().options_.inactivityTimeout = 0;
        });
        controlBar.on('mouseleave', function (event) {
          this.player().options_.inactivityTimeout = this.player().cache_.inactivityTimeout;
        });
      } // Listen for keyboard navigation
      // Shouldn't need to use inProgress interval because of key repeat


      this.on('keydown', handleActivity);
      this.on('keyup', handleActivity); // Run an interval every 250 milliseconds instead of stuffing everything into
      // the mousemove/touchmove function itself, to prevent performance degradation.
      // `this.reportUserActivity` simply sets this.userActivity_ to true, which
      // then gets picked up by this loop
      // http://ejohn.org/blog/learning-from-twitter/

      var inactivityTimeout;
      this.setInterval(function () {
        // Check to see if mouse/touch activity has happened
        if (!this.userActivity_) {
          return;
        } // Reset the activity tracker


        this.userActivity_ = false; // If the user state was inactive, set the state to active

        this.userActive(true); // Clear any existing inactivity timeout to start the timer over

        this.clearTimeout(inactivityTimeout);
        var timeout = this.options_.inactivityTimeout;

        if (timeout <= 0) {
          return;
        } // In <timeout> milliseconds, if no more activity has occurred the
        // user will be considered inactive


        inactivityTimeout = this.setTimeout(function () {
          // Protect against the case where the inactivityTimeout can trigger just
          // before the next user activity is picked up by the activity check loop
          // causing a flicker
          if (!this.userActivity_) {
            this.userActive(false);
          }
        }, timeout);
      }, 250);
    }

It seems that inactivityTimeout is set to 0 and so userActive is never set to false because it just returns. I believe this happens because options_.inactivityTimeout is set to 0 (near `if (controlBar && !IS_IOS && !IS_ANDROID)`). Later on, when the value is supposed to be set to 2000 because of a `this.player().options_.inactivityTimeout = this.player().cache_.inactivityTimeout;` mouseleave event, that never happens. When this code is run again, this.player.cache_.inactivityTimeout is set to 0. so it never recovers. I don't know why mouseleave event is never fired.

I think I am looking in the wrong place so please let me know if I am in the correct place to find the bug or not.

**Comment by Ridham177** [comment] 2021-08-02 20:58
The overlay goes to hidden state if I manually set this.player().options_.inactivityTimeout = 2000 and this.player().cache_.inactivityTimeout = 2000.

**Comment by KVPasupuleti** [comment] 2021-08-04 06:41
> It seems that inactivityTimeout is set to 0 and so userActive is never set to false because it just returns. I believe this happens because options_.inactivityTimeout is set to 0 (near if (controlBar && !IS_IOS && !IS_ANDROID)). Later on, when the value is supposed to be set to 2000 because of a this.player().options_.inactivityTimeout = this.player().cache_.inactivityTimeout; mouseleave event, that never happens. When this code is run again, this.player.cache_.inactivityTimeout is set to 0. so it never recovers. I don't know why mouseleave event is never fired.

@Ridham177 yeah, I too identified the same thing. On the control bar, the expectation is that the `mouseenter` and `mouseleave` events should be happening alternately. 

But, when the quality is changed, a `mouseleave` event is getting skipped sometimes and the `mouseenter` event is getting called again.

This is why the cache is also setting to 0 and the timeout is not getting recovered.  

_____

As @gkatsev said, I too assumed the problem is because of the `vjs-hover` class that is sticking around. I specifically observed this sticking around behavior when we clicked a higher quality level option for rendition switching and the video is in buffering state for a while before it gets played.

 So, I listened to the `waiting` event and removed the `vjs-hover` class on that element assuming it would fix the problem. 
 
 But, as you said, it didn't fix.
 
 _____
 
 I even tried to stop the bubbling through `event.stopPropagation` thinking that something might be re-triggering the `mouseenter` event somewhere up in the DOM tree. But, this didn't solve the problem.
 
 I too will be investigating this until we find the culprit that's causing this behavior.

**Comment by Ridham177** [comment] 2021-08-05 17:55
@mister-ben @gkatsev I am unable to recreate the bug using the captions menu. Could you write directions or publish a video? @KVPasupuleti Thank You for investingating this. @bhargavavarma Are we sure that the issue is with video.js and not videojs-http-source-selector or its dependency?

**Comment by bhargavavarma** [comment] 2021-08-09 04:14
@Ridham177 

From my knowledge and observation, I guess the issue is with `video.js`. 

As a part of the investigation, I checked the complete code of `videojs-http-source-selector` and I didn't find anything suspicious regarding this. 

 The only concern I have is I found this in the package.json
 
 ```
 "generator-videojs-plugin": {
    "version": "5.2.1"
  },
  .
  .
  .
  "dependencies": {
  .
  .
    "video.js": "^7.0.0",
  .
  .
  },
  ```
  
  The version of `video.js` is a bit old. I don't know if this could affect the behavior. But, adding it as a data point.
  
  I couldn't reproduce the same behavior with the captions menu. 
  
  As @KVPasupuleti said, I suspect the issue is with the skipping of the `mouseleave`, but I couldn't identify the root cause.

**Comment by jgcaruso** [comment] 2021-08-18 19:40
I did things kind of backwards, and created a PR before looking for existing issues.

This fixes this issue for me: https://github.com/videojs/video.js/pull/7383

**Comment by gkatsev** [comment] 2021-08-19 04:35
Thanks, @jgcaruso. Looks like both your plugin and http-source-selector seem to be calling update() on source selection. Makes sense that there would then be a mismatch in events, and why it isn't an issue for the captions menu as an example. The various track buttons only change if a track is added or removed.
Your fix definitely makes sense, though, it's probably worth updating the plugins not to call update as often, since when a Menu updates, it refreshes the entire DOM strucutre of the menu.

**Closed** 2021-08-19 19:33 UTC
