### ISSUE TITLE
5.0.0-rc.90 : Bower SCSS problem

### ISSUE THREAD

**Issue by Sly777** [videojs/video.js#2611] opened 2015-09-17 16:52 UTC
Hey,

In video-js.scss file, It's trying to import "../../node_modules/videojs-font/scss/icons" file but it doesn't create node_modules folder in Bower. When you try to import videojs.scss file to another scss, it doesnt work.

**Comment by heff** [comment] 2015-09-18 17:19
We're still trying to figure out the best way to handle the sass files and understand how they'll be used. What specifically were hoping to use the sass files to do?

**Comment by Sly777** [comment] 2015-09-21 08:23
hey @heff,

Mostly, i'm importing plugin scss files with sass import function (you can see example code below). After that, i'm importing this file to my general scss file. For information, i just import one time.

Example code:
```
/// _thirdParty.scss

// BOOTSTRAP 3 BASE FILES
@import "../../../libraries/bootstrap-sass/assets/stylesheets/bootstrap/variables";
@import "../../../libraries/bootstrap-sass/assets/stylesheets/bootstrap/mixins";

// SETTINGS
$body-bg: $colors-dark-blue-grey;
$text-color: $colors-white;
$grid-columns: 15;
$grid-gutterRight: floor(($grid-gutter-width / 2));
$grid-gutterLeft: ceil(($grid-gutter-width / 2));

// BOOTSTRAP 3 BASE FILES
@import "../../../libraries/bootstrap-sass/assets/stylesheets/bootstrap/normalize";
@import "../../../libraries/bootstrap-sass/assets/stylesheets/bootstrap/print";

@import "../../../libraries/bootstrap-sass/assets/stylesheets/bootstrap/scaffolding";
@import "../../../libraries/bootstrap-sass/assets/stylesheets/bootstrap/type";
@import "../../../libraries/bootstrap-sass/assets/stylesheets/bootstrap/grid";

@import "../../../libraries/bootstrap-sass/assets/stylesheets/bootstrap/utilities";
@import "../../../libraries/bootstrap-sass/assets/stylesheets/bootstrap/responsive-utilities";

// SELECT2 FILES
@import "../../../libraries/select2/src/scss/core";

// VIDEO.JS FILES
//@import "../../../libraries/video.js/src/css/video-js";
```

```
/// main.scss

@import "thirdParty";

/// other codes.....
```

Only problem in this scenario is font files of videojs. If work on the different folders and when you send files to production you do compile or something, you cannot use the font files directly so maybe you can create another repo for that (with bower support). When i work with gulp or grunt, i always copy necessary files to production side with copy function of them.

**Comment by heff** [comment] 2015-09-21 14:59
@mmcc any new thoughts on this?

**Comment by mmcc** [comment] 2015-09-21 20:23
This scenario is why I was leaning towards the idea of outputting the compiled css as just an SCSS file for scenarios like this. The problem is we're basically doing the same thing, but we're expecting to be able to pull from `node_modules` (which would also work with anyone else using npm and not bower). We could copy the font scss over like the font files, but that feels a bit hacky.

**Comment by akshayKrSingh** [comment] 2015-10-12 21:08
Shouldn't the `main` property point to the `dist` folder with compiled *css* rather than the `src` folder with the *scss* file ?

**Comment by gkatsev** [comment] 2015-10-12 21:25
It probably should, since that's what we're doing the styles property of the package.json.

**Comment by arpu** [comment] 2015-10-23 21:51
+1

**Comment by DatTran** [comment] 2015-10-30 15:57
1+

**Comment by mmcc** [comment] 2015-10-30 19:06
No need to continue the +1s, this is confirmed.

**Comment by misteroneill** [comment] 2015-11-13 18:03
Going to also note that this _really_ breaks with npm 3.x because it installs dependencies as siblings instead of as nested `node_modules` directories - meaning the `../../node_modules/videojs-font/scss/icons` path breaks anything that tries to compile an `.scss` file from video.js as a node module.

**Comment by gkatsev** [comment] 2015-11-17 18:38
Closing in favor of #2740 since it has a PR out for it: https://github.com/videojs/video.js/pull/2775

**Closed by gkatsev** 2015-11-17 18:38 UTC
Labels: bug, confirmed
