### ISSUE TITLE
EISDIR issue in bower

### ISSUE THREAD

**Issue by evanczhou** [videojs/video.js#2199] opened 2015-05-25 19:12 UTC
Getting the EISDIR error when I installed with bower and used grunt build.

"Warning: Unable to read "dist/public/bower_components/video.js" file (Error code: EISDIR). Use --force to continue."

I guess it's supposed to be a directory but it thinks it's a js file since it's named video.js. Anyone else getting this issue?

**Comment by mmcc** [comment] 2015-06-03 20:42
What version of Video.js are you getting from Bower? I remember a few issues where folks were getting 5.0 beta releases, but I *think* those were caused by triggering upgrades by hand.

**Comment by evanczhou** [comment] 2015-06-06 19:21
Currently using 4.12.8

**Comment by Ant-keke** [comment] 2015-08-11 18:34
Any news on this issue?

**Comment by gkatsev** [comment] 2015-11-17 22:36
I just tried installing both latest and v4.12.8 of videojs using bower and they both seem to have installed fine with latest version of bower.
Closing, but we can reopen if there's still some issue here.

**Closed by gkatsev** 2015-11-17 22:36 UTC
