### ISSUE TITLE
Mute/unmute volume control should show on iOS

### ISSUE THREAD

**Issue by rudyzeinoun** [videojs/video.js#4478] opened 2017-07-10 21:15 UTC
On iOS, the volume bar is hidden because we cannot control the volume due to an OS restriction. However, the mute/unmute button should still show. This is useful in cases where "autoplay muted playsinline" is used, so the video starts automatically playing, but there would be no way to unmute it, even from the device's hardware volume controls or the OS volume slider.

You can force the controls to display by CSS, by adding:

`.video-js .vjs-volume-panel { display: flex !important }`
`.video-js .vjs-mute-control { display: inline-block !important }`

Which allows unmuting the video, but the experience is not optimal and the volume slider still takes some space until it times out and closes back. This can be fixed by more CSS changes, but these are dirty workarounds.

The expected result is to show the volume icon on iOS to allow mute/unmute.

**Comment by arashilan** [comment] 2017-07-12 03:47
Excuse me, how can video autoplay on iOS?
When set "autoplay muted" in <video>,then the video can autoplay.
When set "autoplay" in <video>,then can't autoplay.

Use video.js in html5 .

**Comment by rudyzeinoun** [comment] 2017-07-12 15:50
If you're on iOS, the volume mute/unmute button is hidden, because iOS doesn't let you control volume using JavaScript.
So if you have `autoplay muted`, there's no way for the user to unmute.

**Comment by misteroneill** [comment] 2017-07-12 17:04
We are currently planning a sweep related to the autoplay/muted/playsinline complexity this quarter. Stay tuned!

> Excuse me, how can video autoplay on iOS?
> When set "autoplay muted" in <video>,then the video can autoplay.
> When set "autoplay" in <video>,then can't autoplay.

Yes, that is the behavior of iOS Safari and Android Chrome. You cannot autoplay non-muted video on those platforms. Safari 11 on macOS will behave the same way.

**Comment by rudyzeinoun** [comment] 2017-07-12 17:12
I would advise having an always-showing unmute button when this mode is on, similar to how Facebook does it.

**Comment by misteroneill** [comment] 2017-07-12 17:14
This looks like a duplicate of #4373

**Comment by potsky** [comment] 2017-10-03 15:09
Agree with @rudyzeinoun, on iOS, the autoplay/muted/playsinline works but I need to use a ugly settimout to remove `vis-hidden` class from volume panel the mute button.

**Comment by cmellinas** [comment] 2018-03-22 16:26
Hi,
any updates on this issue? 
thanks

**Comment by healsgoclues** [comment] 2018-03-28 05:15
Hi,
 I tried to show volume control button.
This code worked on iOS 11 with video.js v6.8.0.
I hope I can be of any help.
Thanks.
```
<video id="video_player" class="video-js vjs-default-skin" controls preload playsinline muted>
    <source src="/path/to/video" type="application/x-mpegURL">
</video>
/* ... */
<script>
var player = videojs('video_player');
player.ready(function() {
    player.on('play', function() {
            player.controlBar.volumePanel.show();
            player.controlBar.volumePanel.volumeControl.show();
            player.controlBar.volumePanel.muteToggle.show();
    });
});
</script>
```

**Comment by gkatsev** [comment] 2018-05-04 21:47
There's a PR for this being worked on by @bcdarius: #5052.

**Comment by prozak915** [comment] 2018-05-15 08:46
Jtel to edit them on phone ?

**Closed** 2018-06-21 18:33 UTC

**Comment by gkatsev** [comment] 2018-06-21 19:49
This should be fixed in master now, a release of 7 is coming soon and it'll be back ported to 6.x at some point as well.

**Comment by MrWiLofDoom** [comment] 2018-08-22 15:35
Is this fixed in 7? I am running 7 and I'm still not seeing the mute button

**Comment by bcdarius** [comment] 2018-08-23 01:55
The mute toggle button is displayed on iOS in v7.1.0+. Is that the version you're testing on? I'm seeing the mute toggle button fine here https://output.jsbin.com/sovubus. Another thing to note is that the mute control will be visible in iOS versions that supports muting volume programmatically only, ie iOS 10+.

**Comment by simeyla** [comment] 2020-05-27 04:24
I'd love to see a `bigUnmuteButton` analogous to `bigPlayButton`
