### ISSUE TITLE
High CPU usage after the player stays in background for a while

### ISSUE THREAD

**Issue by demetrio812** [videojs/video.js#5937] opened 2019-04-15 18:43 UTC
## Description
I've implemented an Audio player with VideoJS and we noticed a very high CPU usage after sustained usage in background.

We did some tests and it happens also with the standard demo: https://videojs.com/advanced/

## Steps to reproduce
1. Open Chrome browser and go to the demo page: https://videojs.com/advanced/
2. Open the DevTools
3. Toggle DeviceToolbar in the window and throttle the CPU to Low-end mobile (this step will make it easier to highlight the problem, but the issue is visible also at full CPU)
4. Start playing and put the window in background for 30 minutes
5. Open the window and try to scroll, the page will not respond for some seconds, the more you keep the player in background the more the seconds, eventually will completely block the page

I was able to profile it on my mac with the following procedure:
1-2-3: as above
4. Detach the DevTools from the Window and put the window with the player in background by clicking the yellow round button in the window top bar to minimise it to the dock
5. You should now only have the DevTools window opened, press Cmd+H to hide the browser completely and wait
6. Show Chrome again but clicking on the Chrome icon, you should now see the DevTools window but not the player window that it's still minimised
7. In the devtools window, go to the performances tab and start recording
8. Maximize the player window and wait until the window start reacting again
9. Stop the profiler in the DevTools window and see the results

You can notice a 100% cpu usage for some seconds until it goes back to normal:

<img width="1588" alt="Screenshot 2019-04-15 19 25 12" src="https://user-images.githubusercontent.com/385644/56156972-4a7e7980-5fb6-11e9-9986-317419fe5897.png">

<img width="1592" alt="Screenshot 2019-04-15 19 25 51" src="https://user-images.githubusercontent.com/385644/56156999-58cc9580-5fb6-11e9-9be7-39acf2247b1d.png">

I've tested on multiple Macs (even very fast ones).

Any suggestions?

Thanks,
Dem

**Comment by gkatsev** [comment] 2019-04-18 14:52
Interesting, I'm a bit surprised that it's happening in more modern browsers as well but we recently fixed a similar bug for IE11 where the tab would just crash due to CPU usage. The fix we implemented isn't IE11 specific, so, it may improve things. It's available in the latest release now.

**Comment by demetrio812** [comment] 2019-04-20 15:48
@gkatsev we tested the 7.5.4 and things improved a bit but it's unusable as an audio player because if users keep it in background for a while and then try to access the page, they would have an non-resposive page using a lot of cpu that potentially will never recover, we didn't notice the same problem in another player we tested, HLS.js

**Comment by 0caspy** [comment] 2019-05-04 21:24
have the same trouble. after a while in background player become totally unresponsible.
7.5.4, no plugins.

ps: very popular case to put tab in background, where speech is interesting with boring video

**Comment by DispatchCommit** [comment] 2019-05-22 06:38
Encountering this issue also, and is even leading to instances of tabs fully crashing eventually.

Is there any workaround or mitigation?

**Comment by meikidd** [comment] 2019-09-20 01:40
Encountering same issue here, bot please don't close this.

**Comment by meikidd** [comment] 2019-10-08 09:57
@demetrio812 
I Found out this issue is caused by the code [here](https://github.com/videojs/video.js/blob/607ed8bea8daab3450d0da184518b4848c894ee9/src/js/control-bar/progress-control/seek-bar.js#L59).

The following code is executed every 30ms, when user leave the current tab, `setInterval` still keeps working. 
```
 this.requestAnimationFrame(() => {
     this.update();
});
```

But `requestAnimationFrame(callback)` queues up the callback function until user back to this tab, so when user come back, there are thousands of callbacks in the queue.

See minimal reproducible code [here](https://github.com/meikidd/videojs-issue-5937) 

It exists in version 7.3.0, newest version doesn't have this issue.

**Comment by andreiucm** [comment] 2019-12-08 10:58
@gkatsev I see the same issue. But my case is worst since I load a table with 100 rows and one of the cells contains the player -> after coming from background my site is almost unusable. And the fan of the CPU goes crazy.

MacBook 15
Catalina

**Comment by tzarebczan** [comment] 2020-04-27 23:17
Any updates on this?

**Comment by DispatchCommit** [comment] 2020-04-28 10:15
I can't recall which version exactly, but I believe this was fixed in one of the 7.6.x builds and re-surfaced in the 7.7.x builds.

I'm on 7.7.5 currently and have the issue. I might try downgrading back to the latest 7.6.x and testing. If my memory is correct and 7.6.x does not have the issue, I suspect that the changes made in 7.7.0 are the cause of the issue due to the above mentioned issue with RAF's being queued in the background. 

If this is the case, I suspect it is because of this particular PR: https://github.com/videojs/video.js/pull/6155
Where a new RAF was added to the codebase at this line: https://github.com/videojs/video.js/pull/6155/files#diff-54c39e8f9281d253e730007a0b8c6f63R75

I'll downgrade to test and report back.

**Comment by DispatchCommit** [comment] 2020-04-28 11:16
Ok after some initial investigation this does appear to be a regression, 7.6.6 does not exhibit this behavior while 7.7.5 *does*.

![image](https://user-images.githubusercontent.com/45262335/80480904-5493c180-8906-11ea-9330-958fa93371a4.png)

@gkatsev @brandonocasey any thoughts?

I've only looked at simple performance comparisons so far, might be worth trying to do a code profile comparison to see which functions are running during that 100% CPU time, but I keep crashing dev tools while waiting for the process to finish.

**Comment by DispatchCommit** [comment] 2020-04-28 11:30
Here's a code profile comparison, v7.7.5 is substantially slower upon tab focus compared to v.7.6.6, and it appears to be related to an anonymous function call that calls functions such as `update`, `getCurrentTime`, `duration`, `seekableEnd`, and `liveWindow` which make me think my previous suspicions are correct.

![image](https://user-images.githubusercontent.com/45262335/80482364-f7e5d600-8908-11ea-8fe9-7c8a08d76f7e.png)

**Comment by DispatchCommit** [comment] 2020-04-28 19:14
I found at least 2 sources for this issue in the current codebase, and have PR'd my changes for fixing both instances.
There may be additional issues hidden elsewhere, but removing the two biggest offending instances has resulted in a *substantial* improvement. With just 1 instance resolved I saw a drop from multiple minutes to complete in extreme cases to just around 10 seconds of lockup. After performance profiling on the 10 second lockups and resolving the second occurrence, I'm seeing instantaneous response.

I'm not sure I'm completely satisfied just yet, but I'm going to need to wait much longer periods in order to find other instances.

**Comment by gkatsev** [comment] 2020-04-30 14:29
Thanks for the investigation and PR @DispatchCommit! It does sound right that we don't want to double up multiple rAFs.
We really appreciate your help.

**Closed** 2020-06-19 18:51 UTC
Labels: confirmed

**Comment by DispatchCommit** [comment] 2020-07-10 02:13
:( I'm not sure this is fully resolved yet @gkatsev 
I just switched from my custom build of video.js back to 7.8.4 and I'm still seeing substantial issues with RAF calls. 

![image](https://user-images.githubusercontent.com/45262335/87108697-bf6f4c00-c217-11ea-8148-d59d2c08ba65.png)

v7.8.4
![image](https://user-images.githubusercontent.com/45262335/87108913-3573b300-c218-11ea-88fd-951b0337fb46.png)


I can investigate the source(s) of RAF leaks and work on further improvements, should this issue be re-opened or would it be better to start a new issue to document findings?

**Comment by gkatsev** [comment] 2020-07-10 02:15
7.8.4 doesn't contain the rAF fix yet. Going to be releasing Video.js 7.9 tomorrow which will include that change.

**Comment by DispatchCommit** [comment] 2020-07-10 02:18
Well I'm glad my testing is at least consistent then haha!
My mistake, sorry about that, I jumped the gun there as are a few fixes that I'm hoping to benefit from this next update! looking forward to the release, and will update if any additional issues show up.
Thanks for the hard work 😄

**Comment by gkatsev** [comment] 2020-07-10 16:40
It's out now as `next` on npm

**Comment by DispatchCommit** [comment] 2020-07-10 23:00
You are amazing, thank's the quick work, I am eager to get this new player on our site and to have finally eliminated two of the most annoying issues that we've been facing for far too long in some capacity or another.
Glad to finally see this resolved 🙏

**Comment by gkatsev** [comment] 2020-07-10 23:04
Thank you for tracking down the issue!
