### ISSUE TITLE
Custom buttons don't respond to touch gestures when controls are hidden

### ISSUE THREAD

**Issue by Soviut** [videojs/video.js#3001] opened 2016-01-14 03:57 UTC
I've created an annotation plugin who's components extend the built in Button component. The problem is that on touch devices, when the controls are hidden, these annotations remain visible but become unresponsive to touch.

Is there any particular way I can handle this without keeping the controls visible all the time?

**Comment by gkatsev** [comment] 2016-01-14 04:20
Are you adding your component to the control bar? Or to the player itself?
Would you happen to have, or can you make, a reduced test case on jsfiddle or similar website?

**Comment by Soviut** [comment] 2016-01-14 05:11
I'm adding my components to the player itself.

I'll see about building a reduced case once I've got permission from my client.

**Comment by mmcc** [comment] 2016-01-17 01:11
Isn't this expected behavior? If the control bar is hidden, you can't still use the buttons on it, and it would be incredibly confusing if you could. My thought is to add the listeners you need to the tech itself and take control visibility out of the picture altogether. This is (very vaguely) how the [click-to-play/pause](https://github.com/videojs/video.js/blob/master/src/js/player.js#L940-L961) on the player itself works.

Closing this since it's a pretty specific implementation question, but we can continue the conversation in the comments.

**Closed by mmcc** 2016-01-17 01:11 UTC

**Comment by Soviut** [comment] 2016-01-17 07:36
The buttons are on the rest of the player; clickable annotation overlays,
related videos grid, etc.

**Comment by mmcc** [comment] 2016-01-18 02:43
I hate to continue to harp on this, but trying to debug without reduced test cases is like feeling around in the dark while someone tells you vague instructions out loud. We can revisit this once you've got a reduced test case ready.

**Comment by Soviut** [comment] 2016-01-18 02:45
Fair enough, I'll work on getting a test case together asap. I was just trying to explain the use case where on screen buttons would need to continue to receive touch events even when the controls are hidden.

**Comment by mmcc** [comment] 2016-01-18 02:53
I think I follow what you mean now, but my gut instinct is those are a different use case from "controls" in the current sense (i.e. `playButton`). Might be that we need a different higher level class to encompass this kind of control, but again, something to play with makes this whole thing easier. Thanks for understanding!

**Comment by Soviut** [comment] 2016-01-18 02:56
Yeah, that's what I was wondering too. Perhaps some sort of option on components that says whether or not the should be disabled when control mode is enabled, or not.

I'll do my best to get that example up ASAP.
