### ISSUE TITLE
addRemoteTextTrack causes player freeze

### ISSUE THREAD

**Issue by bryfry** [videojs/video.js#1988] opened 2015-03-30 02:12 UTC
The addRemoteTextTrack function causes the player and js execution to grind to a halt if the text track of that type already exists.  I expected the text track to overwrite without having to remove the existing one.  As a mitigation I'm working on some wrapper code to call removeRemoteTextTrack before adding a new one, but the observed behavior seemed repeatable and not intuitive.

**Comment by gkatsev** [comment] 2015-03-30 02:23
Can you provide a reduced test case?
Adding the same remote text track again shouldn't overwrite existing tracks.
Also, this is possibly related to #1913 but if you're only loading in one file, I don't see why it should lock up.

**Comment by bryfry** [comment] 2015-03-30 02:35
Is there an existing test player+page that I should try to demonstrate the issue with?

**Comment by ksheurs** [comment] 2015-04-02 00:12
@gkatsev @bryfry i made an example here: http://jsbin.com/nihijepuwi/1/. Whether in Chrome or Firefox, it freezes up my browser and js/player execution while it pre-loads all the tracks.

Is there a way to move emulated text tracks to a lazy loaded approach (load per selection)? If not, is there a way emulated text tracks can be powered more like the previous videojs version? This didn't previously happen.

**Comment by ksheurs** [comment] 2015-04-09 20:22
@gkatsev are you able to reproduce this issue? we are close to rolling out our new player powered by videojs, but we are stuck on Flash/emulated tracks locking up. My only idea for moving forward is figure out a way to disable emulated tracks?

**Comment by gkatsev** [comment] 2015-04-09 20:49
Yep, I can reproduce using the jsbin above.
Looks like this only happens with the videojs file that includes vttjs in it. If you use the `novtt` file and include `vtt.js` yourself, it seems to be working fine, mostly: http://jsbin.com/defibihija/1/edit?html,css

**Comment by heff** [comment] 2015-04-09 20:55
Why would that be?

**Comment by gkatsev** [comment] 2015-04-09 20:57
No idea. Maybe because if it isn't available immediately, it delays the execution for a bit?

**Comment by ksheurs** [comment] 2015-04-10 13:54
Thanks for looking into it @gkatsev.

So yes, this does prevent the locking, but seems to break tracks all together. This first exception is on load and the subsequent ones are each time I try to select a language in the player: http://cl.ly/image/103O1S1U262M

Hope we are onto something!

**Comment by ksheurs** [comment] 2015-04-28 13:21
@gkatsev @heff any ideas here? it seems if i include vttjs with videojs the browser freezes for about ~10seconds before playing and allowing tracks to work. when using novtt (and including vttjs separately) the freezing goes away, but tracks don't work. is it likely a fix will happen for this or is focus fully on v5?

if not, do you recommend any other subtitle/caption libraries that can be used with videojs? http://captionatorjs.com?

thank you again!

**Comment by ksheurs** [comment] 2015-04-28 13:33
By the way, if helpful, these are the JS errors I see on the demo you provided when including vttjs separately - http://cl.ly/image/3j3j2p1K0a3X

**Comment by gkatsev** [comment] 2015-05-22 15:34
I'm closing this issue as a duplicate of #1913

**Closed by gkatsev** 2015-05-22 15:34 UTC
