### ISSUE TITLE
Videojs progress leaps

### ISSUE THREAD

**Issue by eugen0329** [videojs/video.js#3902] opened 2016-12-30 14:47 UTC
## Description

Videojs progress bar upon rewinding doesn't go back with a single mouse click.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open http://videojs.com/. Click big play button.
2. Rewind to the middle of the video
3. Click in the beginning of the progress bar.

### Expected
Video is rewinded to the beginning with a single click.

### Actual
You need to click twice to do that.

#### OSes
Chrome 55, OSX Sierra
Chromium Version 55.0.2883.87, Ubuntu 16.04 (64-bit)

**Comment by ImNatho** [comment] 2016-12-30 15:03
Yeah, I also have reproduced this issue. But the video still played from the point you select, just the progress bar stays where it was until you catch up to that point again.

Windows 10 - Chrome 55

**Comment by gkatsev** [comment] 2016-12-30 15:56
This is a duplicate of https://github.com/videojs/video.js/issues/3839 which has been fixes in 5.15.

**Closed by gkatsev** 2016-12-30 15:56 UTC

**Comment by eugen0329** [comment] 2017-01-03 13:45
Everything works fine, thanks!
