### ISSUE TITLE
IE crash with 11 players on one page

### ISSUE THREAD

**Issue by cowanmax** [videojs/video.js#2961] opened 2016-01-01 13:50 UTC
Hi All and Happy New Year !
I have created 11 players on one page and IE each time drops. Firefox 47 works well.
Look at this page - nightbus.ru/testvideo.html
Have any ideas to fix it?

**Comment by mmcc** [comment] 2016-01-01 19:30
Have you tested to see what happens with just vanilla video elements (VJS not initialized on them)? Curious to see if IE still has issues or not.

**Comment by gkatsev** [comment] 2016-01-01 20:00
Also, what version of IE?

**Comment by cowanmax** [comment] 2016-01-03 20:31
IE 11 
W7 x64

**Comment by mister-ben** [comment] 2016-01-04 11:06
Given the videos are HLS I suspect the issue is IE having limited local storage for xhr requests. Try adding `preload="none"` to each video element so nothing is preloaded.

**Comment by gkatsev** [comment] 2016-01-04 15:13
Can you open a corresponding issue against the [videojs-contrib-hls project](https://github.com/videojs/videojs-contrib-hls/issues/new)?

**Comment by cowanmax** [comment] 2016-01-04 16:38
mister-ben, thanks, problem was fixed !
gkatsev, yes sure !

But problem with little stops is stays. When you watch video in Firefox 47 or Chrome there is a little stops after 2-3 ts segments. But in IE there is no problem. The same problem - https://github.com/videojs/videojs-contrib-hls/issues/482

**Comment by gkatsev** [comment] 2016-01-04 18:43
Closing this one to move the rest of the discussion to: https://github.com/videojs/videojs-contrib-hls/issues/496
Thanks.

**Closed by gkatsev** 2016-01-04 18:43 UTC
