### ISSUE TITLE
Fullscreen mode is not working for dynamically loaded videos.

### ISSUE THREAD

**Issue by mawenmaywin** [videojs/video.js#4739] opened 2017-11-12 06:35 UTC
Whenever a new video is loaded dynamically onto the page, fullscreen mode doesn't work for the loaded video(s).

1. Initialize videojs using a nodelist object array with getelementsbyclassname
2. Load one video on page load and then load another video dynamically 
3. Try to enter fullscreen for the dynamically loaded video.

The window enters fullscreen mode but instead of showing the video the entire screen turns black.

The screen is black when fullscreen is enabled.

This is the code I used to initialize the plugin.
```
function load_video_js_plugin() {
    videojs.options.flash.swf = site_url+"plugins/video-js/video-js.swf";
    video_js_class_array = document.getElementsByClassName("video_js_class");
    var video_js_class_array_count;/* this variable is used to count the array of video-js classes */
    for(video_js_class_array_count = 0; video_js_class_array_count < video_js_class_array.length; ++video_js_class_array_count) {/* for every video-js class in the loop do this */
        var video = videojs(video_js_class_array[video_js_class_array_count], {}, function() {
            this.progressTips(); // "load the plugin, no options!"
            this.thumbnails({
                0: {
                    src: site_url+"content/pictures/layout/anon/anonymousAvatar5.png",
                    width: '120px'
                }, 5: {
                    src: site_url+"content/pictures/layout/anon/anonymousAvatar5.png"
                }
            });/* for video thumbnails */
            fluid: true
        });
    }
}
```

**Comment by mister-ben** [comment] 2017-11-16 22:15
There's nothing obvious from your snippet that would cause this. Perhaps a link to a simple example page that reproduces the issue would help.

**Comment by Asone** [comment] 2017-11-20 14:19
i had a blackscreen issue too - specificaly on Firefox quantum -  independant of whichever version i used. 

Turned out that it was an old "preserve-3d" present in the CSS files that was applying for some element containing the video. 

Removing the property removed the problem. 

Maybe check if there's any CSS property that could be the problem ? 

Hope it helps.

**Comment by gkatsev** [comment] 2017-11-30 18:58
Unfortunately, without more information, we cannot provide more help. The snippet provided doesn't show enough for us to be able to diagnose the issue. Maybe @Asone's comment will help.
I'm closing this issue because there haven't been an update in 2 weeks but if we get more information, we'd be happy to continue chatting here and re-opening the issue if necessary.

**Closed by gkatsev** 2017-11-30 18:58 UTC
