### ISSUE TITLE
Call to Video File gets stalled

### ISSUE THREAD

**Issue by venkatas** [videojs/video.js#4249] opened 2017-03-31 05:46 UTC
## Description
In some cases video does not load and when checked the developer tools it was found the call the video file failed because it stalled

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
5.6.10 videojs

**Comment by gkatsev** [comment] 2017-03-31 16:09
What type of video are you playing back? What browser are you playing it in?
If it's something like an mp4, make sure it's [encoded for the web](https://github.com/videojs/video.js/blob/master/docs/guides/troubleshooting.md#problems-with-playback).
Also, our troubleshooting document should hopefully be useful in general as well: https://github.com/videojs/video.js/blob/master/docs/guides/troubleshooting.md

**Comment by venkatas** [comment] 2017-04-01 03:53
Videos are MP4 and we are also using HLS Plugin.

Here is link to our video page : http://ishare.rediff.com/video/others/watch-thirsty-cobra-drinks-water-from-a-bottle-in-drought-hit-karnataka/10774570

**Comment by gkatsev** [comment] 2017-04-04 23:50
Seems to be working fine for me. What browser are you seeing this fail in? Also, potentially which OS version as well?

**Comment by venkatas** [comment] 2017-04-05 03:27
Happening mostly on Chrome and any OS. It does not happen always but intermittently but in regular frequency.
 I just encountered the error. 
Video Link : http://ishare.rediff.com/video/news-and-politics/video-bomdila-welcomes-dalai-lama-wholeheartedly/10776828
Screenshot for the same is http://rcloud.rediffmailpro.com/owncloud/public.php?service=files&t=732151e06cffa1b1ea511604115a5635

**Comment by gkatsev** [comment] 2017-04-20 03:26
I'm unable to reproduce any issues. Closing, but we can re-open if we can find a reproducable test case

**Closed by gkatsev** 2017-04-20 03:26 UTC
