### ISSUE TITLE
v5.0.0-rc.4 Cannot enable captions on iOS 8.3

### ISSUE THREAD

**Issue by forbesjo** [videojs/video.js#2312] opened 2015-07-07 16:10 UTC
The CC icon does not appear in the player nor do the native iOS captions controls appear. These options are present on the same device with latest stable.

4.12.10
![img_0007](https://cloud.githubusercontent.com/assets/7529098/8552212/ba64f37e-24a9-11e5-92a4-ff6a85005fa2.jpg)
![img_0008](https://cloud.githubusercontent.com/assets/7529098/8552213/ba697d36-24a9-11e5-9958-3f56c4859d92.jpg)

5.0.0
![img_0005](https://cloud.githubusercontent.com/assets/7529098/8552221/cb1d2164-24a9-11e5-8cf4-a3b6bd3aadfa.jpg)
![img_0006](https://cloud.githubusercontent.com/assets/7529098/8552220/cb179186-24a9-11e5-9ec5-5982d3ef75da.jpg)

**Comment by gkatsev** [comment] 2015-07-07 17:32
Duplicate of #1904 and #1888 and #2269.

**Closed by gkatsev** 2015-07-07 17:32 UTC
