### ISSUE TITLE
HLS videos are not working on Samsung Galaxy S21 using Chrome browser

### ISSUE THREAD

**Issue by gitamj** [videojs/video.js#7297] opened 2021-07-01 09:59 UTC
## Description

HLS videos are not working on Android, Samsung Galaxy S21/S21+ when using Chrome.

The video throws an error on browser console:
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 

The same video works on that device when used with HLS.js library with a simple video element on page.

## Steps to reproduce
You can browse the following two URLs. One uses video.js and the other one uses HLS.js

1) Here is the version that does not work:
https://www-temp.s3.us-east-1.amazonaws.com/videojs.html

2) The same video works on Galaxy S21 without video.js and using HLS.js
https://www-temp.s3.us-east-1.amazonaws.com/hlsjs.html

I thought that the things might be wrong in my FFMPEG commands or the my videos were not encoded properly. But I have also tested some HLS videos provided publicly by other companies. The above pages are using a video link provided here https://bitmovin.com/mpeg-dash-hls-examples-sample-streams/

### Expected
The video should work normal.

### Actual
The video throws an error.

### Error output
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 

#### videojs
7.14.0
#### browsers
Chrome 89 on Anrdroid device. Specifically Samsung Galaxy S21.
#### OSes
Android

**Comment by gkatsev** [comment] 2021-07-01 21:47
Huh, this is weird. Looks like it's just that stream? Using browserstack (I don't have a physical device), I can confirm the error. But loading in https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 seems to work, as well as a bunch of other sources in https://videojs-http-streaming.netlify.app/.

**Comment by gitamj** [comment] 2021-07-02 06:19
In my experience, it's not just that stream. Some HLS videos work and some don't.

**Comment by gkatsev** [comment] 2021-07-12 23:41
If you have other streams you can see don't work, please let us know.

**Comment by gkatsev** [comment] 2021-07-14 23:03
I believe we have this fixed in Video.js 7.14.1 which we just released. Please take a look.

**Comment by gitamj** [comment] 2021-07-14 23:28
> I believe we have this fixed in Video.js 7.14.1 which we just released. Please take a look.

Thank you Gary, that's great news!!

**Comment by gitamj** [comment] 2021-07-15 02:51
> I believe we have this fixed in Video.js 7.14.1 which we just released. Please take a look.

👍 
It appears to be working, thanks a lot!!

**Comment by gkatsev** [comment] 2021-07-15 13:00
Good to hear, thanks. Closing for now, if you have more issues, please post and we can re-open.

**Closed by gkatsev** 2021-07-15 13:00 UTC
