### ISSUE TITLE
Remove import node_modules from videojs.scss

### ISSUE THREAD

**Issue by Vaporizd** [videojs/video.js#2789] opened 2015-11-07 13:08 UTC
Hi,

Why [are these icons](https://github.com/videojs/video.js/blob/51f1863adc869534d74fdd0c89c0c030534b8708/src/css/video-js.scss#L5) being imported yet ignored by bower?

If you try to use something like rails-assets to include this into a rails app it will be unable to find those icons because they are being ignored by [bower.json](https://github.com/videojs/video.js/blob/master/bower.json#L18). Either unignore them or remove them please.

Thanks.

**Comment by misteroneill** [comment] 2015-11-07 16:02
This is because Bower is not a real package manager. Bower only clones Git repositories and lacks a registry or any support for scripting. Video.js currently does a fair amount of extra work done to support these limitations of Bower.

The icons cannot be unignored because they are an external dependency and, therefore, [also ignored by Git](https://github.com/videojs/video.js/blob/master/.gitignore#L12) and should remain that way.

They cannot be removed because the UI needs those icons!

__The solution__ is either to use npm instead of Bower or - if Bower must be used - reference only the built assets in `dist/` rather than `src/`.

...

One thought that I have now is should `bower.json`'s `"main"` property be changed to the following?

```js
  "main": [
    "dist/video.js",
    "dist/video-js.css"
  ],
```

Also, maybe it makes sense to ignore `src/` entirely in `bower.json` so it's clear that only the `dist/` dir should be used by Bower?

**Comment by Vaporizd** [comment] 2015-11-07 16:12
That seems like a reasonable solution and should solve the problem with the icons not being found. 

Because as of right now if u tried to use something like rails-assets.org which creates a gem based on bower, you won't be able to use videojs, unless you download those icons and put them alongside the gem.

**Comment by misteroneill** [comment] 2015-11-13 18:01
This actually looks like a dupe of #2611

**Comment by Vaporizd** [comment] 2015-11-15 16:34
There seems to be a PR for this already. Maybe get it merged for the next version or something?

**Comment by gkatsev** [comment] 2015-11-17 18:37
Closing as duplicate of #2611.

**Closed by gkatsev** 2015-11-17 18:37 UTC
