### ISSUE TITLE
IOS issue when implementing javascript based controls

### ISSUE THREAD

**Issue by dwlassen** [videojs/video.js#4977] opened 2018-02-26 16:31 UTC
[sample_video.js.txt](https://github.com/videojs/video.js/files/1759433/sample_video.js.txt)
## Description
I am a bit of a newbie re video.js and am trying to use it in a video application to achieve a consistent video player look and feel across modern browsers including ios/safari. The problem I have is that the video.js libraries seem to have an issue with implementing controls via javascript. The Play button in the below example works in FF, edge and chrome but not in any iphone browser. I have used what I believe to be the latest css and js sources.

## Steps to reproduce
Run the below code in an IOS browser and press the Play button

### Expected
Video plays

### Actual
Video does not play

###Code:
```
<link href="http://vjs.zencdn.net/6.7.1/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/6.7.1/video.js"></script>

<video id="movie" class="video-js vjs-default-skin" controls="" preload="auto" width="640" height="264" data-setup="{"example_option":true}">
<source src="http://vjs.zencdn.net/v/oce..." type="video/mp4"/>
To view this video please enable JavaScript, and consider upgrading to a web browser that supports HTML5 video
</video>

<button onclick="pressPlay()">Play</button>

<script>
var vid = document.getElementById("movie");
function pressPlay() {
vid.play();
} 
</script>
```
#### browsers
what browser are affected?
IOS safari and IOS chrome
Major recent non-IOS browsers do not have the issue (Chrome, FF, edge, IE)

**Comment by gkatsev** [comment] 2018-02-26 16:56
Historically, iPhones didn't allow playing back video in anything but the native player. On top of that, they forced the native controls on iPhones and when native controls were enabled you wouldn't be able to overlay elements on top of the video element and have them receive events. So, the decision was made that Video.js will show the native UI on iPhones. Since those times, iPhones now allow you to play inline and allow overlayed elements to receive events but we haven't yet changed the defaults yet. It is probably time to revisit the defaults, at least for newer iPhones.

**Comment by dwlassen** [comment] 2018-02-26 18:38
Hi there, and thanks for the quick reply. I am fine displaying native controls on ios/iphone, but the problem is that the ability to use js to control the player seems to be disabled on IOS when I implement a basic version of video.js, while the same exact code works fine in non-IOS browsers.

Is there anyway around that? (the attached minimized example demos the issue).

Thanks

Dennis

**Comment by dwlassen** [comment] 2018-02-26 19:25
I guess one possible workaround would be to include 2 video elements on the page and then use js to set style="display:block" or style="display:none" depending on the browser/os detected.

But it would be cleaner if video.js could fall back to default controls and not disable js to run in the page out of the box.

Any help appreciated.

Thanks

Dennis

**Comment by gkatsev** [comment] 2018-02-26 19:33
I believe you can force the video.js controls on iOS/iPhone. Let me try and find it exactly.

**Comment by gkatsev** [comment] 2018-02-26 19:45
The option is called `nativeControlsForTouch`, you can set it as a tech option like so:
```js
{
  html5: {
    nativeControlsForTouch: false
  }
};
```
You may also want to set `playsinline` if you want it to play inline rather than the native player on iPhones.

Let me know if that works.

**Comment by dwlassen** [comment] 2018-02-26 19:52
Thanks - Ill give it a go :-)

**Comment by dwlassen** [comment] 2018-02-26 20:27
I updated the opening video tag in my example as follows:

`<video id="movie" class='video-js' controls preload="auto" width="640" height="264" **data-setup='{"nativeControlsForTouch": true}'**>`

however it didn't change the behavior: the play button still doesn't work on IOS (I also set the value to "false" but got the same result.) Would you be able to show how to implement the option in my sample code above?

Thanks

Dennis

**Comment by gkatsev** [comment] 2018-02-26 20:44
You need to make sure to target the tech and you want the value to be false not true.
For example:
```
data-setup='{"html5": { "nativeControlsForTouch": false}}'
```

**Comment by dwlassen** [comment] 2018-02-26 20:49
Thanks again, but I am still unable to get this to work - updated code:

`<link href="http://vjs.zencdn.net/6.7.1/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/6.7.1/video.js"></script>
                                              
<video id="movie" class='video-js' controls preload="auto" width="640" height="264" data-setup='{"html5": { "nativeControlsForTouch": false}}'>
 <source src="http://vjs.zencdn.net/v/oceans.mp4" type="video/mp4" />
 <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
</video>

<button onclick="pressPlay()">Play</button>

<script>
var vid = document.getElementById("movie");

function pressPlay() {
  vid.play();
}         

</script>`

**Comment by dwlassen** [comment] 2018-02-26 20:54
Thanks - but still no joy, updated code attached.

[test7.txt](https://github.com/videojs/video.js/files/1760251/test7.txt)

**Comment by gkatsev** [comment] 2018-02-26 21:00
You're not interacting with the Video.js API but rather using the video element directly which doesn't work with Video.js because the original video element may not exist -- it doesn't on iOS.
Instead, you should probably initialize video.js manually and then use the API.
Example:
```html
<video id="movie" class='video-js' controls preload="auto" width="640" height="264">
   <source src="http://vjs.zencdn.net/v/oceans.mp4" type="video/mp4" />
</video>
<button id="my-play-button">Play</button>

```
```js
var player = videojs('movie', {
  html5: {
    nativeControlsForTouch: false
  }
});
document.querySelector('#my-play-button').addEventListener('click', function() {
  player.play();
});
```

Hope that helps.    

Also, going to close this issue because I don't think it will require any changes in Video.js but we can for sure continue the discussion in here even if the issue is closed.

**Closed by gkatsev** 2018-02-26 21:00 UTC

**Comment by dwlassen** [comment] 2018-02-26 21:01
OK I appreciate your patience and help, as I am on the early stages of the learning curve :-)

**Comment by dwlassen** [comment] 2018-02-26 21:17
Thanks for the solution, it works great. Also, I implemented the "playsinline" option which worked and was a pleasant surprise as I wasn't aware this had become possible.

**Comment by gkatsev** [comment] 2018-02-26 22:00
Glad to hear you got it working!
Yeah, playsinline was added to iOS 10 in late 2016.
