### ISSUE TITLE
7.4.2: Blocked by Malwarebytes Chrome and Firefox extension - malware?

### ISSUE THREAD

**Issue by super23n** [videojs/video.js#5750] opened 2019-01-14 22:57 UTC
## Description
Web page that includes the Videojs Javascript file, is blocked by Chrome and Firefox Malwarebytes extension. Tested Videojs versions 7.4.2, 7.4.1, 7.4.0, 7.3.0.

## Steps to reproduce
1. Include the Videojs Javascript file at the bottom of the web page, for example: 
`<script src="video.min.js"></script>`
2. Include the Videojs CSS file at the top of the web page.
3. Enable Malwarebytes extension and go to/reload the web page.

### Expected
The Videojs player should be loaded when the web page loads, and be ready to play.

### Actual
The web page is visible very briefly, but then immediately replaced by a Malwarebytes page with a message: "Website blocked due to possible suspicious activity". In the address bar of the browser, the URL changes to the URL of the browser extension, and at the end is this: 
`...&type=scam&subtype=coinMiner.worker`. This happens for both Chrome and Firefox.

### Error output
No errors visible.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Tested with: 7.4.2, 7.4.1, 7.4.0, 7.3.0.
#### browsers
Chrome 71.0.3578.98 and Firefox 64.0
#### OSes
Windows 7
### plugins
No Videojs plugins.

**Comment by gkatsev** [comment] 2019-01-14 23:44
Where did you get the files? Looking at the files on our CDN they're equivalent to the files that are published to npm. Going to our CDN url or via this jsbin https://jsbin.com/lawobevore/edit?html,output I could not reproduce this with the malware bytes extension.

**Comment by super23n** [comment] 2019-01-15 00:05
I downloaded it from the Releases page: github.com/videojs/video.js/releases
I have tried it with the CDN version, by including `<script src="https://vjs.zencdn.net/7.3.0/video.js"></script>`  and the result is the same..

**Comment by gkatsev** [comment] 2019-01-15 00:13
Hm... there's definitely nothing coinminer related in there and all the files are identical. When trying it locally, I could not see anything with the malware bytes extension. I'm wondering if there's something else that's causing this.

**Comment by super23n** [comment] 2019-01-15 00:34
That URL you posted, I cannot reproduce it there either, but with a web server (or xamp) that's when it  happens.

**Comment by gkatsev** [comment] 2019-01-15 00:39
Sounds like you have something on your web server intercepting requests and appending a coin miner.

**Comment by gkatsev** [comment] 2019-01-30 21:19
Yup, closing.

**Closed by gkatsev** 2019-01-30 21:19 UTC
