### ISSUE TITLE
Getting "Cannot read property '0' of undefined", null check in parseUserData?

### ISSUE THREAD

**Issue by stomata** [videojs/video.js#6619] opened 2020-04-24 17:02 UTC
Environment:
I have a website implmeneted in ReactJS.
We are trying to implement DRM protected assets playback using the latest version of VideoJS.
Versions:
VideoJS: 7.8.1 (also tried 7.7.5)
mux.js: 5.5.4(also tried 5.2.1)
videojs-contrib-eme: 3.7.0

We get this error when trying to play a widevine protected content with Google Chrome browser on a Macbook:

Note: because we use npm to install pacakages. We have to npm install mux.js separatedly.
videojs/video.js#6417

I did a codepen version of using the following scripts and the player works without any problem.

<script src="https://unpkg.com/video.js/dist/video.js"></script> <script src="https://cdn.jsdelivr.net/npm/videojs-contrib-eme/dist/videojs-contrib-eme.min.js"></script>
Note that we don't have this issue when playing hls streams (Chrome, Safari, Firefox) nor hld streams with Fairplay DRM protection (in Safari)
![image](https://user-images.githubusercontent.com/848144/80238128-be645080-8612-11ea-98b4-dd7b8a094922.png)

Sorry I can't share the exact codepen code as that will expose some sensitive materials of our company.

I have also created a ticket in you Mux.js project, however I haven't got a response. https://github.com/videojs/mux.js/issues/335
Wondering if there's any reason why isn't there a null check in parseUserData() function of mux.js/lib/tools/caption-packet-parser.js ?
Is there any logical reason for not null checking?

If I add the null check for sei.payload, then the player will work fine.

**Comment by gkatsev** [comment] 2020-04-29 18:58
Duplicate of https://github.com/videojs/mux.js/issues/335

**Closed by gkatsev** 2020-04-29 18:58 UTC
