### ISSUE TITLE
v5.0.0-rc.4 Captions issues in IE8/9/10

### ISSUE THREAD

**Issue by forbesjo** [videojs/video.js#2314] opened 2015-07-07 17:29 UTC
1. If you enable a captions track the text is not displayed until you enter fullscreen.  
1. Once captions are displayed they do not update as the video progresses or if you scrub.

**Comment by apadhye** [comment] 2015-07-08 18:21
Also seen in FF and IE11 so far.

**Comment by gkatsev** [comment] 2015-07-08 18:23
Captions broke again? T__T

**Comment by gkatsev** [comment] 2015-07-08 21:03
Oh, I think this might be a dupe of #2172 which will be fixed by #2215

**Comment by gkatsev** [comment] 2015-07-09 15:08
Going to close this as a dupe of #2172 which has been fixed.

**Closed by gkatsev** 2015-07-09 15:08 UTC
