### ISSUE TITLE
Firefox 45+ console warning

### ISSUE THREAD

**Issue by addelong** [videojs/video.js#3352] opened 2016-05-31 21:06 UTC
## Description
Seen on Firefox 45 and 46, with video.js version 5.9.2. 

## Steps to reproduce

1. Include the video.js script on a page and (might not be necessary) instantiate a videojs object.

### Expected
No console warning appears.

### Actual
The following console warning is thrown:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
```

### Error output
See above

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.9.2, have not tested other versions
#### browsers
Firefox 45+
#### OSes
Tested on El Capitan, but I would expect any OS with FF 45+ to throw this
### plugins
none

I believe the error is coming from this block:

```
/*
         * Clean up any existing source handler
         */
        _Tech.prototype.disposeSourceHandler = function () {
            if (this.sourceHandler_ && this.sourceHandler_.dispose) {
                this.sourceHandler_.dispose();
            }
        };
```

**Comment by gkatsev** [comment] 2016-05-31 21:12
A known non-issue. It's because we're using babel to compile our javascript, it's just a warning and can be ignored. Duplicate of https://github.com/videojs/video.js/issues/3325#issuecomment-219465484

**Closed by gkatsev** 2016-05-31 21:12 UTC
