### ISSUE TITLE
Autoplay issues on Chrome

### ISSUE THREAD

**Issue by karlazz** [videojs/video.js#3294] opened 2016-05-03 18:58 UTC
## Description
I have this code in an html file.  It works in Firefox and in Safari but will not autoplay on Chrome.
```
<video id="my-video" class="video-js" width="640" height="264" controls data-setup='{}' autoplay>
    <source src="mysource.mp4" type='video/mp4'>
    <!-- source src="MY_VIDEO.webm" type='video/webm' -->
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>
```

Then I took out the data-setup='{}' and the autoplay works in all browsers, but the size attributes no longer work and the video window is super small.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
I am using the cdn hosted version 5.9.2
#### browsers
Chrome 50, Firefox 46
#### OSes
Mac OSX Mavericks
### plugins
none

**Comment by gkatsev** [comment] 2016-05-03 19:23
Seems like a duplicate of https://github.com/videojs/video.js/issues/3071

**Comment by gkatsev** [comment] 2016-05-24 14:56
Closing as a duplicate.

**Closed by gkatsev** 2016-05-24 14:56 UTC
