### ISSUE TITLE
Video stop when click to play button ( flash)

### ISSUE THREAD

**Issue by njaistudio** [videojs/video.js#3549] opened 2016-08-18 04:35 UTC
## Description

I play a flash video(tream rtmp). When  I click in to video, this video play nomal. but when i click in to button play, video play and stop and resize.
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.
1. Click to video background
   ![untitled-1](https://cloud.githubusercontent.com/assets/12797736/17762242/dff6d032-6538-11e6-8a06-f407cdac2eeb.png)
2. Click to play button

![untitled-2](https://cloud.githubusercontent.com/assets/12797736/17762243/e0b33f9c-6538-11e6-8c07-1c7a33b6384c.png)
### Actual

Please describe what actually happened.
### Error output

If there are any errors at all, please include them here.
## Additional Information

Please include any additional information necessary here. Including the following:
#### videojs

5.8
#### browsers

Tested on chrome

**Comment by gkatsev** [comment] 2018-01-03 19:20
I'm unable to reproduce with the stream I have access too, so, it's either been fixed or needs a reduced test case.
Closing for now since it's been so long, please let us know if it's still an issue.

**Closed by gkatsev** 2018-01-03 19:20 UTC
