### ISSUE TITLE
v5.0.0-25: No subtitles visible in ff

### ISSUE THREAD

**Issue by psharmz** [videojs/video.js#2213] opened 2015-05-29 19:41 UTC
1. Build a default sandbox player, with any possible tech order, and play it firefox
2. During playback select captions icon, select English

Expected: Captions appear during playback
Actual: No captions are present.

The following errors are thrown in the console: 

```
TypeError: this.el_.vjs_getProperty is not a function
downloadable font: rejected by sanitizer (font-family: "VideoJS" style:normal weight:normal stretch:normal src index:0) source: http://10.1.10.220:9999/build/temp/font/VideoJS.eot
```

**Comment by OwenEdwards** [comment] 2015-05-29 19:43
This is a duplicate of #2172.

**Comment by heff** [comment] 2015-05-29 19:58
Got it. Thanks @psharmz and @OwenEdwards. Closing in favor of #2172.

**Closed by heff** 2015-05-29 19:58 UTC
