### ISSUE TITLE
flash mode,with no controls, poster cant be show

### ISSUE THREAD

**Issue by cheerful-li** [videojs/video.js#3905] opened 2017-01-03 04:34 UTC
## Description
 in a flash mode, we set controls to false,then no poster get shown ( it should).

I do checked the source code, in _poster.scss,  see:
```
// Hide the poster when controls are disabled because it's clickable
// and the native poster can take over
.vjs-controls-disabled .vjs-poster {
  display: none;
}
```
so the reason is  video element have a poster attribute,that's ok, but in flash ...
## Steps to reproduce
my test code:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>test videojs</title>
	<link rel="stylesheet" href="../dist/video-js.min.css">
	<script src="../dist/video.min.js"></script>
</head>
<body>
	<video id="my-video" width="800" poster="http://nos.netease.com/vod163/poster.png"></video>
	<script>
		videojs("my-video",{
			controls:false,
			techOrder:["flash","html5"]
		},function(){
			console.log("inited");
		});
	</script>
</body>
</html>
```

**Comment by gkatsev** [comment] 2017-01-09 23:20
Looks like a duplicate of #1625. There's also some steps we can take to fix it, if you want to give it a go.

**Closed by gkatsev** 2017-01-09 23:20 UTC
