### ISSUE TITLE
Internet Explorer 9 occasionally failing when video URLs do NOT contain scheme and domain

### ISSUE THREAD

**Issue by Jpsy** [videojs/video.js#734] opened 2013-09-12 15:14 UTC
We had occasional reports of users not being able to watch videos on IE9 while most visitors had no problems at all. The affected users COULD in fact view the demo video on www.videojs.com without any problems. Only a small fraction of our users were affected by that problem and even those reported that playback occasionally worked for them (in about 20% of their trials).
After a long rally of ghost hunting and debugging we finally found the one difference that made it work for all users:
Video URLs have to contain the scheme and URL (as the videos on www.videojs.com do, e.g. src="http://vjs.zencdn.net/v/oceans.mp4"). Our URLs were starting with a slash to address local files (e.g. src="/videos/myvideo.mp4").
Why this does disturb IE9 on some machines and does work on others is beyond my grasp. I could never reproduce it on our development machines, but witnessed it with great stability on some user machines. The affected browsers were all IE9.0.8112.16421 on Win 7 32, but I would not count on the fact that these are the only affected versions. The problem seems to be connected with limited bandwidth and lengthy round trip times, so it could be some timing or syncing problem, which would explain why even the affected users can sometimes play the videos. But I have no idea why the problem is (reliably!) solved by adding scheme and host to the video URLs.
The Video.js versions that we tested with were 4.1.0 and 4.2.1, hosted on our own servers. preload parameter of &lt;video&gt; tag was set to "auto". autoplay was NOT active.
The symptoms of the problem are: Spinner is visible on the video right after opening the page in IE. Spinner does not rotate and does not vanish. Play button does either not appear or does not react to clicks.
It could be possible that this issue is related to #628 .

**Comment by mmcc** [comment] 2015-07-25 01:04
Given the age of this, the tiny usage of IE9, and the fact that we've been unable to reproduce locally, I'm going to close this. If we can get a reduced test case ping this issue so we can reopen.

**Closed by mmcc** 2015-07-25 01:04 UTC
Labels: browser bug, bug, needs: more info
