### ISSUE TITLE
There's so much bug in the latest version

### ISSUE THREAD

**Issue by onigetoc** [videojs/video.js#4604] opened 2017-09-09 19:33 UTC
There's so much bug in the latest version

When i first load a page without cache, sometime video will show me a error can't load media. if i reload the web page it may work. if i reload again or with F5, it may work.

Same thing in internet explorer. Some time the video will be all black.

You will say, where your demo. It's like that everywhere even on your own demo page.
http://videojs.com/advanced/
In this example, only the first video will work on IE 8 and more.
Usually, if page is in the browser cache it will alway work. So it's probably a problem with the external js file. 

May be it should have a better video ready or something else i don't know.

In this issue, on the pastebin examples. 
both video on pastebin do not work in Windows 7 with IE 11
https://github.com/videojs/video.js/issues/4603

**Comment by samueleastdev** [comment] 2017-09-10 07:27
Pretty sure some of our users have been getting a similar issue to this where they are stating when they load the page it doesn't always load first time but when they refresh again it's works. As soon as I get some time I will try setting up an example based on some of the users feedback.

**Comment by gkatsev** [comment] 2017-09-11 15:42
Hi @onigetoc I understand that issues can be frustrating but opening an issue saying that there's so many bugs is not helpful and discourages the maintainers. Please try and consider that we spend a lot of time and energy on this and definitely do not let bugs in on purpose but we want to work with you in resolving issues when they occur.

The advanced page on videojs.com probably needs more documentation but the reason only the first video works in IE8 is because it's probably the only mp4 video. The rest of the videos are HLS use contrib-hls to play back on browsers that aren't Safari or on mobile. contrib-hls doesn't work on IE8 because it doesn't have the built-ins that are necessary and it is too slow to function properly with polyfills.

Are the issues with the cache happening on a particular browser? Are you seeing these issues on videojs.com/advanced? With just the oceans video? Does it happen on just one version of Video.js or across multiple versions? A reduced test case that triggers the behavior every time is always helpful.

**Comment by gkatsev** [comment] 2017-09-11 15:42
@samueleastdev if you're able to make a test case that would be swell.

**Comment by onigetoc** [comment] 2017-09-11 15:59
Like i said it may be hard to see if there's a bug with cache or zen server js cache.
There's lot of demo in my blog page. i let you browse normally just to see what it will do.
http://www.scriptsmashup.com/blog

**Comment by gkatsev** [comment] 2017-12-01 23:31
I've been unable to reproduce anything and this issue hasn't had activity in a long time.

**Closed by gkatsev** 2017-12-01 23:31 UTC
