### ISSUE TITLE
New div wrapper created each time on play()

### ISSUE THREAD

**Issue by tjbee** [videojs/video.js#3141] opened 2016-02-26 17:32 UTC
Every time the play() function is triggered, a new div wrapper is created inside an existing div  -

```
<div preload="auto" class="video-js vjs-default-skin in-grid-video-1-dimensions vjs-controls-enabled vjs-user-inactive vjs-playing vjs-has-started" id="in-grid-video-1">
<div preload="auto" class="vjs-tech vjs-controls-disabled in-grid-video-1_html5_api-dimensions vjs-user-inactive vjs-playing vjs-has-started" id="in-grid-video-1_html5_api">
<div preload="auto" class="vjs-tech vjs-controls-disabled vjs-playing vjs-has-started in-grid-video-1_html5_api_html5_api-dimensions vjs-user-inactive" id="in-grid-video-1_html5_api_html5_api">
<div preload="auto" class="vjs-tech vjs-controls-disabled vjs-playing vjs-has-started in-grid-video-1_html5_api_html5_api_html5_api-dimensions vjs-user-inactive" id="in-grid-video-1_html5_api_html5_api_html5_api"><video id="in-grid-video-1_html5_api_html5_api_html5_api_html5_api" class="vjs-tech" preload="auto">
						 
						    <source src="http://s7.toryburch.com/is/content/ToryBurchLLC/TB_41151130_001_VID_Tablet_Autox480p_1400k" type="video/mp4">
						
						
						</video>
```

**Original HTML**
```
<div class="newVideo ">
						<div class="newVideo-holder">
						
						<video id="really-cool-video" class="video-js vjs-default-skin" controls
						 preload="auto" width="100%" height="100%" 
						 >
						 
						 
						    <source src="${s7videoPath}" type='video/mp4' />
						
						
						</video>
```

**Comment by mmcc** [comment] 2016-02-26 21:14
Whatever's going on here, I'm pretty confident the root cause isn't Video.js. I'm going to close this, but if you'd like to fill out the [Issue Template](https://github.com/videojs/video.js/blob/master/ISSUE_TEMPLATE.md) you might have better luck getting someone to help debug (or we can definitely reopen this if I'm wrong and this is a legitimate bug in Video.js).

**Closed by mmcc** 2016-02-26 21:14 UTC
