### ISSUE TITLE
Chapters menu not showing

### ISSUE THREAD

**Issue by jorydekort** [videojs/video.js#3151] opened 2016-03-01 20:20 UTC
## Description
When adding a Chapters and Captions file to videojs the icons are not shown when only loading using html code. When initializing with js the icons for both the options show in the menu but when clicking the chapters menu nothing happens. When inspecting the HTML code the header seems to be at the bottom as well.

See example below. This will show both the buttons but no chapters menu will show. Same result on self hosted css and js files.

```
<!DOCTYPE html>
<html>
	<head>
		<title>Video.js | HTML5 Video Player</title>
		<link href="https://vjs.zencdn.net/5.7.1/video-js.css" rel="stylesheet">
		<script src="https://vjs.zencdn.net/5.7.1/video.js"></script>
	</head>
	<body>
		<video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="640" height="264" poster="http://vjs.zencdn.net/v/oceans.png" data-setup="{}">
			<source src="https://vjs.zencdn.net/v/oceans.mp4" type="video/mp4">
			<track kind="captions" src="example-captions.vtt" srclang="en" label="Captions"></track>
			<track kind="chapters" src="example-captions.vtt" srclang="en" label="Chapter" default></track>
		</video>
	    <script>
		    var player = videojs('example_video_1', {}, function() { });
		</script>
	</body>
</html>

```
Also, without: 
`var player = videojs('example_video_1', {}, function() { });`
Both the icons will not even show in the menu!!

### Expected
I would expect to see the chapter menu as before.

### Actual
No menu is shown when clicking the chapter menu

## Additional Information
This shows in 5.7.1 on Safari 9.0.3 and Chrome 48.0.2564.116 on Mac OS X 10.11.3.

**Comment by gkatsev** [comment] 2016-03-01 20:49
Thanks for the details report. Going to close this as a dupe of #3062.

**Closed by gkatsev** 2016-03-01 20:49 UTC
