### ISSUE TITLE
Poster not hiding over API call

### ISSUE THREAD

**Issue by ain** [videojs/video.js#1703] opened 2014-12-02 16:08 UTC
HTML:
```html
  <video id="myvideo" class="video-js vjs-default-skin"
    preload="auto" width="718" height="404"
    poster="/assets/poster.jpg"
    data-setup='{}'>
    <source src="/assets/video.mp4" type='video/mp4'>
    <source src="/assets/video.webm" type='video/webm'>
  </video>
```
JS:
```javascript
(function ($) {
  var player = videojs('myvideo', {}, function() {
    this.play();
    var v = this;
    setTimeout(function() {
      console.log('attempting to hide!', v);
      v.posterImage.hide();
    }, 3000);
    this.on('timeupdate', function(event) {
      console.log(this.currentTime());
    });
  });
})(jQuery);
```
Version used: `http://vjs.zencdn.net/4.10/video.js`

**Comment by gkatsev** [comment] 2015-11-17 23:57
I wonder whether we still have this issue in v5.

**Comment by mariospr** [comment] 2016-03-15 16:26
I think I might be seeing this very same issue with Chromium (not chrome) built from sources, but not from Chrome, since I can reproduce the problem described with videos from the following websites:
  * http://demo.learningequality.org/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/counting-with-small-numbers/
  * http://jonathanfield.com/foo/video-js/demo.html
  * http://videojs.com (Main video at the top)
  * http://mediaelementjs.com (Main video at the top)
  * http://jsbin.com/semitutufo/1/edit?html,output

In any of those videos, if I click on the play button the video starts playing under the poster image, but the vjs-has-started class is not applied to the main <div> element, meaning that the poster image is not hidden and that the video controls are not made visible.

Manually altering the DOM with the inspector confirms that theory if I remove the poster element and make the controls visible by hand, in case it rings any bell.

The other interesting piece of information I found is that this fails with Chromium built from trunk, but also on a stable build of Chromium from Ubuntu (version 48.0.2564.82) while a similar stable build of Chrome (same version, 48.0.2564.82, but built with the Chrome "branding") seems to work fine, so perhaps it's an issue with the browser.

In any case I thought I would comment on this here since I'm new to all this and a bit lost at the moment, in case it rang any bell.

Thanks in advance and apologies if this ends up being totally unrelated noise :)

**Comment by mariospr** [comment] 2016-03-15 21:16
Sorry for the noise, I just found that the problem in this particular case was caused by a local patch that I had applied into Blink's HTMLMediaElement, which was causing the issue. Removed that patch the problem is gone too, and Video.JS based sites work as expected again.

**Comment by gkatsev** [comment] 2016-03-28 21:47
Do we actually want to hide the native poster when the `posterImage` component is told to hide, @videojs/core-committers? It seems to me that they should be separate but maybe I'm missing something.

**Comment by gkatsev** [comment] 2016-07-25 22:34
I'm going to close this. I think that hiding the `posterImage` component shouldn't hide the native poster. They're two separate items.

**Closed by gkatsev** 2016-07-25 22:34 UTC
Labels: bug, confirmed
