### ISSUE TITLE
rtmp with authentication parameters

### ISSUE THREAD

**Issue by pikadjou** [videojs/video.js#2285] opened 2015-06-25 09:25 UTC
Hi everyone,

I have a little probleme with rmtp streaming. I need to put some parametres with the stream, like that: Rmtpe://xxxx?auth=xxx&token=xxx
But the player does'nt work with an url like this.. ( it works with a 'normal' rtmpe url). 
Do you have any idea? Or maybe i miss something in docs?

Thank you so much for your help.

Geoffrey

**Comment by mmcc** [comment] 2015-06-29 21:48
Closing this as a duplicate of #858.

**Closed by mmcc** 2015-06-29 21:48 UTC
