### ISSUE TITLE
Doubled up controls on iOS

### ISSUE THREAD

**Issue by kachnitel** [videojs/video.js#3601] opened 2016-09-07 00:12 UTC
Using any version of video.js 5 and higher, it appears to show an extra set of controls over the set that should actually be there. The extra set doesn't control the video it shows.
It is easily visible without CSS as in this example:
```
<!DOCTYPE html>
<html lang="en">
<head>
<!--       <link href="../video.js/css/video-js.css" rel="stylesheet"> -->
</head>
<body>
    <div id="wrap">
              <video id="my-video453652" class="video-js vjs-big-play-centered video-element" controls preload="auto" poster="poster.jpg" data-setup="{}">
                <source src="video.mp4" type='video/mp4' label='240p' res='240'>
              </video>

<!--               <script src="../video.js/js/video.min.js"></script> -->
<script src="http://vjs.zencdn.net/5.11.6/video.js"></script>

              <script>
                var player = videojs('my-video453652', {
//                     autoplay: true
                });
              </script>
    </div>
</body>
</html>
```

It does behave the same in Chrome's inspector, when emulation of an iOS device is enabled. Emulating an Android device doesn't have such issue, and indeed it works correctly on Android.
![slack for ios upload](https://cloud.githubusercontent.com/assets/4067705/18295281/15913f36-7455-11e6-979e-e4c6dff23662.jpg)

**Comment by gkatsev** [comment] 2016-09-07 04:09
Might be a duplicate of https://github.com/videojs/video.js/issues/3283

**Comment by gkatsev** [comment] 2016-09-19 19:33
Closing this as a duplicate of #3283.

**Closed by gkatsev** 2016-09-19 19:33 UTC
