### ISSUE TITLE
5.0-rc.2 - no video shown on iPad Safari

### ISSUE THREAD

**Issue by meleyal** [videojs/video.js#2275] opened 2015-06-19 09:02 UTC
Happens on iPad iOS 8.3 using Safari.

1. Open test page
2. Click play button

Expected: Video is shown
Actual: No video is shown (black), but controls are active
Test case: http://jsbin.com/halokodoxo/1/edit?output

![img_0041](https://cloud.githubusercontent.com/assets/15045/8250299/79dfc724-1672-11e5-8e19-52d34f1ecc13.PNG)

**Comment by mmcc** [comment] 2015-06-19 09:06
Seems like this is a duplicate of #2415. Mind commenting on that thread?

**Comment by mmcc** [comment] 2015-06-19 09:07
Wow screwed that up. I meant #2214. Mobile is hard.

**Closed by mmcc** 2015-06-19 09:06 UTC
