### ISSUE TITLE
Dash sources not loading on 5.10.2+

### ISSUE THREAD

**Issue by RavWar** [videojs/video.js#3428] opened 2016-07-11 13:24 UTC
I've stumbled upon an issue in videojs 5.10.2+ and dash. The dash sources are not loading most of the times.

It actually depends on how fast the manifest is loaded i think. Small and quick manifests load up normally much frequently than the big or slow ones. Once network throttling is set to slow (3G for example) then the small start to fail as well.

Here is the test case: http://jsbin.com/yesexuxeqe/edit?html,console,output
Note: if videojs version 5.10.2 is replaced with 5.9.2, it works okay every time.

After some investigation i've managed to pinpoint the error to this pr: https://github.com/videojs/video.js/pull/3285
Here is a normal startup flow (i've added additional log entries for loadstart events and firstLoadStartListener, successiveLoadStartListener functions):

![normal start](https://cloud.githubusercontent.com/assets/675182/16731313/1111e7be-4780-11e6-8a08-970cc01531de.png)

Here is a broken one:

![bad start](https://cloud.githubusercontent.com/assets/675182/16731314/11150dc2-4780-11e6-8a77-7c0c4ff1e6f8.png)

Mentioned pr introduced a feature to dispose source handlers on repetitive loadstart events. And in case of slow dash manifest - loadstart is actually fired twice which causes source handler to be disposed before it can even initiate the playback.

I have not had time to dig up the cause of repetitive loadstart event yet. Maybe someone can shed some light on why's that happening?

**Comment by RavWar** [comment] 2016-07-11 13:26
Also, i'm pretty sure this issue https://github.com/videojs/videojs-contrib-dash/issues/90 has the same cause

**Comment by gkatsev** [comment] 2016-07-11 14:50
Interesting. Thanks for digging in and finding the root cause. It does sound like the repetitive loadstarts are the issue here. From what I understand, the loadstart event should only ever be fired once. Might be worth also opening up an issue against dashjs itself with this.

**Comment by richardbushell** [comment] 2016-07-11 15:26
Ditto, we've been using videojs with videojs-contrib-dash for quite a while and also had to revert to vjs 5.9 after trying 5.10 at the weekend to avoid the Media Source error when trying to load the dash source.

**Comment by richardbushell** [comment] 2016-07-12 16:02
OK, here is the reply from dash.js:
https://github.com/Dash-Industry-Forum/dash.js/issues/1491#issuecomment-231959860
So, any thoughts on the optimal way to programmatically set dash as preferred source and say mp4 as fallback (as we have been pre-specifying the src children within the video tag). Does video.js, dash.js, or videojs-contrib-dash control this decision as all three seem to implement some degree of handling MSE detection and source selection?
We could of course detect MSE initially in JavaScript and pre-determine that it will be dash and write the page dynamically, or should we pass multiple sources in an object/array as source options?  What is the best way to implement fallback.
Would welcome any initial thoughts before going back to review the coding options... Thanks.

**Comment by bbcrddave** [comment] 2016-07-13 09:06
Just to be clear, dash.js doesn't really care about source tags.

dash.js uses MSE which requires a MediaSource object be attached to the media element using `media.src`. Attaching this will always cause a `loadstart`, as specified by HTML5.

**Comment by richardbushell** [comment] 2016-07-13 09:20
So does dash.js always create a SRC attribute within the video tag, rather than a source child of the video tag?

**Comment by bbcrddave** [comment] 2016-07-13 10:20
I am eating my words and have partially retracted my previous comment, having been looking a bit deeper into how dash.js initialises when presented with a `<source>` tag containing type `type='application/dash+xml'`, and how interacts with video.js. Some of the console logs in https://github.com/Dash-Industry-Forum/dash.js/issues/1491#issuecomment-232280409 make it clear what is happening.

See my comments there for what is going on.

**Comment by bbcrddave** [comment] 2016-07-13 11:14
https://jsfiddle.net/jzk1sod9/ shows that, bug aside, `loadstart` is fired independently of dash.js and video.js if there is a `source` tag on the media element.

**Comment by bbcrddave** [comment] 2016-07-13 14:05
> So does dash.js always create a SRC attribute within the video tag, rather than a source child of the video tag?

Currently, dash.js uses the src attribute of the media element to attach the MediaSource object.

It is possible to attach that object to the src attribute of a source tag, but I don't think it would make any difference in this scenario.

**Comment by richardbushell** [comment] 2016-07-13 14:36
Thanks Dave, yes, agree it wouldn't make any difference anyway.

Am tracking your skipAutoCreate post in dashjs issue:
https://github.com/Dash-Industry-Forum/dash.js/issues/1496

skipAutoCreate before dash.js seems a bit hacky, but will await feedback.

I suppose the best solution for players in any event would possibly be to make the canplay decision from an array/object of possible sources (with no source tags pre-written, so using an empty video element), and then either pass the dash source selection to dash.js for attachment, or fallback and create a non-dash source tag then. That should guarantee one loadstart.

Anyway, will wait on further thoughts.

**Comment by richardbushell** [comment] 2016-07-19 17:38
OK, have now eliminated dash.js itself as the root cause. Bottom line is that since VJS 5.10.x the sourcehandling thru contrib-dash now fails. Subsequently most browsers now fall back to default mp4 file, rather than dash. Works fine if I revert to VJS 5.9.0. Not sure if the commits mentioned above are indeed the issue but it's now broken until the culprit is identified and remedied.

**Comment by richardbushell** [comment] 2016-07-19 18:21
Just tested to establish break point.
VJS 5.9.2 is OK.  VJS 5.10.1 breaks.
Culprit is definitely:  https://github.com/videojs/video.js/pull/3285
Result is that some browsers now no longer select and play the dash source and now revert to fallback mp4 playback. Chrome & Edge still play dash, BUT Firefox and IE now revert to MP4 fallback.

**Comment by richardbushell** [comment] 2016-07-21 00:33
Using programmatic sources solved the problem. Currently I believe that anyone using html source tags will now break dash handling if using VJS 5.10.1+ due to: videojs/video.js#3285
I think the browser natively fires loadstart automatically if any source tag is included. Later a new source attribute is added after selection for dash, which again fires another loadstart. Broken by videojs/video.js#3285

**Comment by BrandonOCasey** [comment] 2016-07-21 15:14
we saw what may be a similar issue in 5.10.1/5.10.2 and we tracked it down to that PR as well. As of 5.10.3 a fix https://github.com/videojs/video.js/pull/3343 was merged which may solve the issue

**Comment by richardbushell** [comment] 2016-07-21 15:24
The original error was in introduced in 5.10.1 but we still have the same problem as at 5.10.7.  Using an array of source objects solves it (which we'll probably stick with), but it would be good to find a definitive fix for anyone still using source tags.

**Comment by gkatsev** [comment] 2016-07-25 17:30
I wonder if what we should do is check what the video's `currentSrc` is on the second `loadstart` and then if it's a `blob` do nothing but if it's anything else proceed with the current implementation?

**Comment by jemoreno** [comment] 2016-08-23 13:28
Just wondering if anything has been done on this or if a temporary solution has been given?

**Comment by forbesjo** [comment] 2016-08-23 13:58
@jemoreno the temporary solution would be to load your dash source with player.src() as seen here https://github.com/videojs/videojs-contrib-dash#getting-started

**Comment by jemoreno** [comment] 2016-08-23 14:12
The video will load with this fix, however if you try and seek to a later time it locks up and will not play anymore.

**Comment by ruslandinov** [comment] 2016-11-01 11:34
Hey guys, we also encounter this problem and would appreciate a fix. Is there any chance for the PR to be merged soon?

**Comment by tf** [comment] 2017-08-16 17:23
Is https://github.com/videojs/video.js/pull/3906 (which has been released as part of 6.0) a fix for this problem?

**Comment by gkatsev** [comment] 2018-01-03 19:22
This is fixed as part of 6.0, since we removed the double loadstart code.

**Closed by gkatsev** 2018-01-03 19:22 UTC
Labels: confirmed
