### ISSUE TITLE
Captions button (CC) not showing up in Chrome (latest)

### ISSUE THREAD

**Issue by tungwoodboi** [videojs/video.js#2736] opened 2015-10-24 17:02 UTC
Hi, I found a problem with captions/ subtitles in my chrome browser. It works fine in Firefox but not Chrome. 
My chrome version: 46.0.2490.80 m
Tested with your simple demo: http://docs.videojs.com/docs/examples/simple-embed/index.html
Screenshot attached.
![screenshot 6](https://cloud.githubusercontent.com/assets/13481173/10711619/8ad08490-7aab-11e5-9616-ac11d4a70b83.png)

**Comment by chemoish** [comment] 2015-10-26 19:43
Duplicate of https://github.com/videojs/video.js/issues/2689

**Comment by gkatsev** [comment] 2015-10-26 19:54
Thanks @chemoish, closing as a dupe of #2689.

**Closed by gkatsev** 2015-10-26 19:54 UTC
