### ISSUE TITLE
IE11 playback with MP4 videojs.com website video won't display

### ISSUE THREAD

**Issue by wkwood** [videojs/video.js#2396] opened 2015-07-22 18:01 UTC
Windows 8.1, IE 11.0.9600.17905
My sample works on Firefox, Chrome  working with IE11 I get error below.  The VideoJS.com website gives me the same error.  Upgrading to 4.12.11 didn't resolve it either as well as preload="none" as some of the other closed issues have suggested.

VIDEOJS: ERROR: (CODE:1 MEDIA_ERR_ABORTED) You aborted the video playback [object Object]
   "VIDEOJS:"
   "ERROR:"
   "(CODE:1 MEDIA_ERR_ABORTED)"
   "You aborted the video playback"
   {
      [functions]: ,
      __proto__: { },
      code: 1,
      MEDIA_ERR_ABORTED: 1,
      MEDIA_ERR_CUSTOM: 0,
      MEDIA_ERR_DECODE: 3,
      MEDIA_ERR_ENCRYPTED: 5,
      MEDIA_ERR_NETWORK: 2,
      MEDIA_ERR_SRC_NOT_SUPPORTED: 4,
      message: "You aborted the video playback",
      status: null
   }

![untitled](https://cloud.githubusercontent.com/assets/4682752/8832893/2a2ff816-3071-11e5-9690-c6654d2ccaaf.png)

<html>
<head>
<link href="video-js.css" rel="stylesheet" type="text/css" media="all" />
<script src="video.js" type="text/javascript"></script>  
</head>
<body>
  <h1>Sample Video 768K</h1>

               <div>
                       <video id="video" class="video-js" width="800" height="600" controls
                               preload="auto">
                               <source src="testntsc768k.mp4" type="video/mp4" />
                       </video>
               </div>  
   
</body>
</html>

**Comment by mmcc** [comment] 2015-07-22 19:36
Can you give us a little more info? I just double checked and it's working fine for me in a Windows 8.1 VM. Checked Windows 7 as well and didn't see any issues.

![screenshot](https://cloudup.com/cp9lnebC2LQ+)

**Comment by wkwood** [comment] 2015-07-23 19:57
I've tried it on 5 different systems but since you're indicating that it's working for you I'll try and isolate it on my side.  Strange, but I've reset IE11 to factory, so it may be some add on that's causing it.

**Comment by mmcc** [comment] 2015-07-23 22:44
So far it's worked on every instance I've tried it on, including a fresh [modern.ie](http://modern.ie) VM. When you say "tried on 5 different systems," do you mean it hasn't worked on 5 *entirely different* Windows 8.1 systems that you've tried? That would certainly be strange...

**Comment by mmcc** [comment] 2015-07-24 20:51
Closing this since I haven't been able to reproduce on my end. Let's continue the conversation in comments though and we can reopen if need be.

**Closed by mmcc** 2015-07-24 20:51 UTC

**Comment by wittnl** [comment] 2016-10-24 18:27
This is caused by a [security setting in the Windows registry](https://blogs.msdn.microsoft.com/askie/2014/12/31/unable-to-play-html5-videos-in-ie/) that explicitly disallows loading media. I came across this issue while troubleshooting a client's corporate security settings:

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\2701` must be set to `0` to allow.

![ie-urlaction_allow_audio_video](https://cloud.githubusercontent.com/assets/1056369/19658412/735fc098-99ed-11e6-9715-87c578fcb480.png)

Reproduced using a Modern.IE VM and setting the registry key above to `3`
