### ISSUE TITLE
How to hide download button

### ISSUE THREAD

**Issue by htank-wang** [videojs/video.js#4271] opened 2017-04-09 16:06 UTC
How to hide download button

**Comment by mister-ben** [comment] 2017-04-10 07:15
Video.js doesn't have a download button. If you see one, you're probably looking at Chrome's native control bar.

**Comment by gkatsev** [comment] 2017-04-11 04:17
This is a dupe of https://github.com/videojs/video.js/issues/4234

**Closed by gkatsev** 2017-04-11 04:17 UTC
