### ISSUE TITLE
first frame poster

### ISSUE THREAD

**Issue by theshine** [videojs/video.js#2662] opened 2015-10-01 11:17 UTC
Is there a way to have the poster be the first frame of the video in a simple way?
This is how I have it set up now but first frame is coming up black.

<video id="example_video_1" class="video-js vjs-default-skin"
  controls preload="auto" width="640" height="480"
    data-setup='{"controls":true, "autoplay": true, "loop": true, "preload": "auto"}'>

Thanks
Mike

**Comment by gkatsev** [comment] 2015-10-01 15:23
Closing as a duplicate of #284. Let's discuss there whether there's a regression and we should re-open it.

**Closed by gkatsev** 2015-10-01 15:23 UTC
