### ISSUE TITLE
[Doc] Event type

### ISSUE THREAD

**Issue by JasterTDC** [videojs/video.js#3109] opened 2016-02-16 10:39 UTC
Hi there,

I'm trying to check all videojs events, but in documentation has no information about it. Can you upload to the repo all types about events information.

For example:
"play", "mute", "volume_change" ... 

Best regards,

JasterTDC

**Comment by mmcc** [comment] 2016-02-19 19:21
Agreed, but this is a dupe of #2681 and #2101.

**Closed by mmcc** 2016-02-19 19:21 UTC
Labels: duplicate
