### ISSUE TITLE
Live hls stream with discontinuities starts behind live 

### ISSUE THREAD

**Issue by alandrei** [videojs/video.js#6975] opened 2020-12-04 08:21 UTC
## Description
On a live stream with discontinuities video.js starts playing behind live by about 1 minute.
With the same stream other players like Clappr or native safari hls player the video starts at live edge.
This can be reproduced constantly [here](https://videojs-http-streaming.netlify.app/?debug=true&autoplay=true&muted=false&minified=true&liveui=true&partial=false&url=https%3A%2F%2Fstorage.googleapis.com%2Fhls-test%2Fandrei-test-gcloud%2Findex.m3u8&type=application%2Fvnd.apple.mpegurl&keysystems=&buffer-water=false).

## Results
![image](https://user-images.githubusercontent.com/8319837/101139542-fa807a80-3611-11eb-968b-1cc42d88df56.png)

On streams without discontinuities the video starts playing at live edge as expected.

### Expected
Video should autoplay from live edge.

### Actual
Video starts behind the live edge by approximately 1 minute

**Comment by gkatsev** [comment] 2020-12-09 19:28
Interesting, I can reproduce. My assumption is that this has to do with the PDT tags and the discontinuities in the stream.

**Comment by alandrei** [comment] 2020-12-10 14:59
Could you elaborate a bit on what do you mean by that? I'm trying to figure out if this is this a video.js issue or it has to do with our stream file (which can be checked at the above link)

**Comment by gkatsev** [comment] 2020-12-11 06:01
I'll ask some of my teammates if they can take a quick look. I have only limited knowledge of these things.

**Comment by alandrei** [comment] 2020-12-15 15:58
A related issue is that the duration is not correct for this scenario. The duration calculated by manually adding the segments in the playlist is `6:37` but the player shows something around `7:11`(visible by hovering the timeline).

**Comment by gkatsev** [comment] 2020-12-15 18:28
That is weird. We assume the main reason why this stream is playing back weirdly is because our PDT support is pretty buggy.
We hope to be tackling our PDT handling next quarter.

**Comment by gkatsev** [comment] 2021-02-09 19:33
This is potentially fixed with https://github.com/videojs/http-streaming/pull/1063, can you take a look? You can see a live preview of it here https://deploy-preview-1063--videojs-http-streaming.netlify.app/

**Comment by DispatchCommit** [comment] 2021-02-18 06:14
@gkatsev seems to fix the issue for me based on some quick tests.

**Comment by gkatsev** [comment] 2021-02-18 06:17
@DispatchCommit thanks for checking!

**Comment by alandrei** [comment] 2021-02-18 06:23
@gkatsev The issue seems to be fixed now. Thanks a lot!

**Comment by gkatsev** [comment] 2021-02-18 06:24
Sweet! Happy to hear.

**Closed by gkatsev** 2021-02-18 06:24 UTC
