### ISSUE TITLE
VideoJS can embed facebook live video?

### ISSUE THREAD

**Issue by aminebk** [videojs/video.js#3840] opened 2016-12-07 19:10 UTC
Hi,

I have tested videojs rtmp with facebook live video, I have embed the rtmp provided by facebook live, but it seems doesn't work with videojs.

Is videojs compatible with facebook live video?

Thanks

**Comment by RodrigoMaster7** [comment] 2016-12-07 19:15
It is not possible, since the .m3u8 of Facebook has domain protection (I think) and it is not possible to play on other websites, but if you try to play the .m3u8 file locally with some program like VLC, if it reaches you run.

(Translated by Google)

**Comment by aminebk** [comment] 2016-12-07 19:33
I think it's possible, since I saw that jwplayer can do it :

`<script data-cfasync='false' type='text/javascript'>
    jwplayer('playerjxJRqLMFuJaA').setup({
    file: 'rtmp://edgetee.xx.fbcdn.net:80/live-md/236606470086361?api=1&b=2000&o=atn2&a=AfBhMfgQjke97QhT',
 aboutlink: '',
        controls: 'true',
        title: 'Live Stream',
        width: '100%',
        height: '500',
        stretching: 'uniform',
        autostart: 'true',
        primary: 'flash',
 skin: 'glow',
 androidhls: 'true',
        
    });
</script>`

**Comment by RodrigoMaster7** [comment] 2016-12-08 06:33
How do you get the RTMP link?

**Comment by aminebk** [comment] 2016-12-08 09:09
I don't know really, I saw that in a website who host facebook live in jwplayer

**Comment by gkatsev** [comment] 2016-12-08 20:13
I'm going to close this as a duplicate of https://github.com/videojs/video.js/issues/3481.
We theoretically could support it but there's a change to the SWF that we need to make to support the RTMP properly.

**Closed by gkatsev** 2016-12-08 20:13 UTC

**Comment by aminebk** [comment] 2016-12-08 21:28
Hi @gkatsev 
So there is actually no chance to play facebook live videos with videojs player? as I don't think we can change the swf file.

**Comment by gkatsev** [comment] 2016-12-08 21:34
We are planning on making the update to the swf at some point. Unfortunately, it's a lower priority. You could always build the swf yourself and tell videojs to use that custom swf.

**Comment by aminebk** [comment] 2016-12-08 21:36
Will be hard for me actually, I'll look for someone who I can pay to do that for me probably.

**Comment by onigetoc** [comment] 2020-01-15 00:03
MediaElement.js did it.
https://www.mediaelementjs.com/
