### ISSUE TITLE
play a new  video , the old video will play  a soon minutes 

### ISSUE THREAD

**Issue by Jan28** [videojs/video.js#4681] opened 2017-10-23 05:33 UTC
function  play(url) {
            var myPlayer = videojs('my_video_1');
            myPlayer.src(url);  
            myPlayer.load(url);  
            myPlayer.play();  
  }

**Comment by mister-ben** [comment] 2017-10-24 18:47
A reproducible test cases would be helpful.

**Comment by Jan28** [comment] 2017-10-26 08:06
I have a video list ,  when  i  change to play a new video ,and invoke the  function **Play**(url), it will play 
the previous video for a few seconds .

**Comment by gkatsev** [comment] 2017-12-01 22:33
What version of Video.js are you working with? What browser? A working *reduced* test case would be super helpful. Answering the questions in the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md).

We've done many things with playlist but we haven't been able to reproduce this. If you are able to provide more information, we can re-open this issue. I'm closing this in the meantime since the last activity was a while ago.

**Closed by gkatsev** 2017-12-01 22:33 UTC
