### ISSUE TITLE
Help  I have a problem now. Need everyone's help

### ISSUE THREAD

**Issue by AccountGc** [videojs/video.js#6130] opened 2019-07-25 09:01 UTC
I'm a Chinese，English level is not very good

I have a problem now. Thank you!

Use videojs to play m3u8 format files, the error is as follows:

![image](https://user-images.githubusercontent.com/46801445/61861126-c5ccc100-aefd-11e9-9109-d410db674ef7.png)

![image](https://user-images.githubusercontent.com/46801445/61861159-da10be00-aefd-11e9-9831-7c3a54b8f522.png)

What should I do?

**Comment by mister-ben** [comment] 2019-07-25 11:54
Closing as a duplicate of #6127

**Closed by mister-ben** 2019-07-25 11:54 UTC

**Comment by AccountGc** [comment] 2019-07-25 13:00
@mister-ben The problem has been solved，Thank you！ If I can, I am willing to give you some funding.
