### ISSUE TITLE
Trubles with icon speed video,icon subtitles,captions and default subtitles,captions

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#3168] opened 2016-03-10 20:09 UTC
Trubles with icon speed video,icon subtitles and default subtitles
It does not work in firefox default subtitles .In Google chrome subtitle icon disappears! A pop-up window does not display video speed numbers. Why not work correctly Version 5.8.0 and 5.8.2? How to fix it? Or again, it will be necessary to switch to the old version ...? And how to make a transparent background subtitles, as well as the position and size of subtitles? 
in the old version I have here is this type of change to the background and the location of the subtitles and it works:
/ * Individual tracks * /
.video-js .vjs-text-track {
   display: none;
   font-size: 1.4em;
   text-align: center;
   margin-bottom: 0.5em;
   line-height: 1em;
   / * Transparent black background, or fallback to all black (oldIE) * /
   / * Background-color-with-alpha * /
   background-color: # 000000;
   background-color: rgba (0, 0, 0, 0.2);

for the new version 5.8.0 is not helping

Thank you in advance for your reply and help !!

**Comment by surikat1978** [comment] 2016-03-10 20:30
the trouble fault site template? or I incorrectly entered data setup or something else?

**Comment by gkatsev** [comment] 2016-03-10 20:40
data-setup is correct, the issue is the the site styles and how it interacts with videojs.

**Comment by surikat1978** [comment] 2016-03-10 20:46
Thank you so much! Let's look at the problem of styles. But not sure what will happen .. Thanks

**Comment by surikat1978** [comment] 2016-03-11 18:48
Delete all unnecessary template styles .. speed window is displayed normally. But the default subtitles are not played on FireFox. In Google Chrome does not display the subtitle window. What do I do not know already ?! And how to change the dark background subtitle text? And change the position of subtitle text down? Maybe version 5.6.0 is more stable? Or is there the same problems will arise? Thank you advance!

**Comment by surikat1978** [comment] 2016-03-14 16:55
gkatsev   No captions window in the browsers Google Chrome, Opera, Amigo, and Yandex !
Only FireFox running a window , but does not work default captions. Tested on version 5.8.0 ; 5.8.2; 5.8.3 //
Now install 5.8.3
Help advice, what to do?

**Comment by gkatsev** [comment] 2016-03-28 21:53
Closing as a dupe of #1880.

**Closed by gkatsev** 2016-03-28 21:53 UTC
