### ISSUE TITLE
video.js 5.10.x can not recover media error

### ISSUE THREAD

**Issue by ruslandinov** [videojs/video.js#3430] opened 2016-07-12 15:16 UTC
We are using video.js with https://github.com/streamroot/videojs5-hlsjs-source-handler and hls.js for HLS playback.

Recently we found that video-js-5.10.7 (latest pre-release) and video-js-5.10.4 (latest release) can not recover from media error(`bufferAppendingError`) on this `https://tv5mondehlslive-i.akamaihd.net/hls/live/250600/4792245510001-5/tv5plusinfo/index.m3u8` stream and abort playback. 

![Image Error in video-js-5.10.7](https://cloud.githubusercontent.com/assets/78303/16770357/e5c9e7dc-484c-11e6-8360-e103a033e8b2.png)

Meanwhile, with video-js-5.8.6 the playback seems to work fine on Firefox, Chrome, Edge and IE11.  The error is still logged in console though, player is able to recover from it.

![Image Ok in video-js-5.8.6](https://cloud.githubusercontent.com/assets/78303/16770371/f89b6ae8-484c-11e6-91d4-8f9414624e08.png)

Our hypothesis is that before video-js-5.8.6 player just failed in case of media error, but now it tries to use a fallback(another source handler?) to recover, and fails because there is none.

Here is a plunk https://plnkr.co/IofoWmfjGuEKaDe3moQ4/ that demonstrates the issue. In its source code you can toggle between video-js-5.8.6/video-js-5.10.4 by commenting corresponding lines.

Could you please give us a hint on what part of CHANGELOG could introduce this issue? Or probably direct us to someone who might help?

**Comment by gkatsev** [comment] 2016-07-25 17:29
Hey, I'm unable to reproduce this. I am getting a bunch of `internalException`s but nothing relating to `bufferAppendingError`. Can you provide more information on what browsers and their versions that you're using? What platforms you're testing on?
Nothing relating to trying a different source on error was added to videojs yet.

**Comment by ironweber** [comment] 2016-08-09 17:19
I am having this exact same issue in Firefox latest release (48) using [videojs5-hlsjs-source-handler](https://github.com/streamroot/videojs5-hlsjs-source-handler). Though it still doesn't work when switching back to video-js-5.8.6. 

I have tried our hls manifest in hls.js's demo page [hls.js demo page](http://dailymotion.github.io/hls.js/demo/) it recovers fine after the `bufferAppendingError` error. It only fails to recover after the `bufferAppendingError` when using videojs5-hlsjs-source-handler.

**Comment by gkatsev** [comment] 2016-08-15 20:41
I'm still unable to reproduce the problem. If you're seeing issues in the hlsjs demo page, then please report the issues against hlsjs. That demo page does not use videojs for playback.

**Comment by gkatsev** [comment] 2016-09-19 22:37
Closing this issue because it's unlikely to require a change to videojs itself. However, we can still continue the discussion here and if it turns out to actually be an issue with videojs, we can re-open the issue.

**Closed by gkatsev** 2016-09-19 22:37 UTC
Labels: needs: confirmation, needs: discussion, needs: more info

**Comment by shoremark** [comment] 2017-02-08 17:50
I have also seen this issue. What do you need to help debug this issue? The issues seems to be difficult to reproduce in my testing but I have reports of it consistently happening.
