### ISSUE TITLE
Time display doesn't update when a new video is loaded

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#1872] opened 2015-02-17 19:30 UTC
1. Create a player on a desktop browser.
1. Play a couple of seconds of video
1. Change the src property to point to a new video

Expected:
The current, remaining, and duration values in the time display on the control bar are updated.

Actual:
The time display in the control bar isn't updated until the next `timeupdate` event.

**Comment by heff** [comment] 2015-02-25 22:24
The individual time components probably need to be updated to listen for the loadstart event and check the time again. I'll confirm this one.

**Comment by sahin** [comment] 2015-05-07 15:20
+1

**Comment by sahin** [comment] 2015-05-07 15:20
@heff we are using video player in some important places, when do u think you guys can fix it?

**Comment by AlicanC** [comment] 2015-05-07 15:32
I am having issues which are probably related to this and #1641. The seek/duration bar sometimes get stuck at 0:00. When that happens, I also keep getting "timeupdate" events when the player is paused.

Since this doesn't happen all the time, I couldn't really find a proper way to reproduce this and check if the problem is caused by Video.js or the YouTube tech.

**Comment by gkatsev** [comment] 2016-07-25 22:07
I think this is fixed via https://github.com/videojs/video.js/pull/3349

**Closed by gkatsev** 2016-07-25 22:07 UTC
Labels: bug, confirmed
