### ISSUE TITLE
Error when changing quality tracks - HLS

### ISSUE THREAD

**Issue by TroyDota** [videojs/video.js#7048] opened 2021-01-19 06:27 UTC
## Description
Switching qualities sometimes causes 
a fatal error.
Which breaks the player and stops all segment loading but still continues to load manifests. ( For HLS )

1. Changing qualities by disabling the other tracks causes this issue.

### Expected
A recoverable error.

### Actual
A fatal error.

### Error output

```
video.es.js?f0e2:41495 Uncaught TypeError: Cannot read property 'hasAudio' of undefined
    at SegmentLoader.hasEnoughInfoToAppend_ (video.es.js?f0e2:41495)
    at SegmentLoader.handleTimingInfo_ (video.es.js?f0e2:41289)
    at onVideoTimingInfo (video.es.js?f0e2:31029)
    at Worker.handleMessage (video.es.js?f0e2:30501)
hasEnoughInfoToAppend_ @ video.es.js?f0e2:41495
handleTimingInfo_ @ video.es.js?f0e2:41289
onVideoTimingInfo @ video.es.js?f0e2:31029
handleMessage @ video.es.js?f0e2:30501
video.es.js?f0e2:41495 Uncaught TypeError: Cannot read property 'hasAudio' of undefined
    at SegmentLoader.hasEnoughInfoToAppend_ (video.es.js?f0e2:41495)
    at SegmentLoader.handleData_ (video.es.js?f0e2:41529)
    at onData (video.es.js?f0e2:30997)
    at handleData_ (video.es.js?f0e2:30440)
    at Worker.handleMessage (video.es.js?f0e2:30485)
hasEnoughInfoToAppend_ @ video.es.js?f0e2:41495
handleData_ @ video.es.js?f0e2:41529
onData @ video.es.js?f0e2:30997
handleData_ @ video.es.js?f0e2:30440
handleMessage @ video.es.js?f0e2:30485
video.es.js?f0e2:41495 Uncaught TypeError: Cannot read property 'hasAudio' of undefined
    at SegmentLoader.hasEnoughInfoToAppend_ (video.es.js?f0e2:41495)
    at SegmentLoader.handleTimingInfo_ (video.es.js?f0e2:41289)
    at onAudioTimingInfo (video.es.js?f0e2:31017)
    at Worker.handleMessage (video.es.js?f0e2:30497)
hasEnoughInfoToAppend_ @ video.es.js?f0e2:41495
handleTimingInfo_ @ video.es.js?f0e2:41289
onAudioTimingInfo @ video.es.js?f0e2:31017
handleMessage @ video.es.js?f0e2:30497
video.es.js?f0e2:41495 Uncaught TypeError: Cannot read property 'hasAudio' of undefined
    at SegmentLoader.hasEnoughInfoToAppend_ (video.es.js?f0e2:41495)
    at SegmentLoader.handleData_ (video.es.js?f0e2:41529)
    at onData (video.es.js?f0e2:30997)
    at handleData_ (video.es.js?f0e2:30440)
    at Worker.handleMessage (video.es.js?f0e2:30485)
hasEnoughInfoToAppend_ @ video.es.js?f0e2:41495
handleData_ @ video.es.js?f0e2:41529
onData @ video.es.js?f0e2:30997
handleData_ @ video.es.js?f0e2:30440
handleMessage @ video.es.js?f0e2:30485
video.es.js?f0e2:100 VIDEOJS: WARN: Problem encountered with playlist 0-source/playlist.m3u8. No starting media returned, likely due to an unsupported media format. Switching to playlist 4-360/playlist.m3u8.
```

#### videojs latest release (npm) 7.10.2
what version of videojs does this occur with?
#### browsers
chrome + new edge
#### OSes
Windows
### plugins
Quality Selector plugin ~ i wrote my own implementation of the HLS quality selector which is the same except it fits more with Vue.

**Comment by gkatsev** [comment] 2021-01-21 17:40
It sounds like it's trying to switch from a rendition that has both video and audio to one that doesn't have audio? Or that some segments in that rendition don't have audio? If so, we currently do not support that.

**Comment by PI3RRE01** [comment] 2021-04-18 23:10
Hi,
I face the same issue when switching quality for a live HLS video

Here are the the jsfiddle to reproduce the issue easily you juste have to play the live and switch randomly on different quality to reproduce the issue ;
- https://jsfiddle.net/nv1wjz3e/  (videojs-http-source-selector 1.1.6)
- https://jsfiddle.net/y4qtw7jr/ (videojs-hls-quality-selector 1.1.4)

It's seems independant of the plugin selector

The problem is not present with version prior or equal to 7.10.0 : https://jsfiddle.net/j1w2m4n7/

Thanks

**Comment by amaroarcast** [comment] 2021-05-26 03:54
I had the same problem. 
I fixed with this: 
<script src="https://cdn.jsdelivr.net/npm/videojs-hls-quality-selector/dist/videojs-hls-quality-selector.js"></script>
<script src="https://cdn.jsdelivr.net/npm/videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels.min.js"></script>

**Closed** 2021-05-26 04:36 UTC
