### ISSUE TITLE
Missing cues on TextTrack

### ISSUE THREAD

**Issue by makker** [videojs/video.js#3089] opened 2016-02-07 18:22 UTC
I'm trying to synchronize an animation to video by setting animation change data to WebVTT as JSON, and listening 'cuechange' events. When 'cuechage' event triggers I read the data from the 'activeCues' property. Then call animation changer function with the data from the cue. The cues change fast. I can have multiple ques per second. The problem is that only part of the cues seems to trigger 'cuechange' event. I made a test with a WebVTT ([Jan.txt](https://github.com/videojs/video.js/files/120829/Jan.txt))
where I had 24 cues per second. With this rate 'cuechange' event triggered only 14 times in 4 seconds, even thought it had 96 cues in that time. There's the traces from triggered cues: [trace.txt](https://github.com/videojs/video.js/files/120832/trace.txt). Notice the change in index between traced cues is 3, 6, or 12. Except between indeces 3 and 4. Not sure if this means anything. 
Do TextTracks have a low refresh rate? Or is there a bug causing this?

**Comment by gkatsev** [comment] 2016-02-08 17:13
Sounds like this is a duplicate of #2979. Both native and our emulated text tracks depend on `timeupdate` which runs at least every 15ms but could run as little as 250ms depending on the browser and conditions. This means that you could get active cues updates a handful of times a second and you need a lot more.
Also, thank you for the example.
Going to close this but mention that you posted an example in the other issue.

**Closed by gkatsev** 2016-02-08 17:13 UTC

**Comment by makker** [comment] 2016-02-10 15:32
@gkatsev, yes, a duplicate. Thank's for the reply. I basically need at least 24 updates per second.
