### ISSUE TITLE
Events list

### ISSUE THREAD

**Issue by oleynikd** [videojs/video.js#2800] opened 2015-11-10 08:10 UTC
Hi,

First if all thank you guys for such a great tool!!!

Where can I find the full list of available events? Like `timeupdate`, `canplay`, `onpause`...
Thanks.

**Comment by kmoskwiak** [comment] 2015-11-10 11:14
This might help: http://docs.videojs.com/docs/api/player.html#Eventserror
And this: https://github.com/videojs/video.js/blob/master/src/js/player.js#L543

**Comment by gkatsev** [comment] 2015-11-10 22:28
Going to close this issue as a dupe of #2681. We should do a better job documenting it, though, all main events are just from the spec: http://www.w3.org/TR/html5/embedded-content-0.html#mediaevents

**Closed by gkatsev** 2015-11-10 22:28 UTC

**Comment by PhatBK** [comment] 2018-11-01 08:10
Hi,
How do I tracking player video behavior from VideoJS ?

**Comment by mayeaux** [comment] 2021-09-24 18:56
Still basically impossible to find on the website docs. I have to google it and then this is the link that comes up.

**Comment by dioramayuanito** [comment] 2021-09-24 23:57
Html5.Events = [
  'loadstart',
  'suspend',
  'abort',
  'error',
  'emptied',
  'stalled',
  'loadedmetadata',
  'loadeddata',
  'canplay',
  'canplaythrough',
  'playing',
  'waiting',
  'seeking',
  'seeked',
  'ended',
  'durationchange',
  'timeupdate',
  'progress',
  'play',
  'pause',
  'ratechange',
  'resize',
  'volumechange'
];

https://github.com/videojs/video.js/blob/4238f5c1d88890547153e7e1de7bd0d1d8e0b236/src/js/tech/html5.js
