### ISSUE TITLE
video in paragraph

### ISSUE THREAD

**Issue by stdex** [videojs/video.js#2433] opened 2015-08-04 12:17 UTC
If i'm append video to paragraph:
http://jsfiddle.net/fenpw0wv/3/
I think it's not fine.

**Comment by mmcc** [comment] 2015-08-04 19:19
My first instinct was "well the `<video>` element shouldn't be in a paragraph tag, but that instinct was [totally wrong](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Flow_content).

**Comment by heff** [comment] 2015-08-05 19:40
I think the issue is that a div doesn't belong inside a paragraph, which is what we use to wrap the player. The browser (chrome/safari at least) finish the first paragraph when they see the end of the div, and then the fall back paragraph is started at the same level as the first paragraph.

Secondly, it doesn't look like we're actually doing anything to hide the fallback paragraph. We're just relying on the video covering it up.

So we should add something to hide the fallback paragraph and that may fix this issue, but in general, you should probably avoid putting the player in a paragraph if you can because the player div may not play nicely in other ways. (This is also the first I've seen any issue with paragraphs in the 5 years of the project, so take that as you will)

**Comment by stdex** [comment] 2015-08-05 21:02
I think that we should show fallback text in div in examples. It's work with nested blocks. http://jsfiddle.net/fenpw0wv/5/

**Comment by OwenEdwards** [comment] 2015-08-05 22:25
Hiding the fallback paragraph is also an accessibility issue - without hiding the paragraph, it is still 'visible' to screen readers. So I'd like to see it fixed for the accessibility milestone, but because of this paragraph behavior, it's more than _just_ an accessibility issue.

**Comment by heff** [comment] 2015-08-06 00:27
Sounds good to me. It might be as easy as adding:

```
.video-js .vjs-no-js {
  display: none;
}
```

Assuming that's enough for accessibility. [The note for .vjs-no-js](https://github.com/videojs/video.js/blob/master/src/css/components/_layout.scss#L118) says IE8 ignores the the `video-js` class, and IE8 is the only place that message would show up anyway. Should be double checked though.

**Comment by gkatsev** [comment] 2017-01-09 23:08
This potentially could be fixed with the `ingest player div` work. Since you could create a span or another element and have videojs use it. It should work, though, styling could be a bit weird.
Haven't tested it out yet.

**Comment by gkatsev** [comment] 2018-01-03 20:03
I wonder if the new `<video-js>` element will help with this, not sure if browsers default to div-like semantics for elements like that.

**Comment by gkatsev** [comment] 2018-01-11 16:38
Seems like it is no longer an issue in the latest versions of Video.js, whether with `<video-js>` element or not.

**Closed by gkatsev** 2018-01-11 16:38 UTC
Labels: bug, confirmed
