### ISSUE TITLE
5.0-rc.2 - black screen / control bar displaced after leaving fullscreen on iOS Safari

### ISSUE THREAD

**Issue by meleyal** [videojs/video.js#2276] opened 2015-06-19 09:08 UTC
Happens on iPhone / iPad iOS 8.3 using Safari.

1. Open test page
2. Click play button
3. Enter fullscreen
4. Exit fullscreen

Expected: Toolbar appears below video
Actual: Toolbar appears at the bottom of the window (on iPad the screen is also black)
Test case: http://jsbin.com/halokodoxo/1/edit?output

![img_0042](https://cloud.githubusercontent.com/assets/15045/8250373/51120b9e-1673-11e5-9fda-2a3939f2d6b7.PNG)

**Comment by gkatsev** [comment] 2015-07-13 20:50
I think this might have been fixed by #2334. Can you please retest?

**Comment by forbesjo** [comment] 2015-07-14 15:14
Still seeing the issue

**Comment by gkatsev** [comment] 2015-07-15 19:00
Going to close this as a dupe of #2350 because that one has more info now.

**Closed by gkatsev** 2015-07-15 19:00 UTC
