### ISSUE TITLE
player.removeRemoteTextTrack(track) Failing

### ISSUE THREAD

**Issue by EZWrighter** [videojs/video.js#2046] opened 2015-04-16 23:25 UTC
Attempting to remove a text track dynamically does not work in Firefox or Chrome.

reduced test case: http://partner.mediamobz.com/caption-test/

The buttons below the player trigger a removeRemoteTextTrack on the player for the current track and then dynamically add a new track.  The new track gets added, but the old track still exists in the menu and within the player.

This test case is running the latest CDN 4.12 version of videojs.

Should be working according to comments here: https://github.com/videojs/video.js/issues/1700

**Comment by EZWrighter** [comment] 2015-04-17 00:01
Another note on this.  Personally, I would like player.src(sources) function to remove any captions that exist in the player.  It would be great if I could pass the player a json object with sources and captions and just have it work :-)  

If I am setting new sources in the player, I would think in most cases the old text tracks would become invalid.

Right now I just need something working so I can use videojs for playlists with captions and not have to dispose/reload on every switch.

**Comment by gkatsev** [comment] 2015-11-17 23:01
Looks like the issue is that `removeRemoteTextTrack` isn't working correctly when called with the response from `addRemoteTextTrack`. It should be working fine if you get the track itself directly from the `textTracks()`.

**Comment by gkatsev** [comment] 2016-04-19 21:21
Fixed by https://github.com/videojs/video.js/pull/3253

**Closed by gkatsev** 2016-04-19 21:21 UTC
Labels: confirmed
