### ISSUE TITLE
Transport controls not showing in full screen mode

### ISSUE THREAD

**Issue by jonlambert** [videojs/video.js#1972] opened 2015-03-24 11:52 UTC
I've scaffolded a new plugin using Yeoman. When browsing to the generated example.html file, I've noticed making the player full screen causes the control bar to vanish, leaving only the video. This happens regardless of mouse movement. The issue occurs in both Safari and Chrome.

**Comment by mmcc** [comment] 2015-03-24 17:00
Can you reproduce this outside of the Yeoman-generated project? If not, I think this issue belongs with the [generator](https://github.com/dmlap/generator-videojs-plugin).

**Comment by mmcc** [comment] 2015-04-01 00:41
Closing this because we never heard back, but comment if you think it should be reopened.

**Closed by mmcc** 2015-04-01 00:41 UTC
