### ISSUE TITLE
Try next available tech on MEDIA_ERR_SRC_NOT_SUPPORTED : 4

### ISSUE THREAD

**Issue by wannabefro** [videojs/video.js#2287] opened 2015-06-25 14:24 UTC
Recently we encountered an issue when using HTML as the first option in our techOrder with only an mp4 video source available.
On Firefox latest (38) on Windows XP, the HTML player throws a media error of code 4 (MEDIA_ERR_SRC_NOT_SUPPORTED : 4) when attempting to play an mp4. If HTML were the only option for the tech order I'd expect this error but since the tech order was ['HTML', 'flash'] I'd expect videojs to attempt to playback the video using the flash tech if the html tech fails. 
We ended up using a similar approach to https://github.com/videojs/video.js/issues/1315#issuecomment-47296267. 

I was wondering if there was a better approach to handling this scenario? If not would you be interested in a PR that introduced similar functionality into videojs (i.e. try the next available tech option from tech order if the player receives an error code of 4)

**Comment by wjordan** [comment] 2015-07-15 14:38
I for one would be very interested in a PR that introduced such functionality into videojs. I have had to use a similar workaround in the past, I don't know any other approach currently available.

**Comment by heff** [comment] 2015-07-15 16:55
This topic has been brought up quite a few times in the issues. It's not a simple problem to solve well, but any PRs are absolutely welcome.

Ultimately the best solution in my opinion is to encode/re-encode your MP4s to support Firefox. If this error is coming up then it's using an encoding that Firefox doesn't support, and it's not too difficult to create MP4s that Firefox does support. If it's an encoding error you can always try running it through [Zencoder](http://zencoder.com) to fix it.

**Comment by wannabefro** [comment] 2015-07-23 09:56
My feelings are that given a tech order of `[html5, flash]` and a source file of type mp4, if the video element raises an error 3 or 4 while trying to playback the video then videojs should automatically attempt to load the flash tech and replay the video. 

Given that flash supports the mp4 codec and that it is in the tech order, that to me feels like the expected behaviour. However those are just my $0.02 on the matter

**Comment by gkatsev** [comment] 2016-03-28 22:20
Closing this as a duplicate of #1316.

**Closed by gkatsev** 2016-03-28 22:20 UTC
