### ISSUE TITLE
Player reinit issue

### ISSUE THREAD

**Issue by Sahiltuteja** [videojs/video.js#6944] opened 2020-11-12 13:10 UTC
## Description

When we initialized the instance of same player then video is not played

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Play video in modal
2. Press esc to close the modal that having video for play
3. Open the modal again with same but video will not play. Just blank screen

### Expected
Please describe what you expected to see.

Should play

**Comment by mister-ben** [comment] 2020-11-16 07:57
How are you disposing and reinitialising the player?

**Comment by Sahiltuteja** [comment] 2020-11-17 05:37
player.dispose(); to disposing.. but getting error 
" Cannot read property 'chaptersButton' of null
    at t.e.getChild (video.min.js:12) "

**Comment by gkatsev** [comment] 2021-02-17 01:08
Please provide a reduced test case, unfortunately, we cannot reproduce and cannot help otherwise. Closing for now, but can re-open if we get more info.

**Closed by gkatsev** 2021-02-17 01:08 UTC
Labels: outdated

**Comment by rentcare85** [comment] 2021-02-17 01:10
Great work Gazz

________________________________
