### ISSUE TITLE
Livestream won't restart after pressing pause

### ISSUE THREAD

**Issue by Tralapo** [videojs/video.js#1920] opened 2015-03-03 15:13 UTC
I'm using Video.js to stream several live-webcams on websites. So, that means: a rtmp stream for the desktops and an Apple HLS stream for mobile devices.

That system works like a charm, thanks for that. But there seems to be one little annoying bug in the system. It's related to pausing the stream.

If the stream is running and you press pause, it's impossible to start again (desktop/flash), you have to refresh the page. On mobile devices with HLS, it starts again. but just where it ended. So say I pause my livestream and press start again 10 minutes later, I see images from 10 minutes ago. Not how it's supposed to be. 

In video.js 4.11, there was a way to go around this problem, found on [StackOverflow](https://stackoverflow.com/questions/25446868/videojs-doesn%C2%B4t-play-after-pause-rtmp-live-stream) by using the following javascript below the player:

```javascript
<script type="text/javascript">
var myPlayer = videojs('videoID');
videojs("videoID").ready(function(){
  var myPlayer = this;
  myPlayer.on("pause", function () {
    myPlayer.on("play", function () {
      myPlayer.load (); 
      myPlayer.off("play");
    });
  });
});
</script>
```

Not ideal ofcourse, but it worked. Now, with 4.12 released recently, this solution no longer works. When you press play after pause, it shows the poster and the big play button, but you can't press it. Just nothing happens.

The threat at StackOverflow [does offer this other solution](http://stackoverflow.com/a/28632288), but for that you have to use the .dev.js and I would like to keep using the latest CDN version. I must admit I'm not a pro in coding, but could this be the solution then?

**Comment by mmcc** [comment] 2015-03-03 17:50
> So say I pause my livestream and press start again 10 minutes later, I see images from 10 minutes ago. Not how it's supposed to be.

You can do things differently, such as with a [sliding window playlist](https://tools.ietf.org/html/draft-pantos-http-live-streaming-07#section-6.2.2), but this behavior is as expected with HLS. HLS is simply a manifest of segments (literally the old [Winamp](http://www.winamp.com/) playlist format) that the server appends to and the player continues to request. If the player pauses, the manifest will continue to get appended to, but when the player plays again it will just continue where it left off in the manifest. 

Basically, that hack you're doing isn't crazy. When you create the play event listener in the pause event, you can use `one` instead of `on` so you only create a one-time listener and don't need to de-register the listener (either way works, just a heads up).

If you're using HLS anyway and you're happy with it, I would honestly suggest dropping RTMP support and using [contrib-hls](https://github.com/videojs/videojs-contrib-hls). To be frank, we're investing a lot more time in HTTP streaming (DASH and HLS)  than we are RTMP. The workaround the SO post suggests should work with the CDN version if you're willing to override the play method on the Flash prototype like that. Use at your own risk, ymmv, etc etc :)

**Comment by Tralapo** [comment] 2015-03-03 18:03
I'm aware of the way HLS works, but in players like JWplayer, it jumps to the most recent part when hitting play after pause (just like it does when you press play the first time). In my eyes that's the way it's supposed to be. You're saying it's just not possible to pause and play a livestream. I think it should be possible.

>Basically, that hack you're doing isn't crazy. When you create the play event listener in the pause event, you can use one instead of on so you only create a one-time listener and don't need to de-register the listener (either way works, just a heads up).

Thanks. I have to say I don't understand javascript very well, so I was just happy that it worked. You have any idea why this stopped working for 4.12? That was one of my points, I can't upgrade now.

> If you're using HLS anyway and you're happy with it, I would honestly suggest dropping RTMP support and using contrib-hls. To be frank, we're investing a lot more time in HTTP streaming (DASH and HLS) than we are RTMP.

I didn't see that one, I have to admit. I will check that for sure. But again, if it can't pause and re-start to the latest part of the stream, it's no use.

>The workaround the SO post suggests should work with the CDN version if you're willing to override the play method on the Flash prototype like that. Use at your own risk, ymmv, etc etc :)

Don't know how ;) Will stick with 4.11 then.

**Comment by mmcc** [comment] 2015-03-19 01:17
Honestly I think this is probably a better fit for the [contrib-hls](http://github.com/videojs/videojs-contrib-hls), but we can do some research here before punting. @dolartoday were you using contrib-hls?

The big question is, how do the players that natively support HLS handle a live stream. If you open this [NASA test stream](http://www.nasa.gov/multimedia/nasatv/NTV-Public-IPS.m3u8) in Safari or on an iPhone, watch for a bit, then pause...when you play again you'll be where you paused. This is not a Video.js bug, this is how the native player handles HLS playback.

That being said, I put together a [reduced test case](http://jsbin.com/quguwaqasi/2/edit) (this one using a standard MP4) with some changes to the code you're trying to use. If you're calling `load()` and you want playback to begin immediately after, you should subsequently call `play()`. So, add the NASA live stream above to a [similar example](http://jsbin.com/padutoxoku/1/edit) and you have the behavior you're looking for.

Regarding the RTMP issue, as I said before, RTMP support is *really* low on the list of priorities. Your fix doesn't really work in the wild because it's pretty specific to this issue, but as mentioned, you can easily override the Flash prototype in almost the exact same way you're editing the dev version of VJS.

```javascript
// Sometime after videojs is loaded in the page
videojs.Flash.prototype.play = function(){
    this.el_.vjs_load();
    this.el_.vjs_play();
};
```

I originally re-opened this so we could verify whether or not we were causing an issue with the native player, but that does not appear to be the case so I'm going to close this again. If you have other comments about this specifically, @Tralapo, please comment on this thread so we can revisit it rather than opening a new issue.

@dolartoday - Does this help answer your question as well?

**Closed by mmcc** 2015-03-19 01:17 UTC

**Comment by Tralapo** [comment] 2015-03-19 06:25
But, again, any idea why this solution does work fine for 4.11 but not for 4.12?  I'm fine using an ugly solution like that, but I want it to work for 4.12 then.

```javascript
<script type="text/javascript">
var myPlayer = videojs('videoID');
videojs("videoID").ready(function(){
  var myPlayer = this;
  myPlayer.on("pause", function () {
    myPlayer.on("play", function () {
      myPlayer.load (); 
      myPlayer.off("play");
    });
  });
});
</script>
```

**Comment by Tralapo** [comment] 2015-03-19 06:31
I see the updated code you use in the example seems to work @mmcc, thanks. Will take a look at that.

**Comment by mmcc** [comment] 2015-03-19 07:18
Cool! Glad I could at least patch things up for now. If this is something we're going to fix, it should probably still be handled in the hls plugin  (since it would alter native behavior). It's probably a common enough request that it should at least be an option. 




Re: version 4.11, I'm not sure why that was working before. With your initial sample code I couldn't reproduce down to 4.10 I believe, so I'm at a loss. 



—

**Comment by dolartoday** [comment] 2015-03-19 18:02
@mmcc your examples made me understand what was wrong. A "load" is required after a pre-roll or mid-roll is finished, so the HTS stream can be resumed. This seems to work on my desktop, but I'm unable to make it work on my mobile.

I do realize that my specific case/scenario is probably rare. I'm doing LIVE HLS + Advertising. I'll continue playing to see if I can figure out what the problem is on mobile.

Not using contrib-hls.. yet, I'll experiment with it later.

Again, I believe the problems we are reporting are specific to cases were a HLS live stream needs to be resumed either after hiting pause OR after a pre-roll / mid-roll ads loads.

**Comment by mmcc** [comment] 2015-03-19 18:05
@dolartoday you might want to try listening to ad finished events (assuming the plugin provides them) and do something along the same lines. I don't know why listening for play isn't working, but it's worth a shot.

**Comment by dolartoday** [comment] 2015-03-19 19:05
I was able to fix (for desktop only) following your advice



                // What happens after an ad is shown?
                player.on('adend', function() {
                        player.load();
                        player.play();
                });




However, mobile is still a no go.. It will load the pre-roll but it will stay there. Might be an issue with the plugin I guess. Will contact the developer

Here's the LIVE demo I'm using:

https://dolartoday.com/player/demo.html

**Comment by Tralapo** [comment] 2015-03-20 19:29
Last point, @mmcc. Your solution works, as said:
```javascript
    var myPlayer = videojs('my_video_1', {}, function(){
      var player = this;
      player.on("pause", function () {
        player.one("play", function () {
          player.load();
          player.play();
        });
      });
    });
```
But I have 7 video's on my page, and now I'm just using the above code 7 times. Is there a way I can 'speak' to all 7 video's at the same time?

Same goes for the standard options within Video.JS. I would like to remove the data-setup from all seven video's and just set the settings for all of them one time. The docs offcourse speak of this:
```javascript
videojs("example_video_1", { "controls": true, "autoplay": false, "preload": "auto" });
``` 
But I would like to use that line for all 7 players at once. Is it even possible? Would be a good thing to explain in the docs.

**Comment by Tralapo** [comment] 2015-03-31 21:26
Nobody can help me with this? How I can set the techorder and controls stuff for all 7 video's at once? I can't get an array to work.

So to be clear: I would like to use this snippet for 7 players at once, and not having to copy/paste it 7 times on one page. 

```javascript
videojs("CamTest", {"techOrder": ["flash", "html5", "other supported tech"], "nativeControlsForTouch": true, "controlBar": { "muteToggle": false, "volumeControl": false, "timeDivider": false, "durationDisplay": false, "progressControl": false } });
````

**Comment by mmcc** [comment] 2015-03-31 23:00
You can set global options on the Video.js object. 

```js
videojs.options = { controls: true, autoplay: false, preload: "auto" };
```
As to not repeating the anonymous ready function event, why not name it and just pass that on initialization?

```js
function yourSweetReadyFunc() {
  var player = this;
  player.on("pause", function () {
    player.one("play", function () {
      player.load();
      player.play();
    });
  });
};

var myPlayer = videojs('my_video_1', {}, yourSweetReadyFunc);
```

You still need to pass it to players on initialization, but this would reduce the amount of copypasta while still being explicit about what's happening.

**Comment by Tralapo** [comment] 2015-04-01 11:14
yourSweetReadyFunc does work, sweet!

The first part about videojs.options doesn't work:

```javascript
videojs.options = {"techOrder": ["flash", "html5", "other supported tech"], "nativeControlsForTouch": true, "controlBar": { "muteToggle": false, "volumeControl": false, "timeDivider": false, "durationDisplay": false, "progressControl": false } };
```

**Comment by mmcc** [comment] 2015-04-03 01:25
Ah right, this is because I was being dumb. If you override all of the default options, you're going to break the player. You need to either set new options and merge them with `videojs.options`:

```js
var myOptions = { "techOrder": ["flash, "html5"] }
_.merge(videojs.options, myOptions); // lodash for simplicity, you can merge however you'd like.
```

Or, you can avoid the merge and just set options individually:

```js
videojs.options['techOrder'] = ["flash", "html5"];
```

Or, another option is to just do like I told you with `yourSweetReadyFunc` and create an options object that you pass to each new player.

```js
var coolOptions = {"techOrder": ["flash", "html5", "other supported tech"], "nativeControlsForTouch": true, "controlBar": { "muteToggle": false, "volumeControl": false, "timeDivider": false, "durationDisplay": false, "progressControl": false } };
videojs('vid1', coolOptions, yourSweetReadyFunc);
videojs('vid2', coolOptions, yourSweetReadyFunc);
videojs('vid3', coolOptions, yourSweetReadyFunc);
```

**Comment by Tralapo** [comment] 2015-04-03 10:55
Works @mmcc. Sweet and cool!

**Comment by harrydoors** [comment] 2015-07-08 05:41
I had the same problem. 
I just assigned back the src. That's it.
 
example:
		videojs("my_videojs_player").ready(function(){
			myPlayer = this;
			
			myPlayer.on('play', function() { 
				myPlayer.src(arrSrc);
			});
		});

....
		var arrSrc = [
		  { type: "rtmp/mp4", src: "rtmp://mypath/mp4" },
		  { type: "rtmp/mp4", src: "rtmpt://mypath/mp4" },
		  { type: "application/x-mpegurl", src: "http://mypath/path/to/video.ogv" }
		];

**Comment by Tralapo** [comment] 2015-07-20 15:42
Sorry to bump up this issue again @mmcc, but your previous answers where so good. I'm now trying to apply MPEG-DASH with dash.js and contrib-dash and restarting doesn't work there either. 

Maybe I should open a issue over at contrib-dash, but I tought this would me more relevant because it's easy to look back at the solution used before.

With MPEG-DASH, yourSweetReadyFunc won't work. If I press pause and play after that, the console shows some sort of 'blob' url and I get a 404.

**Comment by onigetoc** [comment] 2017-02-22 06:26
If found two way.

```
    var myPlayer = videojs('my_video_1', {}, function(){
      var player = this;
      player.on("pause", function () {
        player.one("play", function () {
        player.currentTime(999);
        });
      });
    });
```


```
    var myPlayer = videojs('my_video_1', {}, function(){
      var player = this;
      player.on("pause", function () {
        player.one("play", function () {
          player.src({"type":player.currentType(), "src":player.currentSrc()});
          player.play();
        });
      });
    });
```
