### ISSUE TITLE
Captions not working in IE9

### ISSUE THREAD

**Issue by jeroenverfallie** [videojs/video.js#1479] opened 2014-09-04 10:32 UTC
First of all, this issue occurs on the example video, on the frontpage of http://www.videojs.com/ - the subtitles do not load in IE9.

We load our captions using the `<track>` tag like this:

```html
<track kind="captions" src="/path/to/caption.vtt" srclang="en" label="English" default>
```

After a lot of debugging, we found out that the `dev tools` in IE are unable to show the `response body`, even tho the `response header` shows the correct content-length.

## Testcase on ie9:

![image](https://cloud.githubusercontent.com/assets/1143308/4147500/39fa6a2e-3419-11e4-9857-a0a4d6879e4b.png)
![image](https://cloud.githubusercontent.com/assets/1143308/4147505/485def32-3419-11e4-95e9-5424936ee657.png)

## Identical testcase on ie10:

![image](https://cloud.githubusercontent.com/assets/1143308/4147530/6eb8fa96-3419-11e4-894e-00e30c5ea846.png)
![image](https://cloud.githubusercontent.com/assets/1143308/4147538/7d12aed4-3419-11e4-81c2-80c876f4522e.png)

## Notes

VideoJS does create the html tags for the captions, but they remain empty throughout the playback.
**Important** to note is that this issue does not occur on a **local** environment (grunt connect).

We tried the `CR` `LF` possible solution hinted in #156 to no success.

**Comment by bschi** [comment] 2015-02-04 15:32
Hey there,

I have a similar problem with our srt subtitles in IE8 & 9. The srt's are embedded in a structure attribute for our video options object.

structure: '<video id="videod159e7648" width="910" height="513" class="video-js vjs-default-skin"><source src="mediafile/250314_910x512.mp4" type="video/mp4"></source><track kind="Subtitles" src="mediafile/250314_910x512.srt" label="On" default="default"></track></video>'

The following error MESSAGE only occurs in IE11 emulation mode as IE9 / 8:
SEC7120: Origin http://localhost not found in Access-Control-Allow-Origin-Header. 

In IE9 within a virtual machine no error is shown, but also no subtitles - So I guess it's the same problem.

If I add an .htaccess file to our project with the content:
Header set Access-Control-Allow-Origin "*"

The Problem is solved - but this solution can only be used for apache machines.

A fix would be appreciated.

**Comment by Globulopolis** [comment] 2015-02-04 17:11
@bschi look at the second post http://serverfault.com/questions/162429/how-do-i-add-access-control-allow-origin-in-nginx

**Comment by gkatsev** [comment] 2015-03-09 21:54
Can you please retest with latest videojs? It has updated vtt text track support.
As for the Access-Control-Allow-Origin issue: there's nothing we can do about that. If the server doesn't set the right headers, we cannot read the files.

**Comment by gkatsev** [comment] 2015-03-09 22:04
Actually, I'm going to close this for now. Please let us know if the new version fixes it or not and if it didn't we can reopen and take another look.

**Comment by EZWrighter** [comment] 2015-04-22 23:04
Same problem with latest code on IE9.  Correct CORS Headers set as Chrome and other browsers work without issue.  With the latest videojs CDN version, IE 9 gives the same network response that the original poster shows.

**Comment by EZWrighter** [comment] 2015-04-22 23:07
My rough guess right now is that IE9 supports html5 video, but not vtt captions directly.  That support did not come until IE10.  If captions are present on IE9, they either need to be emulated or flash tech should be used instead of HTML5.  VirtualBox and microsoft's free developer images are great for easy testing of any of the IE versions.

**Comment by EZWrighter** [comment] 2015-04-22 23:54
Poking around in the source for videojs I noticed some examples with tracks and this following them:
`<!-- Tracks need an ending tag thanks to IE9 -->`
I am inserting tracks dynamically via javascript addRemoteTextTrack(track).
Maybe the text track element is not getting inserted correctly from the html5 tech?

Pot shots I know...but hopefully something is helpful there.

**Comment by EZWrighter** [comment] 2015-04-23 16:41
Ok, so I forced flash tech first on IE9 and I still get the same behavior.  One thing I didn't mention is that it is really hit and miss on whether the captions work(vvt file loads) or not.  Could their be some kind of timeout that would cause the caption file to load intermittently?  Can you point me toward what script would be responsible for getting the vtt file in IE 9?  Any other tests that might help to pinpoint the issue?

**Comment by heff** [comment] 2015-04-23 20:37
@gkatsev could this be related to the track loading issue?

**Comment by gkatsev** [comment] 2015-04-23 20:41
Actually, I wonder if it's related to the fact that IE8 and IE9's CORS don't work properly.
If the caption file is hosted on the same domain as the page, does it work?

**Comment by EZWrighter** [comment] 2015-04-23 20:45
It is and I have debugged enough to believe I know why.  The dev version of the same build actually works flawlessly.  I think that the minifier is removing the dummy/empty functions that are setup for IE9 on XHR requests.  Line 100 & 101 in xhr.js.

I don't think it is CORS as it is intermittent timing kind of issue.  Which is the same behavior being reported here: http://cypressnorth.com/programming/internet-explorer-aborting-ajax-requests-fixed/  You guys reference that in the xhr page.

**Comment by gkatsev** [comment] 2015-04-23 20:48
D'oh. [Those lines](https://github.com/videojs/video.js/blob/6786b70da104e066669ba18c51919337260380e0/src/js/xhr.js#L90-L96) probably need to be updated to use bracket notation, i.e. `request['onprogress'] = function() {}`.
@EZWrighter do you want to submit a PR with that change against the `stable` branch so we can release a patch update?

**Comment by EZWrighter** [comment] 2015-04-23 20:59
I couldn't get the build to actually work...so if you have a working clone of the repository, I would appreciate it if you can just make it happen.  Grunt was failing when trying to build, with an error about the uglify task.  This was from a clean clone of the repository, pulled yesterday.  Guess I need to file something separate for that :-(

**Comment by gkatsev** [comment] 2015-04-23 21:02
Make sure to checkout the stable branch. Master right now is a but in flux because of on-going 5.0 work.

**Comment by gkatsev** [comment] 2015-11-10 23:16
I think that this isn't an issue in 5.0. Can someone verify? Thanks.

**Comment by gkatsev** [comment] 2016-02-24 21:20
No response and it is working as far as I can tell. Closing.

**Closed by gkatsev** 2016-02-24 21:20 UTC
Labels: browser bug, bug, confirmed
