### ISSUE TITLE
Double click -> Full screen

### ISSUE THREAD

**Issue by campones** [videojs/video.js#4948] opened 2018-02-12 11:55 UTC
Hi there

this is more a feature request.

Would it be possible that  a double click make the player go full screen? this is very intuitive and users are usually used to this behavior 

Thanks

**Comment by campones** [comment] 2018-02-13 20:04
works great, thanks!

**Comment by richardbushell** [comment] 2018-02-14 14:28
+1 for making this the native functionality...

**Comment by leventmuslim** [comment] 2018-03-05 17:06
how to apply this code snippet at the final phase?
Because I know that <script>player.on('dblclick', function() { player.requestFullscreen(); });</script> won't work and searching internet to see the final example is not useful on such things. I tried and failed many times.

**Comment by campones** [comment] 2018-03-05 17:15
yes it does work perfectly, just change player.on with the name of your videojs player id

**Comment by leventmuslim** [comment] 2018-03-05 17:30
I tried and nothing happened one more time. I tried putting it between <script> tags. I tried with "" hashes between <script> tags. I tried without "" dashes! I tried without <script> tag. And I got fed up

Embedding video is my best option I see it clearly now. Copy code, paste code, easy as 1-2-3! 
I'd better quit trying and this last post should be my resignation. Thank you for your reply anyway. 
I'm having more headaches and more sleepless nights than my daily job gave me in my life.

But a very happy day for me is coming rapidly that soon machines will do all the coding part and I'll watch all coders go out of business while scratching my belly in front of the tv. I'd better get back to my life my friend. Then as a director I'll take the job applications and roles will change.

**Comment by campones** [comment] 2018-03-05 17:35
ex: 

<video id="myplayer" class="video-js vjs-default-skin vjs-live vjs-live-display vjs-big-play-centered" width="100%" height="100%" poster="/img.jpg" autoplay controls preload="auto" data-setup='{}'>

<script>var vid1 = videojs('myplayer'); vid1.on('dblclick', function() { vid1.requestFullscreen(); }); vid1.on('dblclick', function() { vid1.exitFullscreen(); });</script>

script need to be after the video tag, it doesn't work otherwise (would give a function not defined)

**Comment by leventmuslim** [comment] 2018-03-05 18:31
I thing basic video help of the wordpress with mediaelement.js is what I'm supposed to use my friend. I'll try your recommendation for sure but it'll be the last one I do with Videojs. Or I pay load of dollar to a foxy video hosting website idk
I don't want to get excited again about videos on my website again and try to solve every other problem I come across. Because that means more sleepless nights. 
While trying to understand how things works efficiently, I have postponed living my life more than enough already :( Thank you so much for help. I have designed a beautiful css file for the Videojs btw, if you like I can give to you, maybe you could use it somewhere

**Comment by leventmuslim** [comment] 2018-03-05 18:53
Here is the code to my whole page. This is where I got so far. I have installed your code in here but again. Couldn't make it work for me. I mean  there are more than enough signs already that's why I quit trying.

![plyr](https://user-images.githubusercontent.com/10663138/36993697-ab1a7d3e-20bf-11e8-813c-a8c2c4d0a7c7.jpg)

**Comment by gkatsev** [comment] 2018-03-05 18:56
Looks like the issue is that you have both an exit and a request fullscreen handlers for `dblclick`. They will both end up firing and thus doing nothing. You'll want to check whether we're fullscreen or not in the handler.
```js
vid1.on('dblclick', function() {
  if (vid1.isFullscreen()) {
    vid1.exitFullscreen();
  } else {
    vid1.requestFullscreen();
  }
});
```
Hope that helps.

**Comment by campones** [comment] 2018-03-05 19:03
mine is working fine gkatsev but I ll try your code anyway, thanks

**Comment by campones** [comment] 2018-03-05 19:05
levent your player id and the var is different, so ofc it won't work

**Comment by gkatsev** [comment] 2018-03-05 19:05
I think it's mostly if you want to toggle fullscreen or not. My initial example only went into fullscreen but it never closed it if you double clicked once you're already fullscreen.

**Comment by campones** [comment] 2018-03-05 19:06
yes it does close once you are fullscreen!

**Comment by gkatsev** [comment] 2018-03-05 19:11
Oh, didn't even notice. JavaScript variable names cannot have dashes in them. You'd want to drop the `-` or something. Also, you're using both `data-setup` for automatic initialization, so, you could just do something like:
```js
var player = videojs.player['valkyr-trlr];
player.on('dblclick', function() {
  if (player.isFullscreen()) {
    player.exitFullscreen();
  } else {
    player.requestFullscreen();
  }
});
```

**Comment by leventmuslim** [comment] 2018-03-05 19:15
Of course it will solve my problem. The real issue here is I'm too old to learn coding from ground up.
Once we get through this another one will come up. I can't speak your language @gkatsev  
What you saw in 2 seconds take me hours to figure place into the code cause I don't find convinient steps to lead me. 
Answer I need sometimes is like that; "erase this replace with this"...  Enters,exits, requests.. I'm an area director in a company who can read annual reports in 2 seconds not codes. The way you answer is foreign language to me really. I have even visited your personal website to figure out which languages you are capable of so that in the future I could guess what next step you will take on your next Videojs update.
I was very keen honestly but now I'm sweating and having headaches instead. Unless you are willing to write with me personally until I get to figure out the basics on where to put codes inn codes and which order, coz I can't go on anymore with this project with so many frustrations on every step I take.

**Comment by campones** [comment] 2018-03-05 19:18
lol this is a bit offtopic, I m not a coder myself but I take time to read the good guys just to be able to accomplish what I want.. without complaining.. if that is not acceptable to you, just do something else :)

**Comment by leventmuslim** [comment] 2018-03-05 19:21
FYI @campones, this is SOMETHING ELSE for me my friend. I'm managing a security company's Istanbul headquarter operations. Assume less, think longer than you speak.

**Comment by gkatsev** [comment] 2018-03-05 19:41
We're sorry for the trouble @leventmuslim. We work hard to try to make using Video.js and all of its associated features easy and workable for everyone, but Video.js is a technical product that may require some knowledge of coding and web development to use (particularly when using some custom features that aren't provided by default).

While we always try to improve our ease-of-use and documentation, if you are not experienced with coding, there are places that manage the coding, deployment, and hosting of video players for you, often called [Online Video Platforms (OVPs)](https://en.wikipedia.org/wiki/Online_video_platform).

**Comment by leventmuslim** [comment] 2018-03-05 20:17
No need to be sorry at all. I totally understand the reason behind it. 

Well, in order to clearify myself I need to say, I can somehow manage my website on AWS, and on namecheap's terrible host with a DB at Redis Cloud and smurfs like these. Coz unfortunately seeing a "particular person" clicks "like" faster than I read your msg made this info necessary ;)

My technical knowledge is not so high on video field, but my expectations are not very high either. I have come across with docs from years back during searching, from this point of view I can say that Videojs docs have improved way too much than in the past. I'm sure this will go on to improve. 

For me, it would be great if I could find the coding example of the whole page more often (like my screenshot above), instead of snippets from a webpage. This way I could easily figure out where to insert the code you gave just me. Thanks for the help btw, it was really detailed and laser focused.
...of which I have come so far by the help of such snippet examples given here and there and putting things together for myself compiling with my old knowledge.

I wanted to use Videojs at first place. See, I just didn't want to install lots of plugins for everything to not to get my website bulky, or embed video from a third website and get my visitors angry because of the popping ads on everywhere they click. I'll just chill down for a while since I find a friend of mine to have him convinced to spend a weekend with me by the computer. Apart from using custom features experience you mentioned, I think that would do the trick for my considerably low demands as a last stop before turning on to a OVP.

**Comment by gkatsev** [comment] 2018-06-18 19:29
By the way, we've decided that Video.js should handle this and have a PR for this that's in progress #5148

**Closed** 2018-07-03 16:02 UTC

**Comment by luxueyan** [comment] 2019-09-24 02:00
But  dbclick dosen't work with videojs--flash

**Comment by mister-ben** [comment] 2019-09-25 06:55
More work would be needed to support the Flash tech, and with Flash's end-of-life next year I don't think anyone would prioritise adding features to Flash right now.

**Comment by luxueyan** [comment] 2019-09-25 11:29
You are right！I have made this work by using a mask dom over the flash player.Then click the mask dom ,use documentElement.requestFullscreen on its parent dom instead of player. requestFullscreen.
