### ISSUE TITLE
Ios 10 Safari play has style issues

### ISSUE THREAD

**Issue by xiabin19891230** [videojs/video.js#3732] opened 2016-11-02 07:55 UTC
## Description
The player show two layer controls.
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.open your demo links   in safari on ios10.x.
2.click the  play button 
3.in normal screen model,touch the center of player,you will see two layer controls.

## Additional Information
Please include any additional information necessary here. Including the following:
#### browsers
safari 
#### OSes
ios10.x

**Comment by xiabin19891230** [comment] 2016-11-02 07:55
2016年11月02日15:55:40

**Comment by hartman** [comment] 2016-11-03 15:08
> 3.in normal screen model
What's normal screen model ?

Please try to describe your problem as extensive as possible, if possible, add a screenshot.

**Comment by tooodooo** [comment] 2016-11-11 19:16
I have the same issues. 

I have set `data-setup='{"nativeControlsForTouch": false}'`, it doen't work on IOS 10.1.1.

![img_0836](https://cloud.githubusercontent.com/assets/6067607/20227151/0889337e-a886-11e6-8616-d56c01b462e8.JPG)

**Comment by xiabin19891230** [comment] 2016-11-17 06:24
I have the same issues.

**Comment by DerekZiemba** [comment] 2017-01-10 14:14
```
video::-webkit-media-controls, 
video::-webkit-media-controls-panel,
video::-webkit-media-controls-panel-container,
video::-webkit-media-controls-play-button,
video::-webkit-media-controls-volume-slider-container,
video::-webkit-media-controls-volume-slider,
video::-webkit-media-controls-mute-button,
video::-webkit-media-controls-timeline,
video::-webkit-media-controls-current-time-display,
video::-webkit-full-page-media::-webkit-media-controls-panel,
video::-webkit-media-controls-timeline-container,
video::-webkit-media-controls-time-remaining-display,
video::-webkit-media-controls-seek-back-button,
video::-webkit-media-controls-seek-forward-button,
video::-webkit-media-controls-fullscreen-button,
video::-webkit-media-controls-rewind-button,
video::-webkit-media-controls-return-to-realtime-button,
video::-webkit-media-controls-toggle-closed-captions-button,
video::-webkit-media-controls-start-playback-button {
	display: none !important;
	-webkit-appearance: none;
}
```

This gets rid of the controls, but there's another issue.  When exiting fullscreen safari locks up and you need to force close it.

**Comment by gkatsev** [comment] 2018-06-18 18:40
I'm unable to reproduce this on iOS 10 and latest Video.js.
If there is still a problem with newer versions of Video.js please open a new issue.
Thanks.

**Closed by gkatsev** 2018-06-18 18:40 UTC
