### ISSUE TITLE
seeking when paused bug

### ISSUE THREAD

**Issue by H1D** [videojs/video.js#1073] opened 2014-03-11 15:31 UTC
Timestamp shown incorrectly sometimes when seeking while **paused**
demo -- https://www.youtube.com/watch?v=KaTCRS3j6qY

**OS**: OSX 10.9
**browsers:** Chrome, FF
**how to reproduce:**
1. start video
2. pause
3. seek
4. timestamp OK?
5. repeat 1) - 4) while 4) positive

**Comment by mmcc** [comment] 2015-07-25 00:45
Not able to reproduce in 5.0 and I think this may even be fixed in the latest 4.x.

**Closed** 2015-07-25 00:56 UTC
Labels: bug, confirmed, unclaimed
