### ISSUE TITLE
Video.js not found for packaged chrome app

### ISSUE THREAD

**Issue by tonyleong** [videojs/video.js#3050] opened 2016-01-29 07:31 UTC
Steps to reproduce:

1. Launch chrome browser with url of chrome://extension

2. Download the [videojs.zip](https://github.com/videojs/video.js/files/109360/videojs.zip), "Load unpacked extension"

3. You have video.js installed, "Launch it"

4. Right click on the app and inspect

5. Discover error message of videojs not found.

**Expected:**

videojs object available.

**Actual:**

videojs object not found.

<img width="905" alt="screen shot 2016-01-29 at 3 05 33 pm" src="https://cloud.githubusercontent.com/assets/16951137/12669513/2f720384-c69c-11e5-8f2f-175f12b63e0a.png">

**Note**

I debug on the error, and found this line from video.js is the cause.

`var bound = Function('binder', 'return function (' + boundArgs.join(',') + '){ return binder.apply(this,arguments); }')(binder);`

Chrome app have strict content security policy that blocks inline javascript scripting, hence is preventing video.js to execute.
https://developer.chrome.com/apps/contentSecurityPolicy

By replacing above line with empty function will let video.js run on chrome app.

`var bound = new function(){};`

**Comment by gkatsev** [comment] 2016-01-29 16:37
Thanks for the detailed report. Greatly appreciated. This seems like a duplicate of #2766. I guess we should fix it.

**Closed by gkatsev** 2016-01-29 16:37 UTC
