### ISSUE TITLE
Can't get dynamic video to play in IE8

### ISSUE THREAD

**Issue by chrisjchrisj** [videojs/video.js#2055] opened 2015-04-22 03:22 UTC
I'm sorry, i would post this at StackOverflow, but apparently I'm unable to temporarily.
My video.js player currently works with this:

![code1](https://cloud.githubusercontent.com/assets/4219457/7276041/2a924bb2-e8bc-11e4-9dd2-4334b494023b.png)

But, in IE8 that code also needs this flowplayer fallback code within the video tags:

![code2](https://cloud.githubusercontent.com/assets/4219457/7276049/3598b8a2-e8bc-11e4-9b2a-dcc22b825ed6.png)

However, it's my understand that there's no need for the flowplayer fall-back, because video.js has a fallback built-in. So, I'm trying to get rid of flowplayer, as a back-up.

In here: https://github.com/videojs/video.js/blob/stable/docs/guides/setup.md
under "Alternative Setup for Dynamically Loaded HTML" it says to add this(somewhere/somehow):

![code3](https://cloud.githubusercontent.com/assets/4219457/7276066/4c4e79a6-e8bc-11e4-9d4e-30fc516958f4.png)

I'm just not sure where that would go. How/where does it replace my object flowplayer code? Any comments/insight, or a code example, would be greatly appreciated. Much thanks.

**Comment by chrisjchrisj** [comment] 2015-04-22 03:25
[CODE]<video id="_1200k.mp4" class="video-js vjs-default-skin"
preload="none" width="445" height="340" controls
poster="[var.thumb_file]" data-setup='{techOrder: [‘flash’,’html5’}'>
<source src="http://www...com/uploads/[var.video_play]" type='video/mp4' />
</video>[/CODE]
But, in IE8 that code also needs this flowplayer fallback code within the video tags:

[CODE]<object class="vjs-flash-fallback" width="445" height="340" type="application/x-shockwave-flash"     data="https://releases.flowplayer.org/swf/flowplayer-3.2.1.swf">
<param name="movie" value="/flowplayer/flowplayer-3.2.16.swf" />
<param name="flashvars" value='config={"playlist":["/[var.thumb_file]", {"url":     "http://../uploads/[var.video_play]","autoPlay":false,"autoBuffering":true}]}' />
<img src="[var.thumb_file]" width="640" height="264" alt="Poster Image" title="No video playback capabilities." />
</object>[/CODE]
However, it's my understand that there's no need for the flowplayer fall-back, because video.js has a fallback built-in. So, I'm trying to get rid of flowplayer, as a back-up.

In here: https://github.com/videojs/video.js/blob/stable/docs/guides/setup.md
under "Alternative Setup for Dynamically Loaded HTML" it says to add this(somewhere/somehow):

[CODE]videojs("example_video_1", {}, function(){});[/CODE]

I'm just not sure where that would go. How/where does it replace my object flowplayer code? Any comments/insight, or a code example, would be greatly appreciated. Much thanks.

**Comment by mmcc** [comment] 2015-04-22 17:43
If you're hosting it yourself, you need to make sure to [set the swf location](https://github.com/videojs/video.js/blob/stable/docs/guides/setup.md#self-hosted). Whatever's going on with Flowplayer, just remove it. Unless you're actually dynamically creating video elements on the page, using the `data-setup` attribute should work fine. The `data-setup` attribute you've got in your code sample above is invalid, though, you're missing the closing `]` on your tech array (which you should just remove altogether unless you actually want Flash to be the primary player everywhere instead of a fallback).

As I said on your original [SO question](http://stackoverflow.com/questions/29424048/error-video-could-not-be-decoded-only-when-video-tries-to-play-in-ie11/29424326), if you want more specific help, we have to see an example. Put something together on [JSBin](http://jsbin.com/axedog/latest/edit) if you're still having trouble and we can help you debug.

**Closed by mmcc** 2015-04-22 17:43 UTC

**Comment by chrisjchrisj** [comment] 2015-04-22 18:16
Thanks for your reply. However, this isn't the same question as my SO question that you refered to. This is self-hosted dynamically loaded videos (the SO question was about static videos - which works successfully).

**Comment by mmcc** [comment] 2015-04-23 18:46
The [reduced test case](http://jsbin.com/dimoko/2/edit?html,console,output) you linked to in #2063 isn't terribly helpful since it doesn't load Video.js. Do you have something online that works in other browsers but not IE8? I'm unable to reproduce, dynamically loading videos [works fine](http://jsbin.com/boquyo/1/edit). Again, why are you forcing Flash first?

Just to reiterate from your original question, these issues are not meant to be general development support. If you think you've found a bug with Video.js, this is the right place, otherwise somewhere like StackOverflow is a better fit.

**Comment by chrisjchrisj** [comment] 2015-04-23 19:00
Thank you for your reply. Greatly appreciated. Yes, the displayed code works in all other significant browsers. I'm not intentionally trying to 'force Flash first'. I understand that SO is the proper place, but the messages I get from SO is I have to keep waiting days until I can post there again. Sorry for any inconvenience here. I'd be interested in hiring someone to help me with my particulars. I'm just trying to get this resolved presently instead of waiting for SO to allow another posting. Any additional help/suggestions/solutions will be greatly appreciated.

**Comment by mmcc** [comment] 2015-04-23 21:16
> I'm not intentionally trying to 'force Flash first'.

If you don't want to force Flash, then you can remove the `techOrder` altogether.

I really don't think there's anything else we can do to help given the information we have. If you need to hire someone to help you finish things, I'd suggest checking out something like [oDesk](http://odesk.com). I doubt you're going to have much luck trying to hire someone via this tracker.
