### ISSUE TITLE
ERROR: TypeError: Cannot read property 'BANDWIDTH' of undefined

### ISSUE THREAD

**Issue by joeflateau** [videojs/video.js#7318] opened 2021-07-13 15:53 UTC
## Description
From a master playlist with a single variant, this error is thrown constantly from `shouldSwitchToMedia`.

https://codepen.io/joeflateau/pen/abWpNZX?editors=1000

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Set src to a master m3u8 with a single variant

### Expected
Expect no errors, possibly no bandwidth checks at all.

### Actual
Every few seconds an error is logged

### Error output
VIDEOJS: ERROR: TypeError: Cannot read property 'BANDWIDTH' of undefined
    at shouldSwitchToMedia (video.js:60194)
    at MasterPlaylistController.shouldSwitchToMedia_ (video.js:60882)
    at SegmentLoader.<anonymous> (video.js:60908)
    at SegmentLoader.data.dispatcher (video.js:2257)
    at trigger (video.js:2393)
    at SegmentLoader.EventTarget$2.trigger (video.js:2796)
    at SegmentLoader.handleAppendsDone_ (video.js:56309)
    at SegmentLoader.checkAppendsDone_ (video.js:56117)
    at Object.action (video.js:56597)
    at shiftQueue (video.js:56515)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.13.3
#### browsers
what browser are affected?
all
#### OSes
what platforms (operating systems and devices) are affected?
all
### plugins
no

**Comment by gkatsev** [comment] 2021-07-13 21:25
Looks like it's fixed in VHS's main branch already. We're going to be doing a release soon, we'll try and remember to come back here after it's released.
You can see that it's fixed via https://videojs-http-streaming.netlify.app/, but it's broken via https://v2-9-1--videojs-http-streaming.netlify.app/.

**Comment by joeflateau** [comment] 2021-07-13 21:26
great! thank you!

**Comment by gkatsev** [comment] 2021-07-14 23:02
Just released 7.14.1, confirmed fixed via https://v7-14-1--videojs-preview.netlify.app/sandbox/index.html

**Comment by joeflateau** [comment] 2021-07-14 23:03
🙌

**Closed by gkatsev** 2021-07-14 23:02 UTC
