### ISSUE TITLE
Serious issue with iPad and the API from videojs

### ISSUE THREAD

**Issue by albi** [videojs/video.js#3184] opened 2016-03-16 08:35 UTC
I've run some tests why my movie player won't start on my iPad with iOS 9.2.1 (latest) and Videojs (latest). It seems that the API script for "Wait Until the Player is Ready" breaks the player itself. Only the spinner will show up, but the movie won't load or start.

Look at my reduced test case where at the bottom of the page the script runs. Test it on an iPad. (iPhone is fine.) http://alexanderalbrecht.de/test/

`<script>
	videojs("example_video_1").ready(function(){
		// inserting this script lets iPad Safari (iOS 9.2.1) to not load the video
	});
</script>
`

**Comment by jemoreno** [comment] 2016-03-16 13:26
Check out my response on #2845

**Comment by gkatsev** [comment] 2016-04-07 20:55
I'm unable to reproduce it on my ios devices. Also, if it's a data-setup issue, that's been fixed in the [latest release 5.8.8](https://github.com/videojs/video.js/releases/tag/v5.8.8).
I believe it's been fixed, so, going to close; we can continue the discussion and if it's still a problem, re-open.

Thanks.

**Closed by gkatsev** 2016-04-07 20:55 UTC

**Comment by albi** [comment] 2016-04-08 12:34
Looks like it is working with the new update.

**Comment by gkatsev** [comment] 2016-04-08 14:59
Cool, thanks for confirming @albi.
