### ISSUE TITLE
the vedio is not randering properly on my website. URL:- http://www.unouno.com.au/

### ISSUE THREAD

**Issue by sachinparmar222** [videojs/video.js#2249] opened 2015-06-10 06:43 UTC

**Comment by mmcc** [comment] 2015-06-10 17:50
The video on your home page is working fine for me. What browser / OS are you using?

**Comment by mmcc** [comment] 2015-06-10 18:25
Since I can't reproduce and we don't have any additional info to debug, I'm going to go ahead and close this. If you want us to continue to look into this, just comment on this thread with more information about the issue you're seeing and we can reopen.

**Closed by mmcc** 2015-06-10 18:25 UTC

**Comment by sachinparmar222** [comment] 2015-06-11 09:58
HI i am using iphone for test. video is not randering on iphone...

**Comment by mmcc** [comment] 2015-06-11 18:04
Your MP4 source uses the H.264 profile 4:2:2@L3, which I'm fairly certain isn't supported on iOS. I would suggest transcoding that to Main. You could go to Baseline for even more device support, but main at least gets you iPhone 4 and above.
