### ISSUE TITLE
currentTime indicator/dot jumping forward after clicking on previous time

### ISSUE THREAD

**Issue by andywells** [videojs/video.js#3945] opened 2017-01-13 20:50 UTC
## Description
Using the starter template (http://jsbin.com/axedog/edit?html,output) with no changes, except to update VideoJS from 5.0 to 5.11, I get the following behavior: If you play the video, click forward in time on the seekBar (do not drag), then click back in time on the seekBar (do not drag), the "dot" that indicates the currentTime jumps back to where it was before you clicked back in time. The behavior seems to happen consistently on certain computers, and not at all on others. Is anyone else experiencing this? There are two Macs (13" MacBook Pro - Early 2015 -Sierra 10.12.2, iMac - Mid 2011 - El Capitan 10.11.3) in my office on which it happens consistently, every single time. There is another Mac (15" MacBook Pro - Mid 2015 - Sierra 10.12.2) in my office on which it never happens, ever. I'm only seeing the behavior in Chrome.

## Steps to reproduce
1. Start playing the video
2. Click ahead in time on the seekBar
3. Click back in time on the seekBar

### Expected
The currentTime "dot" should be where you clicked back in time on the seekBar

### Actual
The currentTime "dot" jumps forward to where it was before you clicked back in time on the seekBar

### Error output
No errors

#### videojs
5.11
#### browsers
Chrome 55.0.2883.95
#### OSes
OSX 10.11.3 (El Capitan), OSX 10.12.2 (Sierra)
### plugins
no plugins

**Comment by gkatsev** [comment] 2017-01-13 21:36
This sounds like a duplicate of https://github.com/videojs/video.js/issues/3839 which is fixed in 5.16.0 (the latest pre-release of videojs). There's a fix 5.15.1 as well but apparently it doesn't cover all cases.

**Closed by gkatsev** 2017-01-13 21:36 UTC

**Comment by andywells** [comment] 2017-01-13 21:37
Thanks for pointing that out. Searched the issues, but was unable to find that one. Much appreciated.
