### ISSUE TITLE
Problems with the seekbar in chrome

### ISSUE THREAD

**Issue by juneg** [videojs/video.js#3941] opened 2017-01-13 15:12 UTC
## Description
Hello! We have been using videojs for a year more or less, and 3 days ago we realised that we had a problem with the seekbar. When the player is playing and you try to seek to a previous position, the video seeks correctly but the seekbar's pointer  goes to another position.

Perhaps the update of the chrome to 55.0.2883.87 could be involved with the problem.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.Play one video
2. Seek a new frame fordward (the player works OK)
3. Seek another frame backward,  you realize that the video goes to the correct position but the pointer in the seekbar can't stay at that frame and goes to another position forward.

#### videojs
what version of videojs does this occur with? v5.15.1 at least
#### browsers
what browser are affected? chrome

**Comment by gkatsev** [comment] 2017-01-13 16:57
We just merged another fix for the seeking issue and released it in 5.16.0. Please check it out.
Duplicate of https://github.com/videojs/video.js/issues/3839.

**Closed by gkatsev** 2017-01-13 16:57 UTC

**Comment by juneg** [comment] 2017-01-16 15:40
It works perfect! Thank you :-)
