### ISSUE TITLE
No seeking on Chrome

### ISSUE THREAD

**Issue by michaelao** [videojs/video.js#2190] opened 2015-05-22 12:34 UTC
It's impossible to seek on Chrome, not by clicking on the timeline, and not programmatically.

Clicking on the timeline will cause the video to start over.

You can try it on http://www.videojs.com.

IE and Firefox have no problem.

**Comment by mmcc** [comment] 2015-05-22 16:29
Hrm...that's weird. I'm not seeing this in Chrome 43 or 45 (Canary) on OS X and Windows 7. I'm going to close this because I'm unable to reproduce in any environment I have access to, but if you can point to a specific combination where this is reproducible just comment and we'll re-open.

**Closed by mmcc** 2015-05-22 16:29 UTC
