### ISSUE TITLE
RTMP no longer working?

### ISSUE THREAD

**Issue by haietza** [videojs/video.js#4779] opened 2017-12-01 20:36 UTC
## Description
RTMP with VideoJS does not appear to be working anymore. We had an implementation with 5.12 that was working. Please advise - you guys have been great with pointing out fixes in the code to get things working!

## Steps to reproduce
1. Browse to http://www.appstate.edu/~meltonml/videojs/video.html

### Expected
Expected video to play.

### Actual
Received error.

### Error output
FLASH: NetConnection.Connect.Rejected

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.12.6 (we are integrating with Moodle and this is what they use in their 3.2 version)
#### browsers
Chrome
#### OSes
Mac
### plugins
n/a

**Comment by gkatsev** [comment] 2017-12-01 22:21
I can reproduce. At first I thought it was because chrome is disabling flash but it doesn't seem to be the issue. Unfortunately, I don't really know much about RTMP but it seems like the rtmp endpoint is rejecting the request for some reason? I get similar errors in VLC and this wowza test player: https://www.wowza.com/testplayers

**Comment by mister-ben** [comment] 2017-12-12 21:31
This works for me in Chrome now. I guess something was fixed on the RTMP server side?

**Comment by gkatsev** [comment] 2017-12-12 21:38
Yup, going to chalk it up to server issues.

**Closed by gkatsev** 2017-12-12 21:38 UTC

**Comment by haietza** [comment] 2017-12-13 12:14
Yes - I'm sorry - a domain rule had been changed that I did not see initially. I apologize for the inconvenience - thanks so much for the quick response!!
