### ISSUE TITLE
Why do captions and subtitles not display in Safari browsers on macOS and iOS when using Video.js in this code?

### ISSUE THREAD

**Issue by rainentoyama** [videojs/video.js#8068] opened 2023-01-11 04:55 UTC
### Description

The code provided sets up a Video.js player using the **<video>** element with the id "player" and uses the **videoOptions** object to configure the player. Within the **videoOptions** object, a subtitle track is defined using the **tracks** option, and a source for the video is defined using the **sources** option. Despite this configuration, captions and subtitles are not displaying in Safari browsers on macOS and iOS but it works fine in Chrome (macOS only), Firefox(macOS only). and Opera (macOS only).
What could be the cause of this issue and what steps could be taken to resolve this problem?

### Steps to reproduce

```
<link href="https://vjs.zencdn.net/7.20.3/video-js.css" rel="stylesheet" />
<script src="https://vjs.zencdn.net/7.20.3/video.js"></script>
<video id="player" class="video-js"></video>
<script>
var videoOptions = videojs("player", {
  poster: "https://example.com/poster.jpg",
  controls: true,
  responsive: true,
  autoplay: false,
  preload: "auto",
  tracks: [
    {
      src: "https://example.com/caption.vtt",
      default: "true",
      kind: "captions",
      srclang: "en",
      label: "English",
    },
  ],
  sources: [
    { src: "https://example.com/hls.m3u8", type: "application/x-mpegURL" },
  ],
});
</script>
```

### What version of Video.js are you using?

7.20.3

### Video.js plugins used.

none

### What browser(s) including version(s) does this occur with?

Safari

### What OS(es) and version(s) does this occur with?

macOS High Sierra, iOS 15.7.2

**Comment by amtins** [comment] 2023-01-11 13:39
@rainentoyama  have you tried adding `crossorigin: 'anonymous'` in the configuration and does it fix your problem? Please see https://videojs.com/guides/text-tracks/#text-tracks-from-another-domain

```JavaScript
var videoOptions = videojs("player", {
  poster: "https://example.com/poster.jpg",
  controls: true,
  crossorigin: 'anonymous', // add this to you configuration
  responsive: true,
  autoplay: false,
  preload: "auto",
  tracks: [
    {
      src: "https://example.com/caption.vtt",
      default: "true",
      kind: "captions",
      srclang: "en",
      label: "English",
    },
  ],
  sources: [
    { src: "https://example.com/hls.m3u8", type: "application/x-mpegURL" },
  ],
});
```

We had a similar issue yesterday and I noticed that the `crossorigin` property does not survive between two media loads when the `loadMedia` method is used. I thought of creating a github issue asking if this behavior was intended. Any thoughts @gkatsev ?

**Comment by gkatsev** [comment] 2023-01-11 20:13
@amtins probably an oversight. Can you open a separate issue for that? It's likely because `loadMedia` removes the old video element, but I guess it doesn't get `crossorigin` set once the new video element is created. PRs welcome as well 🙂

**Comment by rainentoyama** [comment] 2023-01-12 02:01
> does it fix your problem

Yes, but it does not it fixed the problem.

However, using **document.createElement** method instead of using the **Videojs function**  to create the track element, set its attributes, and append it to the video element fix the problem. I'm using Safari version Version 13.1.2 on macOS High Sierra, and Safari for iOS 15.

```
<video id="player" class="video-js"></video>
<script>
document.addEventListener("DOMContentLoaded", function() {
  // create the source element
  var source = document.createElement("source");
  source.setAttribute("src", "https://example.com/hls.m3u8");
  source.setAttribute("type", "application/x-mpegURL");

  // create the track element
  var track = document.createElement("track");
  track.setAttribute("kind", "captions");
  track.setAttribute("src", "https://example.com/caption.vtt");
  track.setAttribute("srclang", "en");
  track.setAttribute("label", "English");
  track.setAttribute("default", "");

  // append the source and track elements to the video element
  var video = document.getElementById("player");
  video.appendChild(source);
  video.appendChild(track);

var videoOptions = {
	poster: 'https://example.com/poster.jpg',
	controls: true,
	responsive: true,
	autoplay: true,
	preload: 'metadata'
	}
// create the player using the above options
videojs('player', videoOptions);

});
</script>
```

**Comment by valentinld** [comment] 2023-03-21 18:09
@rainentoyama Try to add your captions using the `addRemoteTextTrack` method:

```javascript
const player = videojs("player", {
  poster: "https://example.com/poster.jpg",
  controls: true,
  autoplay: false,
  preload: "auto"
});

player.src({
  type: "application/x-mpegURL",
  src: "https://example.com/hls.m3u8"
});

player.addRemoteTextTrack({
  src: "https://example.com/caption.vtt",
  kind: "subtitles",
  srclang: "en",
  label: "English",
  default: true
});
```

It is the recommended way to add captions according to the [documentation](https://videojs.com/guides/text-tracks/#a-note-on-remote-text-tracks) and seems to fix the problem (tested on Safari & Chrome on both MacOS and iOS)

**Comment by wseymour15** [comment] 2023-04-25 17:04
This appears to have been resolved, so I am closing this ticket. Please feel free to re-open this ticket if there are further questions.

**Closed by wseymour15** 2023-04-25 17:04 UTC
Labels: bug, needs: triage
