### ISSUE TITLE
Autoplay doesn't work when `currentSrc` is set

### ISSUE THREAD

**Issue by jamesgorrie** [videojs/video.js#3071] opened 2016-02-03 13:28 UTC
It appears, if a page is loaded, we then have a `currentSrc` set.

[This then doesn't run the `setSrc` function as the `current.src === this.el_.src`](https://github.com/videojs/video.js/blob/8f2bc92412c4b95641cf271faa5eadb3207c4147/src/js/tech/html5.js#L37)

So either this PR should include:
```JS
if ((this.src() || this.currentSrc()) && this.tag && this.options_.autoplay && this.paused()) {
//...
}
```

Or the `setSrc` method should be updated.

[Here is an example](https://jsbin.com/hohogu/2/edit?html,js,output) where autoplay won't work when we have `currentSrc` set from the browser.

**Comment by rbran100** [comment] 2016-04-29 15:57
@jamesgorrie Your fix works well in multiple browsers, I posted a PR above.

**Comment by gkatsev** [comment] 2016-04-29 21:49
That's really weird, I can reproduce it in the jsbin example but if I try to do it myself in the sandbox files, it works just fine in chrome 50.

**Comment by gkatsev** [comment] 2016-04-29 21:50
Ah, I figured out what the issue is. It's a Mixed Content issue. The jsbin page is running over https but it's trying to load an http video. For whatever reason it fails to load the first video but somehow succeeds for the second.

**Comment by gkatsev** [comment] 2016-04-29 21:52
Here's an updated example that seems to be working just fine: https://jsbin.com/vefuzohuma/edit?html,js,output

**Comment by gkatsev** [comment] 2016-06-20 20:17
@jamesgorrie @rbran100 hey, any of you have any thoughts about my comments and questions above?

**Comment by rbran100** [comment] 2016-06-20 20:51
@gkatsev When I read this mixed content seemed like a likely culprit, I put it on my list to test and get back to and just have not gotten there yet. sorry to leave you hanging.

**Comment by gkatsev** [comment] 2016-06-20 20:58
Thanks for getting back to me. Let me know if you get any further with that.

**Comment by gkatsev** [comment] 2016-06-28 02:04
@rbran100 cool, it might still be worse pulling that PR in. If you update it with the latest code we can pull it in.

**Comment by gkatsev** [comment] 2016-07-18 20:35
I merged the PR anyway, hopefully, it'll make life easier.

**Closed by gkatsev** 2016-07-18 20:35 UTC
