### ISSUE TITLE
progress bar and control doesn't work with flash play

### ISSUE THREAD

**Issue by ptitbibice** [videojs/video.js#2186] opened 2015-05-21 14:29 UTC
Hi,
i have a problem with a progress bar.
My progress-bar doesn't work when i play a flash video.
Just, the player bug whan i play a flash video. The flash video playing, but the option (play, sond, progress bar) doesn't work.

**Comment by gkatsev** [comment] 2015-05-21 15:21
Hi,
Can you please provide some more info? Like what version of videojs you are using. Also, how you're loading the webpage (through a local webserver or just opening the file up in the browser).
If you're using videojs in master, it might be broken. See #2184.

**Comment by ptitbibice** [comment] 2015-05-21 15:33
hi,

i use 4.12/video.js and i use this in a website.
i have follow the get started video js.
There are a good url for my movies because, this movie is played. 
Just the control video js is broken.

**Comment by ptitbibice** [comment] 2015-05-22 10:15
Hi 
here is my code : 

<head>
<link href="//vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
<script src="//vjs.zencdn.net/4.12/video.js"></script>
<script>
videojs.options.flash.swf = "url.swf";
</script>
</head>

<body>
<video id="videoLancement" class="video-js vjs-default-skin vjs-big-play-centered" controls preload="auto" width="100%" height="502" data-setup="{}">
                        <source src="url.ogv" type="video/ogg" />
                        <source src="url.webm" type="video/webm" />
                        <source src="url.mov" type="video/quicktime" />
                        <source src="url.mp4" type="video/mp4" />
</video>
</body>

i think that a bug exist on video js.
Someone can confirmed ?

**Comment by mmcc** [comment] 2015-05-24 16:10
I'm unable to reproduce, things seem to be working fine for me. Can you show us a live example somewhere of this not working so we can try and help debug? Maybe try and reproduce on [JSBin](http://jsbin.com/axedog/latest/edit)?

**Comment by ptitbibice** [comment] 2015-05-25 12:57
the console done :
"error"
"Script error. (line 0)"
i can't play the flash video.
i can't reproduce the bug but i can't play flash video now..
Can i have a example on JSBin with a flash video ?
Thanks for your support

**Comment by mmcc** [comment] 2015-07-25 01:19
We can't do anything else here without a reduced test case. Closing.

**Closed by mmcc** 2015-07-25 01:19 UTC
Labels: bug, needs: confirmation, needs: reduced test case
