### ISSUE TITLE
Emulated closed captions should hide on video end

### ISSUE THREAD

**Issue by stsvilik** [videojs/video.js#3714] opened 2016-10-25 14:47 UTC
## Description

Emulated captions/subtitles remain visible when video ends
## Steps to reproduce

Play video with closed captions and wait until it ends (assuming there are no plug-ins/actions that handle video end)
1. Play video that has CC
2. Enable CC
3. Play to the end
4. Inspect DOM for .vjs-text-track-display - it is visible
### Expected

Closed-captions display should hide
### Actual

Last displayed closed-caption remain on the screen after video ends
#### videojs

5.11.8
#### browsers

Chrome, Firefox, Safari
#### OSes

MacOS El Capitan
### plugins

None

**Comment by mister-ben** [comment] 2016-10-26 20:16
Is the end time of the last caption equal or greater than the duration? The caption will remain in that case as currentTime doesn't reset to 0. That's also the behaviour of Chrome's native HTML5 video.

You could set the track's `mode` to `disabled` on the player's `ended` event.

**Comment by stsvilik** [comment] 2016-10-26 21:52
@mister-ben I'm not sure if last cue is in the duration timeframe, but disabling track mode myself seems hacky. Would that even work after video ended? I thought that display updates on time change and since its stopped, there would be nothing to trigger the update.

**Comment by boushley** [comment] 2016-11-08 15:10
Are there subtitles actually visible, or is this only an issue if you inspect the DOM?

Also couldn't you simply hide it with a CSS rule like `.video-js.vjs-ended .vjs-{subtitlesglass}` and then a `diaplay: none;` style?

**Comment by stsvilik** [comment] 2016-11-09 04:39
@boushley Yes subtitles are actually visible. The point I'm trying to make is that native component should be smarter about hiding subtitles after video has done playing. Last thing I want to do is hack  it.

**Comment by boushley** [comment] 2016-11-09 04:48
@stsvilik understood, and the concern makes sense. Given the presence of an easy workaround though probably wouldn't focus on it soon.

**Comment by stsvilik** [comment] 2016-11-09 15:01
@boushley as long as this issue is acknowledged and scheduled I'm a happy camper :)

**Comment by gkatsev** [comment] 2016-12-08 22:52
I would be hesitant to make this change because this is how the browsers work natively -- I've confirmed with Firefox, Chrome, and Safari -- plus, it kind of makes sense for them not to go away if the end time isn't equal or less than the duration.
If the issue is that the end time of a cue matches the duration but it still shows up, that's definitely something that we should fix.

**Comment by stsvilik** [comment] 2016-12-20 22:07
@gkatsev I believe its the second case. Video has ended (event "ended" fired, current time = duration), yet last visible caption remains visible.

**Comment by misteroneill** [comment] 2016-12-22 15:01
> Video has ended (event "ended" fired, current time = duration), yet last visible caption remains visible.

What @gkatsev is getting at is that the content ending does not necessarily mean that captions should not be visible. If the `endTime` of a cue is greater than the `duration` of the content, the caption _should_ remain visible after `"ended"`. This is the correct behavior (and the behavior of the native video element).

If this is your situation, you can either fix the captions content or, if that's not possible, use the workaround @mister-ben suggested.

If you can confirm the opposite - a cue with an `endTime` less than or equal to the content `duration` that remains after `"ended"` - with a reduced test case, that is something we would gladly investigate and fix.

**Comment by stsvilik** [comment] 2016-12-22 17:09
@misteroneill I looked deeper into it, and it turns out that caption remains visible even after textTracks have been removed from the video tag all together. So this case makes it difficult for me to assess weather the last cue items' ```endTime``` is less or greater than duration. From usability perspective it appears unnatural (to see comments after end), but if you want to stick to "others have it like that so do we" it is fine as well.

**Comment by gkatsev** [comment] 2018-01-02 23:20
The caption display staying after the track has been removing is a separate issue for sure, we probably don't update the display properly when tracks are removed and that's definitely something that should be fixed.
I think the duration thing isn't an issue, though.

**Comment by gkatsev** [comment] 2018-09-25 16:11
I just tested this against latest version of Video.js and cannot reproduce. Going to close as fixed.

**Closed by gkatsev** 2018-09-25 16:11 UTC
Labels: needs: reduced test case, pinned
